### ISSUE TITLE
Node v4 Server Requirements

### ISSUE THREAD

**Issue by jhuckaby** [jhuckaby/Cronicle#1]
Please note, if you want to run Cronicle with Node.js v4 or higher, you will need an OS with GCC 4.8+, or Clang 3.5+.  This is a requirement of some of the C++ npm dependencies.

Reference: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

> To compile native modules for io.js v3 or Node.js v4, a C++11 standard-compilant compiler is required. More specifically, either gcc 4.8 (or later), or clang 3.5 (or later) works.

Specifically, CentOS 6.x does **not** satisfy these requirements.  You'll need CentOS 7 or later.  Amazon's AWS EC2 Linux flavor seems fine, as does OS X 10.8 and up.

**Comment by iambocai** [comment]
Sad to hear this, but it seems it works well on my CentOS 6.5 server, the only problem is: it will crash when use "Least CPU usage" or  "Least Memory usage" as the algorithm for choosing a server from the target group. (so I only use Random/RR :) )

another strange problem is, the server can   start  by command line,  but can't start by a script, for example:

#$: cat  supervisor_control.sh  

> #!/bin/bash -x
>
>WORKDIR=$(cd $(dirname $0)/../ && pwd)
>PIDFILE="${WORKDIR}/logs/cronicled.pid"
>CONTROL="${WORKDIR}/bin/control.sh"
>
>cd ${WORKDIR}
>
>trap "${CONTROL} stop; exit 0" SIGQUIT SIGTERM SIGSTOP SIGKILL SIGABRT 
>
>while true
>do
>    if [ -f "${PIDFILE}" ] && [ -d "/proc/$(cat ${PIDFILE})/" ]
>    then
>        CWD=$(/bin/readlink /proc/$(cat ${PIDFILE})/cwd) 
>        if [ X"$CWD" == X"$WORKDIR" ]
>        then
>            sleep 10
>            continue
>        fi
>    fi
>    echo "$(date +'%F %T') : Starting Cronicle ..."
>    ${CONTROL} stop
>    ${CONTROL} start
>    sleep 5
>done 

#$: sh supervisor_control.sh  

got crash.log:

> Sat Nov 19 2016 18:26:02 GMT+0800 (CST)
> Error: Invalid mask for ip4: undefined
>     at new Netmask (/opt/cronicle/node_modules/netmask/lib/netmask.js:88:15)
>     at module.exports.Class.create.calcBroadcastIP (/opt/cronicle/lib/discovery.js:149:16)
>     at module.exports.Class.create.setupDiscovery (/opt/cronicle/lib/discovery.js:26:69)
>     at module.exports.Class.create.startup (/opt/cronicle/lib/engine.js:91:8)
>     at /opt/cronicle/node_modules/pixl-server/server.js:190:10
>     at /opt/cronicle/node_modules/async/lib/async.js:181:20
>     at Object.iterate [as _onImmediate] (/opt/cronicle/node_modules/async/lib/async.js:262:13)
>     at processImmediate [as _immediateCallback] (timers.js:363:15)

`

**Comment by jhuckaby** [comment]
Hmm, it sounds like you are having two completely different issues, and neither of them are related to this bug, haha :)

Can you post a crash log and/or stack trace when trying to use Least CPU / Least Memory?  That really shouldn't be happening.

Regarding your supervisor control script, I cannot figure out why it is failing.  That stack trace points to when the auto-discovery code is trying to determine your server's LAN broadcast IP, so it can send out UDP packets to nearby Cronicle servers so they can auto-discover each other.  I have never heard of this failing before.  The only thing I can think is that somehow your server's network isn't accessible from inside the supervisor script.  Meaning, there isn't a IPv4 LAN interface or one just isn't there to grab.

This particular bit of code is simply calling Node's built-in [os.networkInterfaces()](https://nodejs.org/api/os.html#os_os_networkinterfaces) function, and locating the first interface that has `family` set to `IPv4` and `internal` set to `false`.  It then expects a valid IPv4 address and mask, which apparently isn't happening correctly on your server when started from your supervisor script.  Looks like one or the other is set to undefined.  Totally bizarre.

Can you please run this command from your server and paste the output here?

```
node -e 'console.log(require("os").networkInterfaces());'
```

Thanks.

**Comment by iambocai** [comment]
### execute in cmdline: 

>  $: node -e 'console.log(require("os").networkInterfaces());'
{ lo: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true } ],
  eth0: 
   [ { address: '192.168.6.0',
       netmask: '255.255.240.0',
       family: 'IPv4',
       mac: 'fa:16:3e:62:77:b4',
       internal: false },
     { address: 'fe80::f816:3eff:fe62:77b4',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'fa:16:3e:62:77:b4',
       scopeid: 2,
       internal: false } ] }

### put it into a script and execute(same):

> $: cat test.sh 
#!/bin/bash
node -e 'console.log(require("os").networkInterfaces());'
>
> $: sh test.sh  
{ lo: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true } ],
  eth0: 
   [ { address: '192.168.6.0',
       netmask: '255.255.240.0',
       family: 'IPv4',
       mac: 'fa:16:3e:62:77:b4',
       internal: false },
     { address: 'fe80::f816:3eff:fe62:77b4',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'fa:16:3e:62:77:b4',
       scopeid: 2,
       internal: false } ] }

**Comment by iambocai** [comment]
and when use use "Least CPU usage" or "Least Memory usage" as the algorithm for choosing a server from the target group, the crash log is like this (guess it failed on get slave's resource infomation?):

>Thu Nov 17 2016 16:31:00 GMT+0800 (CST)
TypeError: Cannot read property 'hostname' of null
    at constructor.chooseServer (/opt/cronicle/lib/job.js:332:45)
    at /opt/cronicle/lib/job.js:118:25
    at /opt/cronicle/node_modules/async/lib/async.js:726:13
    at /opt/cronicle/node_modules/async/lib/async.js:52:16
    at /opt/cronicle/node_modules/async/lib/async.js:269:32
    at /opt/cronicle/node_modules/async/lib/async.js:44:16
    at /opt/cronicle/node_modules/async/lib/async.js:723:17
    at /opt/cronicle/node_modules/async/lib/async.js:167:37
    at /opt/cronicle/lib/job.js:54:6
    at /opt/cronicle/node_modules/pixl-server-storage/list.js:775:6

**Comment by iambocai** [comment]
My install steps:

1.  yum install -y nodejs npm
2.  npm install -g n
3.  n stable
4. <install Cronicle>

**Comment by jhuckaby** [comment]
Dang, that is very strange.  I cannot reproduce either issue, but I did put in some "defensive" code which should prevent crashes in those two cases.  It has been released as v0.6.3.

Thanks for the report.  Please let me know if it keeps happening!
