### ISSUE TITLE
Get web hook notifications only on failure

### ISSUE THREAD

**Issue by alexbogias** [jhuckaby/Cronicle#100]
Is it possible to only get web hook notifications on failure? If not can you add this option?

**Comment by jhuckaby** [comment]
Yup, you can do this in one of two ways:

The first way is to actually parse the JSON contained in the POST body of the web hook notification request.  Contained within this JSON document is an `action` property, which will be set to one of the following: `job_start`, `job_complete`, `job_failure` or `job_launch_failure`.  If you only want to be notified on errors, simply ignore the first two, and only act on `job_failure` and `job_launch_failure`.

The second way is a server configuration change.  In your `config.json` file, locate the following element.  Note that if you have upgraded from an older version of Cronicle, this element may not exist.  In which case add it:

```js
"web_hook_text_templates": {
	"job_start": "Job started on [hostname]: [event_title] [job_details_url]",
	"job_complete": "Job completed successfully on [hostname]: [event_title] [job_details_url]",
	"job_failure": "Job failed on [hostname]: [event_title]: Error [code]: [description] [job_details_url]",
	"job_launch_failure": "Failed to launch scheduled event: [event_title]: [description] [edit_event_url]"
},
```

Then, simply remove the keys you don't want notifications for.  In your case you'd want to remove `job_start` and `job_complete`.  Then those web hooks will simply never fire, and it'll only fire for the two error cases.

Hope this helps!

**Comment by alexbogias** [comment]
Sorry for taking so long. I tested the second way and worked great. I didn't want to remove the elements and I know that in JSON files there are no comments so i just renamed key to something else like "job_start" => '__job_start" and looks fine now. Thanks a lot for your feedback @jhuckaby
