### ISSUE TITLE
Completed Tab shows no jobs executed 

### ISSUE THREAD

**Issue by sonam1318** [jhuckaby/Cronicle#101]
## Summary
The "Completed" tab in the ui shows "0 events found".

## Steps to reproduce the problem

Create a new event "Test".
Run "Test".
Click the link that appears on the top of the page to view its progress.
The job has completed successfully.
Go to Completed tab and we see zero executions.
## Your Setup

We have 1 Cronicle Master connected to a couchbase cluster of 3 servers.
It is confirmed that it logs the jobs in the database correctly.
### Operating system and version?

Docker container - Debian GNU/Linux 9

### Node.js version?

v8.11.3
### Cronicle software version?
Version 0.8.22

### Are you using a multi-server setup, or just a single server?
Single
### Are you using the filesystem as back-end storage, or S3/Couchbase?
Couchbase cluster of 3 servers

**Comment by tatototino** [comment]
I have gotten the same problem with an environment using couchbase. Even the job is executed correctly no job appear on jobs completed screen, no stats and no history.

Regards,

**Comment by jhuckaby** [comment]
What a bizarre problem.  I will try to reproduce this as soon as I can.  Thanks for reporting it!

**Comment by jhuckaby** [comment]
This should be fixed in [Version 0.8.24](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.24).  Thanks for reporting it!

**Comment by sonam1318** [comment]
Thanks for the quick fix, it works!! :)

**Comment by tatototino** [comment]
Thanks for the quick fix, it works!! :)
