### ISSUE TITLE
Sugestion: Include Seconds for specific demand

### ISSUE THREAD

**Issue by tatototino** [jhuckaby/Cronicle#102]
We have a specific demand to run a job an specific time like 14:03:03 and I´ve found out cronicle does´not include this configuration second time. Can you include it?

Regards,

**Comment by areyesES** [comment]
To contribute to this enhancement - There are some jobs that need to run between time 1 and time 2 (say 8am to 3pm) every 5 minutes. Including this option as well would be appreciated.

**Comment by jhuckaby** [comment]
These are two different feature requests.  @areyesES if you want to schedule a job to run between 8 AM to 3 PM every 5 minutes, that feature exists now.  Just configure the hours and minutes like this:

<img width="658" alt="screenshot 2018-08-23 22 53 00" src="https://user-images.githubusercontent.com/700765/44567454-4f40a580-a727-11e8-877d-cbee432537bd.png">

@tatototino Adding support for seconds would be quite difficult.  The entire system was built to only have scheduling precision down to the minute.  The only thing I can think of is to offer a very simple second "offset" so a job is delayed by N seconds before starting.  I will try to get this onto the roadmap for v2.0.  Thank you for the feature request.

**Comment by tatototino** [comment]
@jhuckaby I came with a easy workaround . I can setup a executable parameter of the plugin to receive seconds and I can setup it on event configuration. So my script  can delay the execution using sleep command and the seconds it receive by the event configuration parameter.

It´s like you said.

Regards,
