### ISSUE TITLE
WebHook Enhancement

### ISSUE THREAD

**Issue by areyesES** [jhuckaby/Cronicle#103]
## Summary
After using the new webhook Slack interface, could there be two webhook's that are automatic for job fails/completes. This would allow you to set 2 different Slack webhooks;  one for job_start/complete_channel and then to job_fail_channel. 
If you have many jobs going around the same time, the single Slack channel can get kinda of messy.
Separating them would be highly suggested. 

## Steps to reproduce the problem

No problem to reproduce.
## Your Setup

Single Master, many slaves
### Operating system and version?

RHEL 7.5
### Node.js version?

v6.14.3
### Cronicle software version?

0.8.22
### Are you using a multi-server setup, or just a single server?
Multi-server
### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem
### Can you reproduce the crash consistently?
No crash
## Log Excerpts
N/a

**Comment by jhuckaby** [comment]
Thank you for the feature request.  However, I am afraid this may over-complicate the web hook system, and people would be confused.

Here are two things which may help you.  First, you can customize which web hook events are sent.  For example, you can totally disable the `job_start` and `job_complete` events, and only get notifications for errors.  Instructions for doing this are in the [Slack Webhook Integration](https://github.com/jhuckaby/Cronicle/wiki/Slack-Webhook-Integration) Wiki.

Secondly, you can customize the web hook URL for each individual event.  So you can have certain events going to certain Slack channels, just by varying the web hook URL inside the Web UI for editing each event.

Third, you can simply write a small proxy script that lives behind a URL, and have Cronicle point to your script first.  Then you can decide which Slack Webhook URL to fire off and make your own secondary request from your script.  That way you have complete control over the notification experience.

Would one of these things help you achieve your goal?
