### ISSUE TITLE
Version Upgrade Steps

### ISSUE THREAD

**Issue by jagansankara** [jhuckaby/Cronicle#104]
Hi,

First i want to Thank You 👍 for this useful tool. It is very helpful for me to manage my servers.

I'm totally new to Node.js and for me it took some time to setup Node.js & Cronicle in my server. I've been using Cronicle last 2 months and now i see there is few bug fixing and feature enhancement. 

The problem is now i don't know how to upgrade Cronicle with its latest version. 

Can you update your Readme doc with upgrade steps also. It'll be helpful for newbie's like me :)

Thanks in advance..!

**Comment by jhuckaby** [comment]
Thank you for your kind words.  There are actually upgrading instructions already in the README.  I apologize if they were hard to find.  Here is the link:

https://github.com/jhuckaby/Cronicle#upgrading-cronicle

And here is a copy of the chapter:

## Upgrading Cronicle

To upgrade Cronicle, you can use the built-in `upgrade` command:

```
/opt/cronicle/bin/control.sh upgrade
```

This will upgrade the app and all dependencies to the latest stable release, if a new one is available.  It will not affect your data storage, users, or configuration settings.  All those will be preserved and imported to the new version.  For multi-server clusters, you'll need to repeat this command on each server.

Alternately, you can specify the exact version you want to upgrade (or downgrade) to:

```
/opt/cronicle/bin/control.sh upgrade 1.0.4
```

If you upgrade to the `HEAD` version, this will grab the very latest from GitHub.  Note that this is primarily for developers or beta-testers, and is likely going to contain bugs.  Use at your own risk:

```
/opt/cronicle/bin/control.sh upgrade HEAD
```

Hope this helps!
