### ISSUE TITLE
Progress not shown/updated

### ISSUE THREAD

**Issue by zakalibit** [jhuckaby/Cronicle#110]
## Summary

No progress update shown on the job status page while job is running.

## Steps to reproduce the problem

My plugin prints progress every 5 seconds, something like
print json.dumps({'progress': 0.2})

The same with shell plugin:

#!/bin/sh

# Enter your shell script code here
echo "0.2"
sleep 5
echo "0.4"
sleep 5
echo "0.8"
sleep 5
echo "1"
### Operating system and version?

CentOS 7.2

### Node.js version?
v8.11.4

### Cronicle software version?

0.8.26

### Are you using a multi-server setup, or just a single server?
single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem

**Comment by jhuckaby** [comment]
Hello.  I'm sorry, but I don't know what programming language this is:

```
print json.dumps({'progress': 0.2})
```

But just from the function name ("json.dumps") it sounds like this may be *pretty-printing* the JSON output, i.e. spreading it across multiple lines, and indenting each line.  Unfortunately this won't work.  Your JSON needs to be [newline delimited](https://github.com/ndjson/ndjson-spec), meaning the JSON document needs to be compacted all onto one line, followed by a single line-feed character.  Like this:

```js
{"progress":0.2}
```

This is described in detail in the [JSON Output](https://github.com/jhuckaby/Cronicle#json-output) section of the documentation.

As for using the Shell Plugin, this output you are printing will not work:

```sh
echo "0.2"
sleep 5
echo "0.4"
sleep 5
echo "0.8"
sleep 5
echo "1"
```

The Shell Plugin only accepts integer numbers between 0 - 100, followed by a `%` symbol, denoting percentage.  Fixed example:

```sh
echo "20%"
sleep 5
echo "40%"
sleep 5
echo "80%"
sleep 5
echo "100%"
```

This output format is described in detail in the [Shell Plugin](https://github.com/jhuckaby/Cronicle#built-in-shell-plugin) section of the docs.

Hope this helps!

**Comment by zakalibit** [comment]
Hi,

this is python 
print json.dumps({'progress': 0.2})

and it does not do any pretty printing by default.

I found the why it was not working, stdout is buffered in python, so either need to run with -u python command line option, or flush stdout explicitly with sys.stdout.flush()

Thanks,
Alex
