### ISSUE TITLE
Backup Servers' homepage keeps reloading

### ISSUE THREAD

**Issue by shammishailaj** [jhuckaby/Cronicle#115]
## Summary
I have installed cronicle on two machines in cluster mode. Let's call them S001 and S002. S002 has been created from an image of S001 so essentially it is the same. When I open http://S001:3012 it works. When I try to open http://S002:3012 , it opens the page but keeps refreshing the homepage in a loop. 

## Steps to reproduce the problem

Install cronicle in cluster mode on one machine. create and image of this machine and launch another machine from this image. 

### Operating system and version?
Ubuntu 16.04

### Node.js version?
v6.14.4

### Cronicle software version?
v0.8.28

### Are you using a multi-server setup, or just a single server?
Multi-Server
### Are you using the filesystem as back-end storage, or S3/Couchbase?
S3
### Can you reproduce the crash consistently?
Yes
## Log Excerpts
I am not sure which logs to give. Please let me know which ones do you want.

**Comment by jhuckaby** [comment]
It sounds like your servers are confused as to which one is master.  Make sure your servers each have a unique hostname (this is very important), and both are listed on the server page.

Also, you cannot load up the UI on a non-master server.  It sounds like that may be happening, as the only point in the code where it ever refreshes the UI is if the WebSocket connects to a non-master server.

Good luck!

**Comment by shammishailaj** [comment]
> Also, you cannot load up the UI on a non-master server. It sounds like that may be happening, as the only point in the code where it ever refreshes the UI is if the WebSocket connects to a non-master server.

I am guessing, that might be the case as I am sure that the hostnames are properly set. Also, the Severs seem to know which of them is which. Please see the screenshot:

http://prntscr.com/kxysoh
