### ISSUE TITLE
feature request: new api call get_event_history

### ISSUE THREAD

**Issue by cbzittoun** [jhuckaby/Cronicle#116]
First, thank you very much for all the work, Cronicle is a brilliant tool!

One thing that would be very useful on our side is the ability to retrieve an event's history details (all jobs completed or failed, with start time, duration etc) through the API.

**Comment by jhuckaby** [comment]
Thank you!

That API already exists -- it just hasn't been properly documented yet.  This should get you started:

### get_event_history

```
/api/app/get_event_history/v1
```

This fetches historical completed jobs for an event, and returns details about them.  It supports pagination to fetch chunks, with the default being the first 50 jobs (in descending order from the latest).  Both HTTP GET (query string) or HTTP POST (JSON data) are acceptable.  Parameters:

| Parameter Name | Description |
|----------------|-------------|
| `id` | **(Required)** The Event ID to fetch job history for. |
| `offset` | (Optional) The offset into the data to start returning records, defaults to 0. |
| `limit` | (Optional) The number of records to return, defaults to 50. |

TBD Example request and response.

Also, make sure you use an [API Key](https://github.com/jhuckaby/Cronicle#api-keys) for this.

**Comment by cbzittoun** [comment]
That's awesome.
Thank you
