### ISSUE TITLE
Empty History/Completed when Using Couchbase DB

### ISSUE THREAD

**Issue by rrindels** [jhuckaby/Cronicle#122]
## Summary
When utilizing couchbase for storage. Jobs are scheduling and completing, but the completed jobs are not showing in the UI.

## Steps to reproduce the problem
Configure Cronicle and Couchbase per the default instructions. Schedule a 1 minute HTTP check. After a manual runs / minutes, the Home tab shows completed jobs however the history / completed page shows no jobs. 

Couchbase.log shows : [1538538060.921][2018-10-03 03:41:00][dev1.rrindels.ptx.accuoss.com][Couchbase][error][couchbase][Failed to fetch key: cronicle/logs/completed: The key does not exist on the server][]

Storage.log shows : [1538538480.719][2018-10-03 03:48:00][dev1.rrindels.ptx.accuoss.com][Storage][error][storage][Failed to dequeue custom task: CouchbaseError: Failed to fetch key: cronicle/logs/completed: The key does not exist on the server][]

## Your Setup
 Couchbase Version: Community Edition 5.1.1 build 5723 

Simple Test System Setup Default Out of the Box

### Operating system and version?
Centos 7 

### Node.js version?
Node.js Version : V8.11.3

### Cronicle software version?
0.8.15

### Are you using a multi-server setup, or just a single server?
Single Server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Couchbase
"Storage": {
                "engine": "Couchbase",
                "Couchbase": {
                        "connectString": "couchbase://127.0.0.1",
                        "bucket": "cronicle",
                        "username": "cronicle",
                        "password": "cronicle",
                        "serialize": false,
                        "keyPrefix": "cronicle"
                }
        },

### Can you reproduce the crash consistently?
Yes. 

## Log Excerpts
Webserver.log
[1538538018.384][2018-10-03 03:40:18][dev1.rrindels.ptx.accuoss.com][WebServer][debug][6][Invoking handler for request: POST /api/app/get_history: API][]

Couchbase.log
[1538538900.656][2018-10-03 03:55:00][dev1.rrindels.ptx.accuoss.com][Couchbase][error][couchbase][Failed to fetch key: cronicle/logs/completed: The key does not exist on the server][]

**Comment by jhuckaby** [comment]
I believe this is a duplicate issue.  See [Issue #101](https://github.com/jhuckaby/Cronicle/issues/101).  Fixed in [Cronicle v0.8.24](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.24).

Let me know if the issue persists after upgrading.
