### ISSUE TITLE
Suggestion: Consider typescript

### ISSUE THREAD

**Issue by ScreamZ** [jhuckaby/Cronicle#137]
Hello :)

First of all thanks for all your work.

This project is pretty new and seems really promising, I'm happy to discover it so early! I've seen, many JS project editor switch to typescript once they reach a great size and I think this project will, due to his awesome concerns. 

I think this might be a good idea to consider using typescript in a near future, this would prevent a total rewriting ? 

Best regards

**Comment by jhuckaby** [comment]
Hello, and thank you for the suggestion.  Unfortunately I know absolutely nothing about TypeScript, having never used it.  I'm afraid I just don't have the time, but I do appreciate the input!  Thanks again!
