### ISSUE TITLE
Linux Service

### ISSUE THREAD

**Issue by bwburch** [jhuckaby/Cronicle#14]
Using shell script to restart a linux service and the job never finishes, how can I configure the job to execute and finish.

example:   service myservice restart 

the job never finishes and the only way to get a status is to abort the job and when I do that it always shows job result as error.

**Comment by jhuckaby** [comment]
I do not believe this is a bug in Cronicle.  The service you are restarting likely isn't forking or detaching from the terminal properly.  Cronicle always waits for the process to exit before declaring the job as complete, so some sub-process (probably a child process forked during your service startup) is still lingering and is attached to the terminal.  Note that even a forked process can still remain attached -- it has to explicitly detach itself after forking.

If this is your own service you are restarting, make sure you are doing a [fork](https://en.wikipedia.org/wiki/Fork_(system_call)) and detaching the forked process from the calling terminal, allowing the main process to exit cleanly.  You can also try launching it using the [nohup](https://ss64.com/bash/nohup.html) call.

As a last resort, if you are not in control of this service and/or have no other option, you can try launching the shell command in the background with `&` and redirecting its STDOUT and STDERR to `/dev/null`.  Something like this maybe:

```
service myservice restart >/dev/null 2>&1 &
```

Good luck.
