### ISSUE TITLE
Always-running jobs

### ISSUE THREAD

**Issue by eitchtee** [jhuckaby/Cronicle#146]
Would it be possible to add a different type of job that is just always running?

Instead of firing up at a specified time, it should run once and be kept alive by the program until the user says otherwise.

Currently I've managed to make it work by setting a "every minute detached job" and since the script I'm running only quits on errors, it works quite well, rerunning it on the next minute if it happens to fail, but it creates quite a lot of noise on the upcoming events list and just trashes my Success Rate, since a job fails to run every single minute.

**Comment by jhuckaby** [comment]
Use the [Chain Reaction](https://github.com/jhuckaby/Cronicle#chain-reaction) system, and have your event chain to **itself**, on both success on error:

<img width="660" alt="screenshot 2019-02-03 11 10 45" src="https://user-images.githubusercontent.com/700765/52181210-6a1e4800-27a4-11e9-8a18-22c7c7082b1a.png">

This should effectively keep it running forever, after you start it once by hand.  Recommend you set the schedule to "On Demand" so the scheduler doesn't keep trying to start more of them.
