### ISSUE TITLE
No progress update shown on the job status page while job is running.

### ISSUE THREAD

**Issue by M1k13** [jhuckaby/Cronicle#151]
## Summary

No progress update shown on the job status page while job is running.

## Steps to reproduce the problem

I'm using the schell-script plugin and my text is :

#!/bin/sh

#Enter your shell script code here

ping -c 2 127.0.0.1
sleep 4 || exit 1
echo "25%"

ping -c 2 127.0.0.1
sleep 4 || exit 1
echo "50%"

ping -c 2 127.0.0.1
sleep 4 || exit 1
echo "75%"

ping -c 2 127.0.0.1
sleep 4 || exit 1

## Your Setup

I'm using multi-server setup with 2 slaves and 1 master. And I'm using couchbase on the master.

### Operating system and version?

RHEL 7

### Node.js version?

Node v11.0

### Cronicle software version?

Cronicle Version 0.8.28

I dont see any progress % changing on the "home tab" or the "job details tab".
I used the echo "number%" example like in the readme but while the task runs it doesn't show the progress %  same for the perforemance matrix .

Log of the job:

#Job ID: jjsg7u54y1t
#Event Title: sysstat
#Hostname: {FQDN}
#Date/Time: 2019/02/22 15:34:05 (GMT+0)

PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.025 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.026 ms
--- 127.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.025/0.025/0.026/0.005 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.014 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.017 ms
--- 127.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.014/0.015/0.017/0.004 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.022 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.025 ms
--- 127.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.022/0.023/0.025/0.005 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.013 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.077 ms
--- 127.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.013/0.045/0.077/0.032 ms

#Job completed successfully at 2019/02/22 15:35:00 (GMT+0).
#End of log.

**Comment by jhuckaby** [comment]
Guessing from the timestamps in your log that you are using [Detached Mode](https://github.com/jhuckaby/Cronicle#detached-mode)?  Since detached scripts run as completely independent processes, there is no pipe connecting them for real-time progress updates.  As such, they only send an update every minute, via a special temp file.

From the docs, emphasis added:

> Please use this mode with caution, and only when truly needed, as there are downsides. First of all, since the process runs detached and standalone, **there are no real-time updates**. Meaning, the progress bar and time remaining displays are delayed by up to a minute. Also, when your job completes, there is a delay of up to a minute before Cronicle realizes and marks the job as complete.

Hope this helps.

**Comment by M1k13** [comment]
Thanks a lot!
