### ISSUE TITLE
On OSX is Cronicle is stuck at "Waiting for master server..."

### ISSUE THREAD

**Issue by Mossop** [jhuckaby/Cronicle#152]
## Summary

I installed Cronicle as a single server and starting it from the command line appears to work, but accessing the site just shows "Waiting for master server..."

## Steps to reproduce the problem

    mkdir -p /usr/local/cronicle
    cd /usr/local/cronicle
    curl -L https://github.com/jhuckaby/Cronicle/archive/v0.8.28.tar.gz | tar zxvf - --strip-components 1
    npm install
    node bin/build.js dist
    /usr/local/cronicle/bin/cronicle.sh start

### Operating system and version?

OSX 10.14.3

### Node.js version?

11.9.0

### Cronicle software version?

0.8.28

### Are you using a multi-server setup, or just a single server?

Single serer

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

### Can you reproduce the crash consistently?

Yes

## Log Excerpts

Logs don't appear to show any kinds of errors.

**Comment by jhuckaby** [comment]
Your steps to reproduce seem to omit initializing storage:

https://github.com/jhuckaby/Cronicle#setup

> With that out of the way, run the following script to initialize the storage system. You only need to do this once, and only on the master server. Do not run this on any slave servers:

```
/opt/cronicle/bin/control.sh setup
```

> Among other things, this creates an administrator user account you can use to login right away. The username is `admin` and the password is `admin`. It is recommended you change the password as soon as possible, for security purposes (or just create your own administrator account and delete admin).

Also, please note that it takes 60 seconds for it to decide on a master server when launched as a daemon.

Good luck!

**Comment by Mossop** [comment]
Oops, you are quite right, sorry for wasting your time.

**Comment by jhuckaby** [comment]
No worries!
