### ISSUE TITLE
Backup Cronicle with cronicle job?!

### ISSUE THREAD

**Issue by SwapFaceL** [jhuckaby/Cronicle#160]
Hi,

first I really do appreciate the work, it is a very nice interface and a smooth application.

I've just installed cronicle and before I am entering too much data into it, I wanted to know if there is any recommendations how to backup the cronicle configuration and jobs?

My first attempt was to copy the whole /opt/cronicle directory. Therefore I needed to stop cronicle, copy it and restart cronicle. Worked fine.
Then I thought it would be nice to use a cronicle job to backup. The problem is, that cronicle reports a failure for this job (probably because it gets stopped) although the backup is fine.

How are you backing up the inserted jobs and configuration?! Any specific path I might copy without stopping cronicle?

Thanks in advance.

**Comment by jhuckaby** [comment]
I assume you are using the [Filesystem](https://github.com/jhuckaby/Cronicle#filesystem) Plugin and want to backup **all** of the data on disk, including completed job history?  If so, then there is really no "safe" way to do this, as you could theoretically interrupt an operation in progress, like appending to a list, which requires multiple writes.  The recommended solution is to use a replicated storage system like NFS, or use the [Couchbase](https://github.com/jhuckaby/Cronicle#couchbase) or [AWS S3](https://github.com/jhuckaby/Cronicle#amazon-s3) Plugins.

However, if you just want to backup the **critical** data like your Event Schedule, Plugins, Groups, Users, etc. you can probably do this safely while Cronicle is running, as it is probably less likely someone will be modifying these records when your backup runs.  Instructions are here: https://github.com/jhuckaby/Cronicle#data-import-and-export

If you want daily backups of the data which auto-expire after a year, a simple shell script can do it for ya:

```sh
#!/bin/bash
DATE_STAMP=`date "+%Y-%m-%d"`
BACKUP_DIR="/backup/cronicle/data"
BACKUP_FILE="$BACKUP_DIR/backup-$DATE_STAMP.txt"

mkdir -p $BACKUP_DIR
/opt/cronicle/bin/control.sh export $BACKUP_FILE --verbose
find $BACKUP_DIR -mtime +365 -type f -exec rm -v {} \;
```

Good luck.

**Comment by DmitryAdam** [comment]
Hi, I've completely download the backup file, but how to import it to another cronicle server

**Comment by jhuckaby** [comment]
Sorry, the docs have moved since 2019.  New link:

https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#data-import-and-export

To import data back into the system after exporting, first make sure Cronicle is stopped on all servers in the cluster, and then run this command on the master server:

```sh
/opt/cronicle/bin/control.sh import /path/to/cronicle-data-backup.txt
```

Then start Cronicle again.
