### ISSUE TITLE
Laptop use?

### ISSUE THREAD

**Issue by Mossop** [jhuckaby/Cronicle#161]
## Summary

I'm not sure if what I'm doing is just unsupported, broken, or I'm just doing it wrong. I've liked running Cronicle on my home server but I have some regular tasks I'd like to monitor on some of my laptops as well so I've tried installing and using it on mine. I've got it mostly working but the issue I'm hitting is that things fail in various ways as I move from wifi network to wifi network. This means the LAN IP address and sometimes the hostname change over time and this seems to confuse Cronicle.

For example if I'm on a different network to when I last started Cronicle live logs don't work, they look to be trying to communicate based on the IP address the laptop used to have. Restarting Cronicle also fails, just ends up forever waiting for the master server and I have to manually edit the hostname and IP address in global/servers/0 of storage to match the new values.

I never want this laptop to be as slave server, never really want it to communicate with any other Cronicle instances. Ideally there would be a way to just have it always use localhost and 127.0.0.1 whenever it needs to talk to the Cronicle service.

## Steps to reproduce the problem

1. Install Cronicle and get it all working.
2. Move to a network so the hostname and IP address of the computer changes.
3. Try restarting Cronicle.

### Operating system and version?

OSX 10.14.3 (18D109)

### Node.js version?

11.9.0

### Cronicle software version?

0.8.28

### Are you using a multi-server setup, or just a single server?
Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem

### Can you reproduce the crash consistently?
Yes

**Comment by jhuckaby** [comment]
I do apologize, but Cronicle is really designed from the ground up to identify servers by their IP addresses.  So running a cluster of multiple servers really requires static IPs that do not ever change.  I now regret this design decision, but it was made so very long ago that it is now so deeply rooted in the codebase.  It would be extremely difficult to change at this point.

> I never want this laptop to be as slave server, never really want it to communicate with any other Cronicle instances. Ideally there would be a way to just have it always use localhost and 127.0.0.1 whenever it needs to talk to the Cronicle service.

This is totally possible.  The exception to the above rule is running a single solo master server by itself.  You can "force" a single standalone server to become master by adding `--master` to the `debug.sh` script when running in debug mode.  See: https://github.com/jhuckaby/Cronicle#starting-in-debug-mode

When I test Cronicle on multiple servers at home, I setup DHCP IP reservations in my router so my laptop and other machines always get the same IP address.

Hope this helps.

**Comment by Mossop** [comment]
Alright, thanks for the help.

**Comment by Mossop** [comment]
Sounds like this isn't a case you want to support (which is fine!) but in case you're interested I got things working for me with this change: https://github.com/Mossop/Cronicle/commit/bba9e6841466a2d279521bc057e59150de33ab2e.

It's a bit of a hack because I didn't want to go into forking pixl-server too, but it'll do for me for now!
