### ISSUE TITLE
How to auto start cronicle after server reboot

### ISSUE THREAD

**Issue by pratiksoni9** [jhuckaby/Cronicle#163]
## Summary
After Server reboot cronicle will stop working, we need to manually start by using command line, is their any cron job structure, that we can add into server cron job ?
So after server successfully up then cron job will trigger and cronicle will start ?

### Operating system and version?
Centos 7

### Cronicle software version?
Version 0.8.28

### Are you using a multi-server setup, or just a single server?
No

**Comment by jhuckaby** [comment]
Instructions are in the docs here: https://github.com/jhuckaby/Cronicle#server-startup

**Comment by pratiksoni9** [comment]
Hi

It's for node.js restart, we need auto cronicle start after successfully
reboot.
Is it possible to do via server side cron job ?

**Comment by jhuckaby** [comment]
> It's for node.js restart

I don't understand what you mean.

> we need auto cronicle start after successfully
reboot.

See my reply above.  This is explained in the docs, which I linked to.

> Is it possible to do via server side cron job ?

Uh, sure, I guess so.  See the crond documentation for your OS.  Most Linux crond flavors support a `@reboot` macro to run a command on boot.

**Comment by Austinddan** [comment]
Sorry for commenting on a closed issue, didn’t want to open a new issue if it’s not necessary. Is there a solution for this that works on OSX?

**Comment by jhuckaby** [comment]
Sure @Austinddan!  For OS X, you need to create this file as root (or use sudo) on your boot drive:

```
/Library/LaunchAgents/com.node.cronicle.plist
```

The contents of the file should be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.node.cronicle</string>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/cronicle/bin/control.sh</string>
		<string>start</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<false/>
</dict>
</plist>
```

That will start Cronicle as root on macOS reboot.

Note that this will be **much** easier in Orchestra (Cronicle 2.0) which will have a simple command-line option for enabling boot start on any OS.

**Comment by Austinddan** [comment]
Perfect, thanks!

**Comment by Austinddan** [comment]
> Sure @Austinddan! For OS X, you need to create this file as root (or use sudo) on your boot drive:
> 
> ```
> /Library/LaunchAgents/com.node.cronicle.plist
> ```
> 
> The contents of the file should be:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>Label</key>
> 	<string>com.node.cronicle</string>
> 	<key>ProgramArguments</key>
> 	<array>
> 		<string>/opt/cronicle/bin/control.sh</string>
> 		<string>start</string>
> 	</array>
> 	<key>RunAtLoad</key>
> 	<true/>
> 	<key>KeepAlive</key>
> 	<false/>
> </dict>
> </plist>
> ```
> 
> That will start Cronicle as root on macOS reboot.
> 
> Note that this will be **much** easier in Orchestra (Cronicle 2.0) which will have a simple command-line option for enabling boot start on any OS.

I can wait for Orchestra if thats the only option. It seems the boot drive is not writable from Catalina on, not even in recovery mode. Is there another way?

**Comment by jhuckaby** [comment]
@Austinddan I did not know that.  Are you saying you can't write into the `/opt` directory on macOS?  Even as root?  That is very strange.  Well, Cronicle can live anywhere on your filesystem, just follow the manual installation instructions here: https://github.com/jhuckaby/Cronicle#installation

For example, on macOS you can create a fake user home dir in `/Users/Shared/` and install Cronicle in there.  **Just make sure you do all this as root (sudo).**

```
sudo bash
mkdir -p /Users/Shared/cronicle
cd /Users/Shared/cronicle
curl -L https://github.com/jhuckaby/Cronicle/archive/master.tar.gz | tar zxvf - --strip-components 1
npm install
node bin/build.js dist
```

Good luck!

**Comment by sanme98** [comment]
> Instructions are in the docs here: https://github.com/jhuckaby/Cronicle#server-startup

For latest version on this moment, the doc had moved to here: https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#server-startup

**Comment by jhuckaby** [comment]
Apologies for moving the docs.  I couldn't figure out a way to preserve all the old links when they were split apart.
