### ISSUE TITLE
UI: this.transports.shift is not a function

### ISSUE THREAD

**Issue by LordMike** [jhuckaby/Cronicle#168]
## Summary

```
TypeError: this.transports.shift is not a function -- universalModuleDefinition:2
	open (index):2
	n (index):2
	n (index):1
	connect (index):1
	n (index):1
	n (index):1
	n (index):1
	socketConnect _combo.js:3365
	init _combo.js:3201
	<anonymous> _combo.js:3071
l2jQuery	l
	c
```

## Steps to reproduce the problem

In theory, running `docker run --name cronicle --hostname localhost -p 3012:3012 intelliops/cronicle:latest` and browsing `http://localhost:3012` should do the trick.

Note: I've just run this locally, and I can reproduce the issue there.

## Your Setup

* Run in docker
* Using https://hub.docker.com/r/intelliops/cronicle
* No proxies or other sorts

### Operating system and version?

* Host is a Ubuntu server

### Node.js version?

Unknown

### Cronicle software version?

`Version 0.8.28`

### Are you using a multi-server setup, or just a single server?

Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

FS

### Can you reproduce the crash consistently?

Yes. I've tried clearing caches and running in FF with "disable cache" for networking.

## Log Excerpts

The docker log doesn't show anything out of the ordinary. Web requests are made and responded to, and it seems like jobs are running. This seems like a 100% UI issue.

**Comment by LordMike** [comment]
Note: I've reported this to [belsander/docker-cronicle](https://github.com/belsander/docker-cronicle/issues/17) as well, as this seems a bit more like an image specific issue right now.

**Comment by LordMike** [comment]
Prob. an issue with the image.

**Comment by wackazong** [comment]
This is because the JSON property socket_io_transports is set to a string and not to a JSON array. You need a different method to set it, I use jq.
