### ISSUE TITLE
Croncile master binds to the second network interface

### ISSUE THREAD

**Issue by vshalchian** [jhuckaby/Cronicle#169]
## Summary
Croncile master binds to the second network interface, on some systems I do see it starts on the first network interface. To me it seems random

## Your Setup
3 node setup running in Docker swarm
My config.json:
####################
{
        "base_app_url": "http://localhost:3012",
        "email_from": "admin@localhost",
        "smtp_hostname": "localhost",
        "smtp_port": 25,
        "secret_key": "256f94608637a59b3dc813775c3bb612",

        "log_dir": "logs",
        "log_filename": "[component].log",
        "log_columns": ["hires_epoch", "date", "hostname", "pid", "component", "category", "code", "msg", "data"],
        "log_archive_path": "logs/archives/[yyyy]/[mm]/[dd]/[filename]-[yyyy]-[mm]-[dd].log.gz",
        "log_crashes": true,
        "copy_job_logs_to": "",
        "queue_dir": "queue",
        "pid_file": "/var/run/cronicled.pid",
        "debug_level": 9,
        "maintenance": "04:00",
        "list_row_max": 10000,
        "job_data_expire_days": 180,
        "child_kill_timeout": 10,
        "dead_job_timeout": 120,
        "master_ping_freq": 20,
        "master_ping_timeout": 60,
        "udp_broadcast_port": 3014,
        "scheduler_startup_grace": 10,
        "universal_web_hook": "",
        "track_manual_jobs": false,

        "server_comm_use_hostnames": true,
        "web_direct_connect": false,
        "web_socket_use_hostnames": true,

        "job_memory_max": 1073741824,
        "job_memory_sustain": 0,
        "job_cpu_max": 0,
        "job_cpu_sustain": 0,
        "job_log_max_size": 0,
        "job_env": {},

        "web_hook_text_templates": {
                "job_start": "Job started on [hostname]: [event_title] [job_details_url]",
                "job_complete": "Job completed successfully on [hostname]: [event_title] [job_details_url]",
                "job_failure": "Job failed on [hostname]: [event_title]: Error [code]: [description] [job_details_url]",
                "job_launch_failure": "Failed to launch scheduled event: [event_title]: [description] [edit_event_url]"
        },

        "client": {
                "name": "Cronicle",
                "debug": 1,
                "default_password_type": "password",
                "privilege_list": [
                        { "id": "admin", "title": "Administrator" },
                        { "id": "create_events", "title": "Create Events" },
                        { "id": "edit_events", "title": "Edit Events" },
                        { "id": "delete_events", "title": "Delete Events" },
                        { "id": "run_events", "title": "Run Events" },
                        { "id": "abort_events", "title": "Abort Events" },
                        { "id": "state_update", "title": "Toggle Scheduler" }
                ],
                "new_event_template": {
                        "enabled": 1,
                        "params": {},
                        "timing": { "minutes": [0] },
                        "max_children": 1,
                        "timeout": 3600,
                        "catch_up": 0,
                        "queue_max": 1000
                }
        },

  "Storage": {
    "engine": "S3",
    "AWS": {
      "endpoint": "http://minio-lb:9000",
      "accessKeyId": "admin",
      "secretAccessKey": "password",
      "s3ForcePathStyle": true,
      "correctClockSkew": true,
      "maxRetries": 5,
      "httpOptions": {
        "connectTimeout": 5000,
        "timeout": 5000
      }
    },
    "S3": {
      "fileExtensions": true,
      "params": {
        "Bucket": "cronicle"
      }
    }
  },

        "WebServer": {
                "http_port": 3012,
                "http_htdocs_dir": "htdocs",
                "http_max_upload_size": 104857600,
                "http_static_ttl": 3600,
                "http_static_index": "index.html",
                "http_server_signature": "Cronicle 1.0",
                "http_gzip_text": true,
                "http_timeout": 30,
                "http_regex_json": "(text|javascript|js|json)",
                "http_response_headers": {
                        "Access-Control-Allow-Origin": "*"
                },

                "https": false,
                "https_port": 3013,
                "https_cert_file": "conf/ssl.crt",
                "https_key_file": "conf/ssl.key",
                "https_force": false,
                "https_timeout": 30,
                "https_header_detect": {
                        "Front-End-Https": "^on$",
                        "X-Url-Scheme": "^https$",
                        "X-Forwarded-Protocol": "^https$",
                        "X-Forwarded-Proto": "^https$",
                        "X-Forwarded-Ssl": "^on$"
                }
        },

        "User": {
                "session_expire_days": 30,
                "max_failed_logins_per_hour": 5,
                "max_forgot_passwords_per_hour": 3,
                "free_accounts": false,
                "sort_global_users": true,
                "use_bcrypt": true,

                "email_templates": {
                        "welcome_new_user": "conf/emails/welcome_new_user.txt",
                        "changed_password": "conf/emails/changed_password.txt",
                        "recover_password": "conf/emails/recover_password.txt"
                },

                "default_privileges": {
                        "admin": 0,
                        "create_events": 1,
                        "edit_events": 1,
                        "delete_events": 1,
                        "run_events": 0,
                        "abort_events": 0,
                        "state_update": 0
                }
        }

}

###################

My network interfaces:
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.0.0.133  netmask 255.255.255.0  broadcast 10.0.0.255
        ether 02:42:0a:00:00:85  txqueuelen 0  (Ethernet)
        RX packets 179  bytes 29127 (28.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 149  bytes 27214 (26.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.255.0.98  netmask 255.255.0.0  broadcast 10.255.255.255
        ether 02:42:0a:ff:00:62  txqueuelen 0  (Ethernet)
        RX packets 661  bytes 37370 (36.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 652  bytes 168299 (164.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.7  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:ac:12:00:07  txqueuelen 0  (Ethernet)
        RX packets 11  bytes 823 (823.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 167 (167.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 62  bytes 4134 (4.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 62  bytes 4134 (4.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
### Operating system and version

centos7.5.1804

### Node.js version?
10.15.1

### Cronicle software version?
0.8.28

### Are you using a multi-server setup, or just a single server?
multi-server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
S3

### Can you reproduce the crash consistently?
Yes

## Log Excerpts
Here is my Cronicle.log
I expect that 10.0.0.133 is picked up as the Server IP but the second network interface gets picked up

`[1553738451.166][2019-03-27 22:00:51][master01][29][Cronicle][debug][1][Cronicle v0.8.28 Starting Up][{"pid":29,"ppid":1,"node":"v10.15.1","arch":"x64","platform":"linux","argv":["/usr/bin/node","/opt/cronicle/lib/main.js"],"execArgv":[]}]
[1553738451.175][2019-03-27 22:00:51][master01][29][Cronicle][debug][9][Writing PID File: /var/run/cronicled.pid: 29][]
[1553738451.176][2019-03-27 22:00:51][master01][29][Cronicle][debug][9][Confirmed PID File contents: /var/run/cronicled.pid: 29][]
[1553738451.177][2019-03-27 22:00:51][master01][29][Cronicle][debug][2][Server IP: 10.255.0.98, Daemon PID: 29][]
[1553738451.177][2019-03-27 22:00:51][master01][29][Cronicle][debug][3][Starting component: Storage][]
[1553738451.4][2019-03-27 22:00:51][master01][29][Cronicle][debug][3][Starting component: WebServer][]
[1553738451.41][2019-03-27 22:00:51][master01][29][Cronicle][debug][3][Starting component: API][]
[1553738451.412][2019-03-27 22:00:51][master01][29][Cronicle][debug][3][Starting component: User][]
[1553738451.412][2019-03-27 22:00:51][master01][29][Cronicle][debug][3][Starting component: Cronicle][]
[1553738451.413][2019-03-27 22:00:51][master01][29][Cronicle][debug][3][Cronicle engine starting up][]
[1553738451.42][2019-03-27 22:00:51][master01][29][Cronicle][debug][4][Using broadcast IP: 10.255.255.255][]
[1553738451.42][2019-03-27 22:00:51][master01][29][Cronicle][debug][4][Starting UDP server on port: 3014][]
[1553738451.586][2019-03-27 22:00:51][master01][29][Cronicle][debug][4][Server is eligible to become master (Master Group)][]
[1553738451.586][2019-03-27 22:00:51][master01][29][Cronicle][debug][2][Startup complete, entering main loop][]
[1553738453.352][2019-03-27 22:00:53][master01][29][Cronicle][debug][5][New socket.io client connected: 9qRibcIoAIknPLpcAAAA (IP: ::ffff:10.255.0.3)][]
[1553738453.371][2019-03-27 22:00:53][master01][29][Cronicle][debug][4][Socket client 9qRibcIoAIknPLpcAAAA has authenticated via user session (IP: ::ffff:10.255.0.3)][]
[1553738454.807][2019-03-27 22:00:54][master01][29][Cronicle][debug][5][New socket.io client connected: tyhjg53SNf-v3eAYAAAB (IP: ::ffff:10.255.0.2)][]
[1553738454.827][2019-03-27 22:00:54][master01][29][Cronicle][debug][4][Socket client tyhjg53SNf-v3eAYAAAB has authenticated via user session (IP: ::ffff:10.255.0.2)][]
[1553738456.307][2019-03-27 22:00:56][master01][29][Cronicle][debug][5][New socket.io client connected: QiSG5NU0iOthjSYGAAAC (IP: ::ffff:10.255.0.2)][]
[1553738456.308][2019-03-27 22:00:56][master01][29][Cronicle][debug][5][Socket.io client disconnected: QiSG5NU0iOthjSYGAAAC (IP: ::ffff:10.255.0.2)][]
[1553738458.294][2019-03-27 22:00:58][master01][29][Cronicle][debug][5][Socket.io client disconnected: 9qRibcIoAIknPLpcAAAA (IP: ::ffff:10.255.0.3)][]
[1553738511.679][2019-03-27 22:01:51][master01][29][Cronicle][debug][3][No master ping received within 60 seconds, choosing new master][]
[1553738511.747][2019-03-27 22:01:51][master01][29][Cronicle][debug][5][We are the top candidate for master][]
[1553738511.747][2019-03-27 22:01:51][master01][29][Cronicle][debug][3][We are becoming the master server][]
[1553738511.757][2019-03-27 22:01:51][master01][29][Cronicle][debug][4][Looking for leftover job JSON files: logs/jobs/*.json][]
[1553738511.767][2019-03-27 22:01:51][master01][29][Cronicle][debug][9][Job recovery complete][]
[1553738511.767][2019-03-27 22:01:51][master01][29][Cronicle][debug][4][Looking for leftover job logs: logs/jobs/*.log][]
[1553738511.768][2019-03-27 22:01:51][master01][29][Cronicle][debug][9][Log recovery complete][]
[1553738580.791][2019-03-27 22:03:00][master01][29][Cronicle][debug][4][Scheduler Minute Tick: Advancing time up to: 2019/03/27 22:03:00][]`

**Comment by jhuckaby** [comment]
You'll have to forgive me as I don't use Docker, so I don't know anything about how it handles network interfaces.  But I can tell you this much.  By default, Cronicle doesn't specify any network interface to bind to, and instead Node.js just binds to **all of them**, including the localhost loopback adapter.  This is the default behavior of the Node.js [net](https://nodejs.org/api/net.html#net_server_listen) module.  Quoting their docs:

> If `host` is omitted, the server will accept connections on the [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (`::`) when IPv6 is available, or the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (`0.0.0.0`) otherwise.

> In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).

Now, if you want to specify an exact interface to bind to, add a [http_bind_address](https://github.com/jhuckaby/pixl-server-web#http_bind_address) configuration property into the `WebServer` object, set it to the IP address of the interface to bind to, and restart Cronicle.

Hope this helps!  Good luck!

**Comment by vshalchian** [comment]
Thanks for getting back to. 
OK let me ask you something else then that might be useful for anybody who would like to use this product inside docker.
What happens in the docker is that Cronicle runs inside a container with a completely different IP address from the host. However many tools handle this case by letting the user specify an advertise-addr
i.e the IP address of the host operating system (not the  IP address of the docker container)
 Something like the broadcast_ip we have here. I tried to changing  both "broadcast_ip" and "http_bind_address" to the IP of the host computer ,
        "broadcast_ip": "192.168.56.32",
        "http_bind_address": "192.168.56.32",

but still in the GUI under Admin->Server I see the real IP address of the docker container which is a private network. and it causes other hosts cannot will not be able to communicate my node.

Dkron has a --advertise-addr that works perfectly fine (https://dkron.io/cli/dkron_agent/)
I also use Vault and Consul from Hashicorp products and they also handle this part well. 

Is it possible to have this feature ? like the code never should rely on the output of ifconfig, instead it needs to treat advertise-addr or broadcast_ip as the IP.

**Comment by vshalchian** [comment]
Thanks for getting back to me. 
I get your point about the service listening to all ports by default and it is true. I tested on a regular machine with two network interfaces and it is fine.

But in my docker swarm setup I still have that problem.

My concern in this line of log:
[1553738451.177][2019-03-27 22:00:51][master01][29][Cronicle][debug][2][Server IP: 10.255.0.98, Daemon PID: 29][]
Are you suggesting that if I set  http_bind_address to the IP of a different network interface, I will see a different IP shows up in that log ?

**Comment by jhuckaby** [comment]
I am sorry, I simply don't know anything about Docker, so I don't know how it handles networking.  I do apologize, but I don't know how to help.

The "Server IP" address you see in the debug log is simply the first non-internal IPv4 interface found in the [os.networkInterfaces()](https://nodejs.org/api/os.html#os_os_networkinterfaces) output.  The code is [here](https://github.com/jhuckaby/pixl-config/blob/master/config.js#L230-L249) if you are interested.

Cronicle master will attempt to communicate to all of its backup and slave servers using their IP addresses *unless* you set the [server_comm_use_hostnames](https://github.com/jhuckaby/Cronicle#server_comm_use_hostnames) configuration property.  Then they will use hostnames instead.

**Comment by vshalchian** [comment]
No worries, I will check out the code. Thank you.

**Comment by piotrkochan** [comment]
@jhuckaby basically I have very similar problem, I'm adding eg 192.168.1.10 slave but master receives different ip address from the slave and it is not accessible
