### ISSUE TITLE
How to export plugin in cronicle?

### ISSUE THREAD

**Issue by hiba007** [jhuckaby/Cronicle#170]
## Summary

I am trying to export plugin but I can't find any solution

## Steps to reproduce the problem

Can't find solution to export plugin

## Your Setup

localhost

### Operating system and version?

Ubuntu 18.04

### Node.js version?

v8.10.0

### Cronicle software version?

Version 0.8.28

### Are you using a multi-server setup, or just a single server?

Single Server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

back-end storage

### Can you reproduce the crash consistently?
No

**Comment by jhuckaby** [comment]
I'm sorry, but I don't understand what you are asking.  A "Plugin" in Cronicle simply refers to a file on disk.  It doesn't include the file -- it's just an internal reference, i.e. a filesystem path, and some other metadata like a CWD and UID.  Internally a Plugin looks like this:

```js
{
	"id": "shellplug",
	"title": "Shell Script",
	"enabled": 1,
	"command": "bin/shell-plugin.js",
	"params": [ ... ],
	"username": "admin",
	"modified": 1534109788,
	"created": 1442197063,
	"cwd": "",
	"uid": ""
}
```

Is this the Plugin metadata you want to "export"?  If so, see the [Data Import and Export](https://github.com/jhuckaby/Cronicle#data-import-and-export) documentation.  The export contains all the Plugin metadata.

Good luck.

**Comment by MiraMaX166** [comment]
Greetings. I’m also very interested in the possibility of transferring plugins, but I haven’t figured out how to do this yet. The documentation link is no longer valid. Can I provide a link to current information? Thank you.

**Comment by jhuckaby** [comment]
https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#data-import-and-export

**Comment by MiraMaX166** [comment]
Thank you very much, I'll look into it.
