### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Wrong number of arguments to doError

### ISSUE THREAD

**Issue by zakalibit** [jhuckaby/Cronicle#173]
Cronicle Version 0.8.28
Couchbase Community Edition 6.0.0 build 1693
CentOS Linux release 7.5.1804 (Core)

> AssertionError [ERR_ASSERTION]: Wrong number of arguments to doError
    at constructor.doError (/opt/cronicle/node_modules/pixl-server-user/user.js:1305:3)
    at /opt/cronicle/node_modules/pixl-server-user/user.js:308:17
    at /opt/cronicle/node_modules/pixl-server-user/user.js:1281:5
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:359:4
    at /opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:200:5

**Comment by zakalibit** [comment]
Please review and merge the following fix
https://github.com/jhuckaby/pixl-server-user/pull/2

**Comment by jhuckaby** [comment]
Fixed via your PR, thank you @zakalibit!
