### ISSUE TITLE
Stuck "Waiting for master server..." forever

### ISSUE THREAD

**Issue by jetacpp** [jhuckaby/Cronicle#178]
## Summary

Cronicle got stuck "Waiting for master server..." on new installation. I waited more than 60s, like a couple of minutes and more. Why does it not simply work and please tell me if there is more information I should provide.

## Steps to reproduce the problem
1. Install
2. sudo /opt/cronicle/bin/control.sh start
3. Wait few minutes
4. goto localhost:3012

## Your Setup

Single server setup, default config.json, nothing changed

### Operating system and version?

Ubuntu 18.04

### Node.js version?

8.10.0

### Are you using a multi-server setup, or just a single server?
Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?
File system
## Log Excerpts

> [1557379196.195][2019-05-08 22:19:56][dell][18958][Cronicle][debug][3][Cronicle engine starting up][]
> [1557379196.199][2019-05-08 22:19:56][dell][18958][Cronicle][debug][4][Using broadcast IP: 192.168.1.255][]
> [1557379196.199][2019-05-08 22:19:56][dell][18958][Cronicle][debug][4][Starting UDP server on port: 3014][]
> [1557379196.204][2019-05-08 22:19:56][dell][18958][Cronicle][debug][4][Server not found in cluster -- waiting for a master server to contact us][]
> [1557379196.205][2019-05-08 22:19:56][dell][18958][Cronicle][debug][2][Startup complete, entering main loop][]

```
dev@dell:/opt/cronicle/logs$ /opt/cronicle/bin/storage-cli.js get global/servers/0
/opt/cronicle/bin/storage-cli.js:213
				if (err) throw err;
				         ^

Error: Failed to fetch key: global/servers/0: File not found
```
```
dev@dell:/opt/cronicle/logs$ node -e 'console.log(require("os").hostname().toLowerCase());'
dell
```
```
/opt/cronicle/bin/storage-cli.js edit global/servers/0
{}
```

**Comment by gamefundas** [comment]
@jetacpp how did you resolve this. I am getting the same error and cant figure out at all, whats causing this.

**Comment by muety** [comment]
Same issue here.

**Comment by duanmq1994** [comment]
@gamefundas @muety Try run the command `/opt/cronicle/bin/storage-cli.js install` first. This error occurs because the master haven't been installed yet.
