### ISSUE TITLE
send e-mail ,Error: Connection timeout

### ISSUE THREAD

**Issue by MingqingLi** [jhuckaby/Cronicle#18]
Failed to send e-mail for job: jj1c2352702: liuxx@xx: Error: Connection timeout

confing:

 "base_app_url": "http://192.168.200.149:3012",
        "email_from": "xxxx@xxx",
        "smtp_hostname": "smtpcom.263xmail.com",
        "smtp_port": 25,
         "mail_options": {
         "host": "smtpcom.263xmail.com",
         "port": 25,
         "secure": "flase",
         "auth": {
         "user": "xxxx@xxx",
         "pass": "xxxxx"
      }

**Comment by jhuckaby** [comment]
You have a typo error here:

```
"secure": "flase",
```

"flase" is not a word, but also, this needs to be a Boolean (`true` or `false`), **without quotes**.  Try:

```
"secure": false
```

**Comment by MingqingLi** [comment]
thank you so much。I'm a lower
