### ISSUE TITLE
Is there a node SDK to gain easy access to the api?

### ISSUE THREAD

**Issue by regevbr** [jhuckaby/Cronicle#184]
It would be awesome if there was a TypeScript SDK we could use to communicate with the Cronicle api...

**Comment by jhuckaby** [comment]
I'm sorry, but I really don't know anything about TypeScript.  Cronicle is a 100% pure JavaScript application, so I don't know what a "TypeScript SDK" would do in this case.  But the Cronicle API is just standard HTTP REST with JSON, and it is fully documented here:

https://github.com/jhuckaby/Cronicle#api-reference

I hope this helps.

**Comment by regevbr** [comment]
Hi,

When I say SDK I mean something like [aws-sdk](https://www.npmjs.com/package/aws-sdk) - yes, you can access AWS using REST api, but why let everyone recreate logic to handle that, when you can simply require a library and call methods on them without getting into the internals of the api...

If you don't know TypeScript I highly recommend to check it out - it is a super set of Javascript that lets you write typed JS code for static type safety, while it compiles to pure JS, so yuo can use it in any node environment.  
If we continue our aws-sdk example you can find [here](https://github.com/aws/aws-sdk-js/blob/master/clients/s3.d.ts) they typings for the S3 api

**Comment by regevbr** [comment]
By the way - I have stopped writing pure Javascript about a year ago and I only use TypeScript - it is awesome and a somewhat industry standard now

**Comment by regevbr** [comment]
@jhuckaby I have created https://github.com/PruvoNet/cronicle-client (still unpublished and WIP)
Any comments are more than welcome

**Comment by jhuckaby** [comment]
@regevbr Hey, great work!  Of course, you'll have to forgive me, but this is all in TypeScript so I have no idea what I am looking at, or how to read the code.  Somehow I've been able to avoid learning anything about TypeScript despite it taking over the entire world.  But at first glance of your docs and examples it looks very easy to use, and the "types" make it easy to understand what goes where, instead of a freeform JSON blob.  Nice job!

**Comment by regevbr** [comment]
@jhuckaby haha, as I said you should really get started on it!  

Once I will publish it (I still need to add unit tests), you will be able to see the pure JS code it produces and the typings files, and then I would recommend you to play around with it a bit to get familiar.  

This library is using kind of advanced TypeScript techniques so maybe it is not the best to start with, but I'm sure you will get the hang of it pretty fast.  

I am also thinking about investing in great docs like I did in https://squiss-ts.pruvo.com but this will take a couple of hours to produce.  

I would love it if, once I'm done, you will link to my library in your main docs... Is that something you can consider?  

p.s  
WIll the api change in v1?

**Comment by regevbr** [comment]
@jhuckaby just released final beta version v0.1.0 of the client so you can check it out if you want.

**Comment by jhuckaby** [comment]
Thanks, I'll check it out when I have some time!

> I would love it if, once I'm done, you will link to my library in your main docs... Is that something you can consider?

I would be happy to list it on the official Cronicle [Community Work](https://github.com/jhuckaby/Cronicle/wiki/Community-Work) Wiki, but linking to it from the main doc is asking a lot.

> WIll the api change in v1?

Well, probably not, but I can't make any promises.  It is a major redesign, but if I am going to break any of the APIs, I will version them (e.g. `/api/app/get_schedule/v2`), so your client library will continue to work with the v1 (current) API.

**Comment by regevbr** [comment]
> I would be happy to list it on the official Cronicle [Community Work](https://github.com/jhuckaby/Cronicle/wiki/Community-Work) Wiki, but linking to it from the main doc is asking a lot.

Thanks sounds good!
 
> Well, probably not, but I can't make any promises. It is a major redesign, but if I am going to break any of the APIs, I will version them (e.g. `/api/app/get_schedule/v2`), so your client library will continue to work with the v1 (current) API.

Great!

**Comment by regevbr** [comment]
@jhuckaby can you please add my lib to https://github.com/jhuckaby/Cronicle/wiki/Community-Work and close the issue?

**Comment by jhuckaby** [comment]
Done!  Thank you so much!  The library looks great, and your docs are excellent.  I'll test it out when I have some time (sorry for lack of feedback, as I've been swamped).

Updated Wiki: https://github.com/jhuckaby/Cronicle/wiki/Community-Work
