### ISSUE TITLE
event look up by id is highly not optimized

### ISSUE THREAD

**Issue by regevbr** [jhuckaby/Cronicle#189]
## Summary

Storage of events is list based with out and hash key for a quick find.
Looking for events based on id (or title for that matter) can potentiality take a long time and can also lock the server from other storage operations

I would suggest using that pixl hash storage instead of the list stroage (if it all possible)...

This will also fix #162

**Comment by regevbr** [comment]
I also think it will be best to allow create event to control the id and then enforce is unique....

**Comment by jhuckaby** [comment]
Actually, it is optimized.  It may not look like it from first glance at the code, but everything in the `global/` storage namespace is [cached in RAM](https://github.com/jhuckaby/Cronicle/blob/master/lib/engine.js#L449) on the master server.  Effectively, after the first load, an event ID lookup is no more complex than a native JavaScript array scan.  Trust me, it's very fast, even with huge schedules.

**Comment by regevbr** [comment]
Ok got it thanks!
