### ISSUE TITLE
Chain Reaction	

### ISSUE THREAD

**Issue by MingqingLi** [jhuckaby/Cronicle#19]
Select an event to run automatically after this event completes.

workflow，I would like to have multiple job options and use the and 、or  connection.  If the first fails or timed out, please upstream and downstream report failed.

**Comment by jhuckaby** [comment]
I am having trouble understanding you.

I believe what you are saying is that you would like to have more varied options when using the Chain Reaction system.  Please note that you can use the JSON API inside your job to trigger any event you want, for any reason.  You don't have to pick a fixed one in the UI.  You have full control.

See: https://github.com/jhuckaby/Cronicle#chain-reaction-control

Does this satisfy your request, or is there something else you wanted?  I apologize for the language barrier, but it looks like your requests are auto-translated from another language.

**Comment by MingqingLi** [comment]
thank you, your understanding is right。I know！
