### ISSUE TITLE
Add external root CA certificates [solution & improvement]

### ISSUE THREAD

**Issue by missilerider** [jhuckaby/Cronicle#192]
## Summary

I have a working cronicle environment, but once I use internal certificates cronicle does not correctly "verify the first certificate" and SSL bypass is needed.

I've already added the CA root cert to the system (it is a CentOS6) and "openssl s_client -showcerts -connect server.domain.local:443" states it is correct from the system certification chain point of view.

I cannot find where to add the CA cert locally to cronicle. Is there a way? Am I missing something?

Thanks in advance!

## Steps to reproduce the problem

Issue a HTTP job to a internal FQDN. The server's certificate should match the FQDN and the CA root cert should also be installed ("ca-trust force-enable" + "cp ca.cert.crt /etc/pki/ca-trust/source/anchors/" + "update-ca-trust extract") and checked accordingly ("openssl s_client ...").

## Your Setup

It is the most simple installation: single server, single task.

### Operating system and version?

CentOS Linux release 7.6.1810

### Node.js version?

v10.15.3

### Cronicle software version?

0.8.28

### Are you using a multi-server setup, or just a single server?

Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

S3

### Can you reproduce the crash consistently?

Yes

## Log Excerpts

You can guess it, but:
```
# Job ID: justzqt000z
# Event Title: job01
# Hostname: cronicle.domain1.local
# Date/Time: 2019/06/11 15:59:36 (GMT+0)

Sending HTTP GET to URL:
https://server.domain.local/resource.html

Request Headers:
User-Agent: Cronicle/0.28
Header: param

Error: unable to verify the first certificate

Performance Metrics: scale=1000&total=31.313&dns=22.399&connect=1.621

# Job failed at 2019/06/11 15:59:36 (GMT+0).
# Error: Error: unable to verify the first certificate
# End of log.
```

**Comment by missilerider** [comment]
Just to let anyone else know: I could add the cert directly to node by using the `NODE_EXTRA_CA_CERTS` environment variable.

Anyway, it would be great if the pixl-request system would accept root CA certificates on runtime instead of messing with the environment. I had to add the "export NODE_EXTRA_CA_CERTS=..." directly to the control.sh script as it failed on the systemd script.

My method will require rewriting everytime I upgrade :'(

Hope it helps.

Best!

**Comment by jhuckaby** [comment]
I'm sorry you are having so much trouble.  Here are two things that can help:

First, you can put custom environment variables into your `config.json` file, and they will survive upgrades.  Check out the [job_env](https://github.com/jhuckaby/Cronicle#job_env) documentation for details.  Example:

```js
"job_env": {
	"NODE_EXTRA_CA_CERTS": "/path/to/your/cert"
},
```

Alternatively, you can add any custom environment variables to your jobs right in the Cronicle Web UI.  Just edit the desired Plugin and add them as hidden parameters.  For example, you can add `NODE_EXTRA_CA_CERTS` as a hidden parameter right into the [HTTP Request](https://github.com/jhuckaby/Cronicle#built-in-http-request-plugin) Plugin, and it becomes an environment variable when the subprocess is spawned.  This will also survive upgrades.

To do this, click on the "**Admin**" tab, then "**Plugins**", then click on the "**HTTP Request**" plugin to edit it.  Then locate the "**Parameters**" section, which should look like this:

<img width="785" alt="Screenshot 2019-06-13 09 04 35" src="https://user-images.githubusercontent.com/700765/59448770-b6187380-8dba-11e9-8207-dae9e91e400c.png">

And click the "**Add Parameter...**" button.  That will pop up this dialog:

<img width="525" alt="Screenshot 2019-06-13 09 05 40" src="https://user-images.githubusercontent.com/700765/59448817-cd576100-8dba-11e9-8279-0729c5bd2c8d.png">

Fill it out as shown above, replacing the value with your custom cert path.  If you set the parameter type to "hidden" then it won't show when editing events.  Or, you could make it a text field, so it IS visible and editable per event (for example, if you have multiple different certs, and need to have different jobs use different certs).

Once you click "Add" to add the parameter, don't forget to click "**Save Changes**" on the Plugin itself.

Hope this helps!

**Comment by missilerider** [comment]
That is exactly what I was looking for! Didn't found that plugin parameters were environmental; I'm also afraid couldn't match my cert requirements with the job_env param.

Thank you very much for you effort and great work.

Regards!

Alfonso
