### ISSUE TITLE
Web Hook URL？

### ISSUE THREAD

**Issue by MingqingLi** [jhuckaby/Cronicle#20]
Please see：
https://dingtalk.taobao.com/docs/doc.htm?spm=a219a.7629140.0.0.MYZwcw&treeId=257&articleId=105735&docType=1

There is no problem in the command line as shown below：

curl 'https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx' \
   -H 'Content-Type: application/json' \
   -d '
  {"msgtype": "text", 
    "text": {
        "content":  "Cronicle message"
     }
  }'

but write ' https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx' in cronicle, cannot receive message.

**Comment by jhuckaby** [comment]
I am having trouble understanding, but I believe what you are saying is that you need the Web Hook system to support a HTTP POST with a JSON message as the request body.  Right now it only supports a simple HTTP GET.

If this is the case, I will mark this issue as an enhancement request.  I don't know soon I will be able to get to it tho.

**Comment by MingqingLi** [comment]
Yeap, I need Web Hook system to support a HTTP POST with a JSON message as the request body。 
  Just do it。

**Comment by jhuckaby** [comment]
I still don't really understand what is needed here, but please see [v0.6.14](https://github.com/jhuckaby/Cronicle/releases/tag/v0.6.14) release.  It has two new features you might find useful for your web hook requirements:

### web_hook_custom_data

If you need to include custom JSON data with the web hook HTTP POST, you can do so by specifying a `web_hook_custom_data` property, and any keys/values will be merged in with the event data as it is sent to the web hook URL.  Example:

```js
"web_hook_custom_data": {
	"msgtype": "text",
	 "text": {
		"content": "????Cronicle message"
	}
}
```

In this example `msgtype` and `text` will be merged in with the event data that usually accompanies the web hook post data.  See the [Web Hooks](https://github.com/jhuckaby/Cronicle#event-web-hook) section in the docs for more on the data format.

### web_hook_ssl_cert_bypass

If you are having trouble getting HTTPS/SSL web hooks to work, you might need to set `web_hook_ssl_cert_bypass` to true.  This causes Node.js to blindly accept all HTTPS URLs, even when it cannot validate the SSL certificate.  This effectively sets the following environment variable at startup:

```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

Please only do this if you understand the security ramifications, and *completely trust* the host you are connecting to, and the network you are on.  Skipping the certificate validation step should really only be done in special circumstances, such as trying to hit one of your own internal servers with a self-signed cert.

Good luck to you.
