### ISSUE TITLE
API requests on Backup Master nodes

### ISSUE THREAD

**Issue by alexpanas** [jhuckaby/Cronicle#216]
## Summary

Hello,
I have a setup of one master and two backups (and 3 slaves)

I have following settings on all master-eligible servers:
        "server_comm_use_hostnames": false,
        "web_direct_connect": true,
        "web_socket_use_hostnames": false,

When I try queuing one of the backups for schedule (e.g. 
http://{backup IP}:3012/api/app/get_schedule/v1?api_key=<> ) the backup redirects the query to the master hostname (resulting URL is http://{Master hostname}:3012/api/app/get_schedule/v1?api_key=<>)

As far as I can see - there is currently no setting which can change this behavior (hostname vs IP address in the redirect).

Is it possible to add ability to control this behavior - or to have it to comply to server_comm_use_hostnames or server_comm_use_hostnames values and have the IP address of the master instead of its hostname in the URL?

## Steps to reproduce the problem
Try querying any Backup master server via API for schedule

## Your Setup
3 "master-designated" servers, 3 slaves

### Operating system and version?
CentOS Linux release 7.6.1810 (Core)

### Node.js version?
v10.16.2

### Cronicle software version?
0.8.31

### Are you using a multi-server setup, or just a single server?
Multi-server setup
### Are you using the filesystem as back-end storage, or S3/Couchbase?
Couchbase

**Comment by jhuckaby** [comment]
I do apologize, but there is no way to do what you are asking (if I understand it correctly).  Only the master server can accept actionable API requests, so if any slaves get the request by mistake, they issue a 302 redirect to the master.  It is up to the client to follow the redirect and hit the correct server for the API request.

This behavior is discussed in the docs here: https://github.com/jhuckaby/Cronicle#redirects

> If you are running a multi-server Cronicle cluster with multiple master backup servers behind a load balancer, you may receive a HTTP 302 response if you hit a non-master server for an API request. In this case, the Location response header will contain the proper master server hostname. Please repeat your request pointed at the correct server. Most HTTP request libraries have an option to automatically follow redirects, so you can make this process automatic.

> It is recommended (although not required) that you cache the master server hostname if you receive a 302 redirect response, so you can make subsequent calls to the master server directly, without requiring a round trip.

I hope this helps, and I'm sorry I don't have a better answer.

**Comment by alexpanas** [comment]
Joseph,

Thank you for the confirmation and sorry for not being clear enough.

My point was that currently there is a way to force servers to connect to each other using IPs only (setting "server_comm_use_hostnames": false and "web_socket_use_hostnames": false) - but the clients using the API will revert to using master hostname (which is not necessarily resolvable by the client) after first redirect.

But as mentioned in the Ops section of the documentation (which I should have been reading more thoroughly)  - 
Each server in the cluster needs to have a fully-qualified hostname that resolves in DNS.

This complicates a bit the setup of multi-server testing environments, but is still reasonable I assume - and basically eliminates my initial inquiry.

**Comment by jhuckaby** [comment]
Oh okay, I see what you're saying now.  Yeah, that's definitely a bug.  The 302 master redirect should definitely honor the `server_comm_use_hostnames` setting.  Marking as such.  Thanks!

**Comment by kamcio2603** [comment]
Any news about fixing bug?

**Comment by jhuckaby** [comment]
Should be fixed in [v0.8.43](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.43).  Thanks!
