### ISSUE TITLE
Question about parameter for bash script

### ISSUE THREAD

**Issue by needelp** [jhuckaby/Cronicle#217]
Hello,

I want to create a plugin wich the executable is a bash file then i want to create a lot of job with this plugin but with différents arguments.

example : 

PLUGIN 1
executable : /scripts/test.bash
parameter : ID=IP; value:"enter IP here"

JOB 1
plugin : PLUGIN 1
IP : 127.0.0.1

JOB 2
plugin : PLUGIN 1
IP : 192.168.0.1

obviously it doesn't work

there is a way to put argument to my executable like : /scripts/test.bash $argument1 ?

Thanks in advance,

Best Regards,

**Comment by jhuckaby** [comment]
This works exactly as you describe.  Just make sure you upper-case the `$IP` in the command line.  So setup your Plugin like this:

<img width="705" alt="Screen Shot 2019-08-28 at 10 05 35 PM" src="https://user-images.githubusercontent.com/700765/63911740-25782980-c9e0-11e9-95fb-de350361dbed.png">

Then setup your events like this:

<img width="467" alt="Screen Shot 2019-08-28 at 10 04 10 PM" src="https://user-images.githubusercontent.com/700765/63911749-2b6e0a80-c9e0-11e9-8bd2-225a7f325557.png">

And the user-entered IP address will be passed to the executable like this:

```
/scripts/test.bash 11.22.33.44
```
