### ISSUE TITLE
Best practices to deliver plugins to cronicle

### ISSUE THREAD

**Issue by vanatd** [jhuckaby/Cronicle#222]
## Question
I have question about delivery plugins to cronicle.

We have some structure of plugins where we use npm modules as plugins.
Then when we create/update plugin we change package.json and run npm install in cronicle docker. This approach good for us in almost all cases, but we need to check and wait until cronicle become free (no jobs running), 'cause npm install lead us to build new container then deploy it. So we have to reload cronicle. 
Here I have a question, maybe you have some practices how to add new plugin in to the cronicle, I mean file/files which will be executed, without reload. 
We can create some ci cd to copy/clone/install plugins near cronicle, but wants to have some versioning for plugins, i mean just clone the repo is not good :)
Can you help somehow with it?

P.S. Thank to you about such cool project!

**Comment by jhuckaby** [comment]
I do apologize, but I don't have a clever way of doing this.  At my day job we just have a roll script that iterates over all our servers and restarts the services.  New software (including Plugins) are installed in the middle of that process.  So it's stop, install, start.  I know, it's really simple and stupid, but it works.  I'm sorry I don't have anything better 😞

**Comment by denis-vanat** [comment]
you totally no need to apologize!! you did a great job! so, how to deliver plugins it’s our problem. 
i’m thinking about mounting a folder to the docker container and try to run plugin from this folder. but here i need to think how to handle plugins versions.
Anyway, thanks for your great job!
