### ISSUE TITLE
Error: Cannot find module './engines/Couchebase.js'

### ISSUE THREAD

**Issue by fullmoon4465** [jhuckaby/Cronicle#227]
cd /opt/cronicle 
npm list | grep couchbase
├─┬ couchbase@2.6.8

## Summary

Fresh install of cronicle and trying to use couchbase for backend but is throwing error on setup script missing module.

## Steps to reproduce the problem

Follow your setup on using couchbase with this application

### Operating system and version?

Ubuntu 16.04 LTS

### Node.js version?

v10.16.3

### Cronicle software version?

its not started yet but I just pulled this down last week

curl -s https://raw.githubusercontent.com/jhuckaby/Cronicle/master/bin/install.js | node

### Are you using a multi-server setup, or just a single server?

Planning on multi server setup, just at the starting point of getting one of them installed first fresh with couchbased backend

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Trying to use couchbase

### Can you reproduce the crash consistently?

Just trying to run the setup script yes keeps throwing error about the missing module. May have to do with pathing in my env and nodejs but not sure

## Log Excerpts

/opt/cronicle/bin/control.sh setup
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './engines/Couchebase.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:71:23)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:50:19
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by jhuckaby** [comment]
You spelled "Couchebase" wrong.  It's spelled **Couchbase** (there's no "e" in it).  In your config file, you likely did this:

```js
"engine": "Couchebase"
```

You need to change it to this:

```
"engine": "Couchbase"
```

**Comment by fullmoon4465** [comment]
LMAO; you have no idea how many times my muscle memory kept adding 'e' in it when creating DNS records and config. THANKS for the quick reply!
