### ISSUE TITLE
Feature request: Hide job body in notification

### ISSUE THREAD

**Issue by lukasmrtvy** [jhuckaby/Cronicle#231]
I would be nice to be able to hide job body in notifications, it may contain secrets.
Thanks

**Comment by jhuckaby** [comment]
I don't know what "job body" is, but you have complete control over the e-mail notification contents.  Please see this section of the docs: 

https://github.com/jhuckaby/Cronicle#email-configuration

Simply edit the `conf/emails/job_success.txt` and/or `conf/emails/job_fail.txt` files on your Cronicle master server, and make any changes that you want.
