### ISSUE TITLE
SMTP Port in Config not respected in Admin UI for some things

### ISSUE THREAD

**Issue by fullmoon4465** [jhuckaby/Cronicle#233]
I am using non standard port for STMP via my relay host which is 60025.

In my conf/config.json the three params are

        "email_from": "cronicle.admin@company.com",
        "smtp_hostname": "relay.company.com",
        "smtp_port": 60025,

Now, my emails work via the on Success and on Error just fine. However I just noticed when adding a "new user" in the UI I didn't get an email. I also attempted to use the "forgot password" and you can see that even though i said to use 60025 the error on the page is stating its attempting to use port 25 which isn't open on my relay host.

Please advise

**Comment by jhuckaby** [comment]
Thanks for the issue report.  This is actually a bug in one of the supporting libraries, [pixl-server-user](https://github.com/jhuckaby/pixl-server-user), and is now fixed.  This will be included in the next Cronicle release.  If you can't wait for that to happen, you can add this to your `config.json` file:

```js
"mail_options": {
	"port": 60025
}
```

And then restart Cronicle.

Thanks again!
