### ISSUE TITLE
special bash 'echo'

### ISSUE THREAD

**Issue by needelp** [jhuckaby/Cronicle#235]
Hello all,

I encountered a problem when I tried to'echo' the -e argument.

See below how to reproduce the problem : 

Code : 
`#!/bin/bash`
`echo -e "bla   bla\c"`
`sleep 1`
`echo -e "\rbla 1 bla"`

result in shell : 
line 1> bla   bla
--> 1 sec later
line 1> bla 1 bla

result in Cronicle log : 
line 1> bla   bla
--> 1 sec later
line 1> bla   bla
line 2> bla 1 bla

I think that node.js can't do an echo until it sees a carriage return.

There is a solution to get around the problem?

Thanks in advance for your help,

Best regards,

**Comment by needelp** [comment]
Re,

I find a dirty way to get around the problem : 
i just sed the log file, but it's VERY dirty to do that. there is a proper way to do this ?

**Comment by jhuckaby** [comment]
Hey there,

I am so sorry to report this, but this is currently "as designed" behavior.  The Cronicle log watcher system works on a line-by-line basis -- it literally watches for EOL characters to delimit the lines sent to the browser, and each line then becomes a DIV in the DOM.  There is no easy way to support sub-line micro updates in the current architecture.

I will try to address this in the big v2.0 release (coming next year), but I can't promise anything. 

I'm sorry I don't have better news 😞

**Comment by needelp** [comment]
Hi,

Thanks for your feedback.
For the moment I will use my dirty way so.
I'm sorry to open a lot of ticket, Cronicle is the central application of our big project and I had to learn it in depth.

May I'll have more questions in the future
