### ISSUE TITLE
Can't write Couchbase

### ISSUE THREAD

**Issue by MingqingLi** [jhuckaby/Cronicle#24]
no log  completed jobs and no events found in web UI

**Comment by MingqingLi** [comment]
no log, no  Completed Jobs in web UI

**Comment by jhuckaby** [comment]
I'm sorry, but GitHub Issues is not a place for getting technical support.  This is a place to report bugs with the product.  I cannot help you with what you have provided here.

You may want to consider a different product that has more developers and community support behind it.  Cronicle is developed by one person in his free time.  Have you considered using [Chronos](https://mesos.github.io/chronos/), by the AirBnB team?

https://mesos.github.io/chronos/

It may be more to your liking.  You can read more about it here:

https://medium.com/airbnb-engineering/chronos-a-replacement-for-cron-f05d7d986a9d

Good luck to you.

**Comment by MingqingLi** [comment]
thank you!

**Comment by MingqingLi** [comment]
"Storage": {
                "engine": "Couchbase",
                        "Couchbase": {
                                "connect_string": "couchbase://x.x.x.x:8091",
                                        "bucket": "beer-sample",
                                        "password": "",
                                        "serialize": "false"
                        }
        }

**Comment by jhuckaby** [comment]
Look for `/opt/cronicle/logs/Error.log`.  It might hold some clues as to what is wrong.
