### ISSUE TITLE
Queue Job

### ISSUE THREAD

**Issue by needelp** [jhuckaby/Cronicle#242]
Hello all,

I would like to know if it is possible to configure a job such as :

He can only be in queue once
It can only be in progress once
He can't be in queue and in progress at the same time

At the moment, I can respect the first two points, but not the last.
I can't get the job to queue up while a similar job is in progress....

Anyone to help me with that?

Thank you in advance for your help,

**Comment by jhuckaby** [comment]
I am sorry, but this is not possible with Cronicle.  The queue system is only activated if there is already a job running.  So that right there omits the possibility of your third item.

**Comment by needelp** [comment]
Thanks for your feedback,

Will the modification be made in a later version?

**Comment by jhuckaby** [comment]
I do apologize, but I just don't understand the logic.  Your three rules seem to contradict each other.  I just have no idea how to code this feature.

**Comment by needelp** [comment]
Hello,

It doesn't matter for the moment. I will close ticket for the moment.

My manager and I, have a ton of questions...
Is it possible that we could talk directly to each other?
Not now, but in a future I mean

I will describe in detail our project and any questions we may have about Cronicle's roadmap. I think that a confcall could be beneficial for you as well as for us on the progress of our project as well as the improvement of yours on future versions of Cronicle.

**Comment by jhuckaby** [comment]
I'm very sorry, but I really don't have time for that.  I am quite busy with my day job.  Cronicle is just a side project of mine, and is really just a hobby.

If you have any feature requests, or run into bugs, please feel free to add them here in GitHub.  I will address them as soon as I have time, but please note, I don't have a timeline for fixes.

If your company is looking for a production grade, enterprise level scheduler, then Cronicle may not be it.  This is just a fun little project of mine.  You might want to look into something like [Chronos](https://medium.com/airbnb-engineering/chronos-a-replacement-for-cron-f05d7d986a9d) by Airbnb.

Anyway, thank you for your interest, and best of luck to you and your company!

**Comment by saravanakesavan** [comment]
Can you suggest someother scheduler other than Chronos ?

**Comment by benpro** [comment]
Chronos did not receive updates since 2016... Actually, we are considering Cronicle at work as a replacement. :)
This ticket should be closed I guess?

**Comment by jhuckaby** [comment]
Sure, I'll close this.  But I will say in closing, if you want a good alternative to Cronicle, check out [Rundeck from PagerDuty](https://www.pagerduty.com/integrations/rundeck-runbook-automation/).  It's pretty dang neat.
