### ISSUE TITLE
Job history with the api

### ISSUE THREAD

**Issue by tquille2** [jhuckaby/Cronicle#247]
Hi,

I use the api "api/app/get_schedule" to view my jobs. And it's works.

But now, i need to know the state of my job (Success or failed). And i need to it for the last 5 executions.

Can you help me ?

I can use the api or linux command line.

Cordialy,

**Comment by jhuckaby** [comment]
Hello,

Yeah, sorry, that API exists, but it is not yet documented.  I honestly don't have time to write out all the documentation right now, but here is what you need to get it going:

URI Endpoint: `/api/app/get_event_history`

Query String Parameters:

| Parameter | Description |
|-|-|
| `id` | The **Event ID** of the scheduled event you want to get history for.  You can find this on the Edit Event page at the very top of the form, above the event title.  |
| `offset` | The offset into the data.  Passing `0` means get the latest jobs. |
| `limit` | The number of jobs to fetch. |

Example URL:

```
http://MASTER_SERVER/api/app/get_event_history?id=ejs9m57bw01&offset=0&limit=5
```

The response will contain an array of job runs, each one following the [Event Data Format](https://github.com/jhuckaby/Cronicle#event-data-format).

This API requires authentication, so please setup an [API Key](https://github.com/jhuckaby/Cronicle#api-keys) and pass it in using any of the methods available.

**Comment by tquille2** [comment]
Perfect, Thank you

**Comment by jhuckaby** [comment]
Added to docs.  Closing this.
