### ISSUE TITLE
24 hour time format

### ISSUE THREAD

**Issue by csadam** [jhuckaby/Cronicle#250]
Is it possible to display time values in 24 hour format instead of AM/PM?

**Comment by jhuckaby** [comment]
Not currently, but I would be happy to add this feature.

**Comment by ugoviti** [comment]
Hi, definitively a useful feature.

Thankyou!

**Comment by Zixim** [comment]
definately +1

**Comment by Shto1337** [comment]
+1

**Comment by ugoviti** [comment]
+1 absolutely for me too :)

**Comment by Richdark** [comment]
Hey, I've just started using Cronicle and it has been amazing so far! The lack of option to switch to 24-hour format is really the only thing that is bothering me at the moment, so one more vote for this from me. Anyway, thank you for this project!

**Comment by jhuckaby** [comment]
So sorry for the delay on this.  It is coming in v2!  Due for release in early 2025.

See #99 for a screenshot.

Closing this as it's actually a duplicate of #99
