### ISSUE TITLE
API to get all events

### ISSUE THREAD

**Issue by LtCMDstone** [jhuckaby/Cronicle#252]
Hey this is not an issue it's more a wish for enhancement.
First of all nice work, Cronicle is such a nice tool!

Can you extend the get_event API so we could get all events?
So like passing no title or id so we get a list of everything.

Best regards
stone

**Comment by jhuckaby** [comment]
Thanks, but the API you want already exists I think.  It's [get_schedule](https://github.com/jhuckaby/Cronicle#get_schedule).  This fetches all the events.

**Comment by LtCMDstone** [comment]
So it return the created events?
I thought it would return the schedule it self what events run in the next time.

**Comment by LtCMDstone** [comment]
Ah ok, I tested and yes i missunderstood :)
