### ISSUE TITLE
Get running jobs API

### ISSUE THREAD

**Issue by servo1x** [jhuckaby/Cronicle#261]
Hi,

Is there an API endpoint to get all running jobs (even ones started manually)?

Thanks!

**Comment by jhuckaby** [comment]
I'm so sorry, but there is not.  I will add this to the TODO list and get it done as soon as possible.

**Comment by servo1x** [comment]
No need to apologize @jhuckaby , if you want to provide any pointers maybe someone could make a PR?

**Comment by jhuckaby** [comment]
No need for a PR, it's a one-liner change, I just need to update the docs.  I'll get it done tonight.  I'm just stuck at my day job at the moment.  I'll have a release ETA 8 PM PST.

- Joe

Joseph Huckaby
jhuckaby@gmail.com

**Comment by servo1x** [comment]
Thank you so much! 👍

**Comment by jhuckaby** [comment]
Okay, I just dropped [Version 0.8.42](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.42) which has the requested API.  Have fun!  Docs:

https://github.com/jhuckaby/Cronicle#get_active_jobs

### get_active_jobs

```
/api/app/get_active_jobs/v1
```

This fetches status for **all active** jobs, and returns them all at once.  It takes no parameters (except an [API Key](https://github.com/jhuckaby/Cronicle#api-keys) of course).  The response format is as follows:

```js
{
	"code": 0,
	"jobs": {
		"jk6lmar4c01": {
			...
		},
		"jk6lmar4d04": {
			...
		}
	}
}
```

In addition to the [Standard Response Format](https://github.com/jhuckaby/Cronicle#standard-response-format), the response object will contain a `jobs` object.  This object will have zero or more nested objects, each representing one active job.  The inner property names are the Job IDs, and the contents are the status, progress, and other information about the active job.  For details on the job objects, see the [get_job_status](https://github.com/jhuckaby/Cronicle#get_job_status) API call above, as the parameters of each job will be the same as that API.
