### ISSUE TITLE
get_all_events API

### ISSUE THREAD

**Issue by servo1x** [jhuckaby/Cronicle#262]
A API for getting all events would be super useful.

When we run a deploy we typically run database migrations and would like to stop a set of events, and then wait for the running jobs to be be finished (#261).

After we finish migrations, we would like to make a API request to reenable all the events.

While there is the `update_event` api, it requires knowing the `event_id` ahead of time which can be problematic across different environments. There doesn't seem to be a way to look up events.

A `get_all_events`, which returns all events would be sufficient for us, as then we can write a script to take all the event ids and pass it to `update_event` and modify the `enabled` property to our needs.

Thanks!

**Comment by jhuckaby** [comment]
This API already exists.  It's called `get_schedule'.  Docs: https://github.com/jhuckaby/Cronicle#get_schedule
