### ISSUE TITLE
Operational Difficulty In Busy Environment

### ISSUE THREAD

**Issue by geofffox** [jhuckaby/Cronicle#264]
## Summary

Because I have many short jobs constantly finishing and the 'History' page dynamically updates, it is nearly impossible to "filter by event."  I can't get to the last menu items before the page changes and the picker box closes.

Since this is a front facing problem I'm going to skip the following steps.

### Can you reproduce the crash consistently?
Yes

**Comment by jhuckaby** [comment]
All fixed in [v0.8.44](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.44), just released.  Thanks!!! 😃

**Comment by geofffox** [comment]
Thanks, Joe.
