### ISSUE TITLE
email identification problem

### ISSUE THREAD

**Issue by gokyman** [jhuckaby/Cronicle#272]
Hi,

The problem I experienced in the process of defining mail to my Cronicle account is as follows;

/opt/cronicle/conf config.json I fill my mail information in this file.

               "base_app_url": "http://xx.xx.xxx.xx:3012",
               "email_from": "info@xxxx.com.tr”,
               "smtp_hostname": "xxx.xxxx.com",
               "smtp_port": 465,                  
               "secret_key": "xxxxxxx",      // I enter the mail password. 

Then /opt/cronicle/bin/control.sh  I am performing the upgrade.

I want it to enter to my admin account "http://xxx.xx.xxx.xx:3012 " and to open trial from "Schedule section" and send me an email.

I get the following issiue which i reach from  "Admin Activity Log"

Failed to send e-mail for job: jk94f2d8y0q: xxxxx.xxxx@xxxx.com.tr: Error: Can't send mail - all recipients were rejected: 550-"JunkMail rejected - (localhost.localdomain) [xxx.xx.xxx.xx]:44964 is in an 550 RBL: https://www.spamhaus.org/query/ip/xxx.xx.xxx.xx" 

I am waiting for your return as soon as possible about the error. Thank you.

**Comment by gokyman** [comment]
no one to help me?

**Comment by jhuckaby** [comment]
This is a problem with your SMTP server, not with Cronicle.  Try using Sendmail instead:

https://github.com/jhuckaby/Cronicle#mail_options

You can also use `mail_options` to use local [sendmail](https://nodemailer.com/transports/sendmail/), if you have that configured on your server.  To do this, set the following properties, and tune as needed:

```js
"mail_options": {
	"sendmail": true,
	"newline": "unix",
	"path": "/usr/sbin/sendmail"
}
```

You can omit `smtp_hostname` and `smtp_port` if you are using sendmail.

Good luck.
