### ISSUE TITLE
Can Cronicle support multiple steps in one event(job)?

### ISSUE THREAD

**Issue by jackhuangca** [jhuckaby/Cronicle#276]
## Summary

Can Cronicle support multiple steps in one event?

## Steps to reproduce the problem

For example, 
Step 1, create a zip file
Step 2, send to SFTP server

So when step 2 fails because of the internet, I can just re-run step 2, without re-generate the zip file in step 1.

**Comment by jhuckaby** [comment]
Check out the **[Chain Reaction](https://github.com/jhuckaby/Cronicle#chain-reaction)** system.  It should do what you need here.
