### ISSUE TITLE
Event names not showing on Completed tab after deleting event

### ISSUE THREAD

**Issue by jhuckaby** [jhuckaby/Cronicle#28]
From @pallavibatra-cpi, copied here from #25:

After deleted the event when i restart the cronicle, in the COMPLETED tab, i can see all the job ids but "(None)' in Event Name. Below is the screenshot :

![Image](https://cloud.githubusercontent.com/assets/25767871/25526067/86552e02-2c2f-11e7-90a8-1ea2e97bd8cc.png "Screenshot")

Is there any way possible to show the name of the event it was running before it got deleted.

Thanks
Pallavi
(pallavi.batra@chargepoint.com)

**Comment by jhuckaby** [comment]
This should be fixed in [v0.6.15](https://github.com/jhuckaby/Cronicle/releases/tag/v0.6.15).  Note that this will only work for new completed jobs going forward.  Meaning, it does not retroactively resurrect old event titles for jobs that completed before upgrading to 0.6.15.

**Comment by pallavibatra-cpi** [comment]
Thanks jhuckaby for being the saviour 👍 . This issue is resolved now.
