### ISSUE TITLE
entry point for docker

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#282]
Any suggestion how to start Cronicle as an docker entry point? Currently control.sh/start and node/main.js just start a background proccess, so docker container stops right away. How to run it in foreground?

**Comment by jhuckaby** [comment]
I don't know how to use Docker, but I believe others have figured this out.  Please see:

https://github.com/belsander/docker-cronicle

**Comment by mikeTWC1984** [comment]
OK. I saw that, but it seemed to use "node ../main.js". I was looking for a simple way to bring cronicle to foreground, since docker is kind of daemon itself.

**Comment by jhuckaby** [comment]
Oh okay.  Check out the environment variables for a solution:

https://github.com/jhuckaby/Cronicle#environment-variables

I believe `CRONICLE_foreground` is what you are looking for.  @belsander uses this in his Docker script as well.

Good luck!

**Comment by mikeTWC1984** [comment]
Perfect, thanks!
