### ISSUE TITLE
feature: Reports

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#286]
I think it would be useful to let user host arbitrary html pages using cronicle. Say let them create folder where they can dump html files, then view it through cronicle web ui, e.g.
http://localhost:3012/reports/somereport

**Comment by jhuckaby** [comment]
You can already do this now.  Cronicle serves static files out of `/opt/cronicle/htdocs/`.  Place whatever you want in there, reports, etc.  then you can view them with URLs.
