### ISSUE TITLE
How to reuse (backup) data/logs for file system storage?

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#288]
I'm trying to reuse logs/schedules from one cronicle instance in another (by copying /opt/cronicle/data and logs from old instance to another one). If I do this then new installation will stick forever in "Waiting for master" state on the next restart. Is there any suggestion how to properly move schedules/history around instances?

**Comment by mikeTWC1984** [comment]
I tried migration tool and export/import (control tool), but it seemed to be broken - cronicle doesn't start after doing that (same as manual copy/pasting of data/global).

**Comment by jhuckaby** [comment]
So, you're trying to do something that is not supported.  The Cronicle data storage system is not meant to be transplanted across servers.  If you want to run multiple master servers, please read the documentation for the options available.  You can use NFS, Amazon S3 or Couchbase.  Details:

https://github.com/jhuckaby/Cronicle#multi-server-cluster

Hope this helps.

**Comment by mikeTWC1984** [comment]
I'm looking for a way to back up (import/export) job schedules and ideally history. Say if current setup crashed, or I need to install it on a different server. Is it possible without entering manually entering schedules?

**Comment by mikeTWC1984** [comment]
interesting, export/import worked if I grep only lines related to schedule. If I import entire export file cronicle will not start

**Comment by mikeTWC1984** [comment]
Ok, so the problem is that default setup.json uses host name and external ip of the host in the configuration. So if host changes then it wont work. Is it possible to use localhost/127.0.0.1 instead? Or how to set specific hostname/ip? I tried to modify _HOST_/_IP_ on the setup.json, it doesn't work

**Comment by mikeTWC1984** [comment]
btw this command hangs up. 
/opt/cronicle/bin/control.sh  stop (and thus any related comand like restart)
Need to hit ctrl+C to stop it (it's not causing any issues though)

**Comment by jhuckaby** [comment]
It looks like you're reporting many different issues here.  I'll address the first one, i.e. the title of this issue.

What you are trying to do is not currently implemented as a feature, or supported.  That being said, you can theoretically edit the raw internal server list, and change the server IPs and hostnames to whatever you want.

Please note, this is **not** supported at all, and I cannot be held responsible for any data loss in trying to do this.  Also, please **shut down** Cronicle before editing the raw storage files, as they are cached in RAM while it is running.

This command will spawn your Terminal's `EDITOR` command (i.e. `vi`), so please set this to whatever editor you want.  The files are all JSON format.

```
cd /opt/cronicle
bin/storage-cli.js edit global/servers/0
```

Please be very careful with the JSON syntax, as it is very picky.  Once you save and exit your editor, the data record will be written back to storage.  Then restart Cronicle and it will accept these servers as the source of truth.

Good luck.

**Comment by mikeTWC1984** [comment]
Thanks. I realized if I keep same host name, everything  works fine. I can reuse data/logs folder with new install, export/import works too (it actually works on different host names as long if you grep out server configs). 
Assigning hostname (or ip) is not a big deal if you are using containers (so I guess I'm good). Probably storage cli would help to alter name on actual machine/VM. Although wouldn't it be a natural solution to use "localhost" rather actual hostname on the single master set up (in default setup.json)? Looks like cronicle consider "localhost" as a separate master on a separate cluster.

**Comment by mikeTWC1984** [comment]
OK, never mind, I was just thinking of single master/single node setup, but in multi-node setup localhost is not unique so it make no sense. I was able to reconfigure node on the new host using storage-cli indeed, thanks. 
Btw, it might be a good idea to create simplified single node version of cronicle
