### ISSUE TITLE
[question] Is redis supported as a storage?

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#300]
I'm reading trough this doc https://www.npmjs.com/package/pixl-server-storage#couchbase, so pixl-server seemed to support redis. Can redis be used with cronicle?

**Comment by jhuckaby** [comment]
It's untested at this point, but it should work.  I'm still worried about the max record size, as the Cronicle job logs are uploaded to storage, and Redis may have some kind of limit.

Feel free to try it, just please understand that it is at your own risk 😊 

I'm currently working on "hybrid" storage support for two different engines, so people can have the data records (i.e. schedule, categories, users, plugins) go to one place, and the large binary blobs (job log files) go to another.

**Comment by mikeTWC1984** [comment]
Thanks. I just tried and it worked. I tried couchbase earlier and have some troubles, but I guess neither are good options for the reasons you mentioned. 
The "hybrid" options sounds great. I think it would even make git a useful option for storing metadata

**Comment by mikeTWC1984** [comment]
Hm, actually git would be usable even now if you can trigger event by creating objects (users/schedules). Is there a trick to achieve this? E.g. to execute git add/commit/push upon creating new object
