### ISSUE TITLE
Jobs folder over 20Gb

### ISSUE THREAD

**Issue by geofffox** [jhuckaby/Cronicle#304]
## Summary
I recently broke down my jobs into smaller pieces -- meaning more jobs.  The jobs folder size has exploded.  I tried changing "job_data_expire_days": 30, but there's been no reduction.  Also lowered the number of jobs kept from 10000 to 1000.

I restarted cronicle and ran maint (with and without today's date)
[cronicle-config-file.txt](https://github.com/jhuckaby/Cronicle/files/4880569/cronicle-config-file.txt)

## Steps to reproduce the problem

Cronicle working as expected

**Comment by geofffox** [comment]
To alleviate the problem I have moved /opt/cronicle to a symbolic link on a drive with more (4Tb) space.

**Comment by jhuckaby** [comment]
Hey Geoff, glad you were able to move the data to another drive!

Yeah, so the [job_data_expire_days](https://github.com/jhuckaby/Cronicle#job_data_expire_days) configuration parameter only takes effect on **new** jobs, not existing ones.  This is why you didn't see any immediate relief when you made the change.  Unfortunately, there is no way to change the expiration date for existing job data in storage -- it has to live out its life.  The only way to do it would be to hard-delete all the job data.  Luckily, you can do this without affecting any other Cronicle data.  See below:

Assuming you are using the local filesystem and the default storage configuration, you can delete all job log data using these commands:

```
/opt/cronicle/bin/control.sh stop
rm -rfv /opt/cronicle/data/jobs/*
/opt/cronicle/bin/control.sh start
```

Good luck!

**Comment by geofffox** [comment]
Thanks Joe.  I really don't mean to be this needy.

Every once in a while I go beyond my knowledge.  It's very scary.  Luckily
my friend Greg knew how to make things better.

The rm on /opt/cronicle/data/jobs has been running over ten hours now.
Folders in folders in folders is tough!  I started with about 800mb free.
I remember when that was a lot.  I now have 16Gb free with around 5 or 6
left to reclaim.  My home drive has 4Tb-plenty of space.

Thanks again for your help.  Please, if you ever want to do a tutorial
video I will produce it for you.  I owe you so much.

Geoff

**Comment by jhuckaby** [comment]
No problem, man!  Glad to help.  I'm really glad you had a big drive laying around, and your friend help you with the symlink.

Ten hours, wow!  That's a lot of jobs.  I hope it finishes soon!

**Comment by geofffox** [comment]
I finally stopped it.  All that reading/writing/deleting/synchronizing was
slowing down my already overloaded schedule.  I'm off Friday and will
finish the job.

**Comment by foorschtbar** [comment]
Same problem here. I have some jobs that runs every minute and producing in the last few months more than one million files in the jobs folder - vscode hates that 🤣 

I am right, if i delete the files manual this time and set 

```
list_row_max=1000
job_data_expire_days=30
```

or do I need to recreate the jobs for the effect to occur?

**Comment by jhuckaby** [comment]
Yeah, the `job_data_expire_days` only takes effect for new jobs.  It doesn't retroactively change the expiration set for previously completed jobs.

**Comment by saikrishna1488** [comment]
@jhuckaby I'm also facing the same issue, and it's quite difficult for us to run the rm command continuously for 10 hours.

I have one question regarding your statement: **"the job_data_expire_days only takes effect for new jobs."**

Let’s say I initially configured job_data_expire_days = 15 and kept it for a month. Then I changed it to job_data_expire_days = 7. My understanding is that logs generated after this change will expire in 7 days, but logs generated before the change will still follow the 15-day expiry. Is that correct?

And over time, as new jobs follow the updated 7-day rule, eventually all logs will start expiring after 7 days. Am I understanding this correctly?

**Comment by jhuckaby** [comment]
@saikrishna1488 You are 100% correct.

**Comment by saikrishna1488** [comment]
@jhuckaby Thanks man for your quick reply. And the tool is awsome.
