### ISSUE TITLE
Confusing with the `job_memory_max`

### ISSUE THREAD

**Issue by Passengerss** [jhuckaby/Cronicle#308]
## Summary
job abort when the memory usage reach the `job_memory_max`,  this is right. 
 but i have some problem understanding the `memory_size`.

For job A which is a job with large log to record, maybe the size could reach to 10 Gb.  

does `Cronicle`  save the whole job's log to memory and then save it to disk when the job get done?

or the `job_memory_max` is just the flag that tells the Cronicle to save log to disk when the memory usage reach `job_memory_max`.

for me now, it seems like first situation here.

**help wanted**
- i wonder if there is a way to save log to disk directly, maybe there is no sufficient memory(RAM?) to increase `job_memory_max` to 4G or bigger.

**Comment by jhuckaby** [comment]
The job memory is measured by sampling **your processes only**, meaning the processes that you spawn for your jobs.  It does not have anything do with Cronicle's internal memory.

Cronicle does not load the log files into memory.  You can create a job log file of any size, and it will not affect memory usage (as long as you yourself don't load it into memory).

**Comment by Passengerss** [comment]
Thanks for your quickly replying, I'm clear now. :smile:
