### ISSUE TITLE
Question: Is there an easy way to upgrade all Cronicle hosts in a cluster?

### ISSUE THREAD

**Issue by mpatel-cpi** [jhuckaby/Cronicle#31]
We have a single-master, multi-slave setup Cronicle setup. Does Cronicle detect version mismatch between various Cronicle master(s)/slave(s)? I'd imagine weird bugs in case master/slave go out-of-sync?

- Is there an easy way to upgrade all hosts in the cluster?
- It would be nice if "Server Cluster" table on "Admin -> Servers" page showed current Cronicle version for each host.

**Comment by jhuckaby** [comment]
Hey there,

Don't worry, the API is fully backward compatible.  You can have mismatched versions across your cluster and everything will be fine.  I won't make any breaking API changes like that until v2.0 or later, and I'll make sure there is a very clear and easy upgrade path when the time comes.

Upgrading a Cronicle server is very easy -- it's just one single command.  This also automatically shuts down and restarts the service as well:

```
/opt/cronicle/bin/control.sh upgrade
```

Just enter that one command on all your servers and you'll be on the latest version.  You can also do it in any order -- Cronicle will reconnect all the servers when they come back online.

At some point in the future I'll add a button to do this from the UI.  And I'll display the current version number for each server as well (thanks for that feature request!).

Hope this helps!

**Comment by mpatel-cpi** [comment]
You're awesome @jhuckaby. Thanks!

**Comment by aldanor** [comment]
In the UI, you can create an event with 'Multiplex' type so it runs on all servers and then do something like this:

```sh
nohup /opt/cronicle/bin/control.sh upgrade >/dev/null 2>&1 &
```

Running this event will trigger the upgrade on all servers (you won't see it in the logs though).
