### ISSUE TITLE
Can the shell plugin accepts parameters from API call?

### ISSUE THREAD

**Issue by doronyaary** [jhuckaby/Cronicle#312]
## Summary

I would like to know if I can pass parameters to a shell script event - when executing the event from an API call

## Steps to reproduce the problem

There are no steps to reproduce.

## Your Setup

My setup included the simple nodejs installation and Cronicle installation "by the book"

### Operating system and version?

CentOS 7 x64 (1cpu 1gb RAM)

### Node.js version?

14.5.0

### Cronicle software version?

Version 0.8.47

**Comment by jhuckaby** [comment]
Of course, please see the [docs for the run_event API call](https://github.com/jhuckaby/Cronicle#run_event).  It has all the details.

Example request:

```js
{
	"id": "3c182051",
	"params": {
		"db_host": "idb01.mycompany.com",
		"verbose": 1,
		"cust": "Marketing"
	}
}
```

Note that the `params` object can be omitted entirely, or sparsely populated, and any missing properties that are defined in the event are automatically merged in. This allows your API client to only specify the `params` it needs to (including arbitrary new ones).

For using the [Shell Plugin](https://github.com/jhuckaby/Cronicle#built-in-shell-plugin), parameters are passed in as Environment Variables, with the parameter names converted to upper-case.  In the above example it would be `$DB_HOST`, `$VERBOSE`, and `$CUST`.
