### ISSUE TITLE
Scheduler master switch was disabled

### ISSUE THREAD

**Issue by MingqingLi** [jhuckaby/Cronicle#32]
[image](http://blogmingling.oss-cn-shanghai.aliyuncs.com/%E6%9C%8D%E5%8A%A1/screenshot_09.png)

The task does not run after 6:06pm，Memory problem?

**Comment by jhuckaby** [comment]
I am having a very difficult time understanding you.  And I am afraid my response is going to go through another translator, and you won't understand me.  But I will try to help.

Someone (one of your users) clicked the **Scheduler Enabled** Master Switch checkbox by hand, manually.  Meaning, someone clicked right here:

![screenshot_09 png 2554x852](https://user-images.githubusercontent.com/700765/27068530-7356cb44-4fc5-11e7-934e-c22af255edd8.png)

This turns OFF the master switch and STOPS all events from running.  You need to click it AGAIN, to turn it back ON.  It's a toggle switch (on / off / on / off), i.e. a checkbox.  So click it again until it shows a (X) icon.  Then the scheduler is enabled.

Make it look like this:

![screenshot 2017 06 12 23 20 53](https://user-images.githubusercontent.com/700765/27068635-e44b9c76-4fc5-11e7-84f6-f6be6543ad74.png)

This is what you want it to look like.  This means the scheduler is ENABLED, so it is actually running jobs.

I hope this translates properly.

**Comment by MingqingLi** [comment]
Thank you very much for solving my problem！
