### ISSUE TITLE
Broadcast IP address

### ISSUE THREAD

**Issue by Irytacja** [jhuckaby/Cronicle#321]
Hey,
Please add option to choose on which interface/ip addr cronicle will broadcast. For now afair cronicle chooses first available interface and uses it's ip. I would like to have an option to enter IP manually.

**Comment by hobsRKM** [comment]
i tried this setting it to at bottom
hers what i get. Any help?
![image](https://user-images.githubusercontent.com/11420858/91166350-deef0500-e6ef-11ea-874b-9234bd38ecb5.png)

**Comment by Irytacja** [comment]
You have to set it in the first part of config.json (in place where you are
setting things like secret_key etc.)

wt., 25 sie 2020 o 12:57 Yuvaraj Mudaliar <notifications@github.com>
napisał(a):
