### ISSUE TITLE
Update Job Progress

### ISSUE THREAD

**Issue by benk-snowflake** [jhuckaby/Cronicle#325]
Can we update job progress either via the bash plug-in provided with Cronicle or via the API?

We have a fair number of jobs running across multiple AWS regions accessible from a single master endpoint. Some of the database update jobs are quite long, and the users would like to be able to see how far they've got without having to dig too deep into the database itself.

Great product!

Ben

**Comment by jhuckaby** [comment]
Yes, if you are using the [Shell Plugin](https://github.com/jhuckaby/Cronicle#built-in-shell-plugin), see that section of the docs for reporting progress via shell output:

You can still report intermediate progress with the Shell Plugin.  It can accept JSON in the [standard output format](#json-output) if enabled, but there is also a shorthand.  You can echo a single number on its own line, from 0 to 100, with a `%` suffix, and that will be interpreted as the current progress.  Example:

```sh
#!/bin/bash

# Perform some long-running task...
/usr/local/bin/my-task-1.bin || exit 1
echo "25%"

# And another...
/usr/local/bin/my-task-2.bin || exit 1
echo "50%"

# And another...
/usr/local/bin/my-task-3.bin || exit 1
echo "75%"

# And the final task...
/usr/local/bin/my-task-4.bin || exit 1
```

This would allow Cronicle to show a graphical progress bar on the [Home](#home-tab) and [Job Details](#job-details-tab) tabs, and estimate the time remaining based on the elapsed time and current progress.
