### ISSUE TITLE
Feature request: User privileges

### ISSUE THREAD

**Issue by Irytacja** [jhuckaby/Cronicle#327]
Hey,
I've stepped upon a problem that i'd like to solve one or another way.
Whenever i add user with privileges to add/edit/run tasks, he is able to add/edit tasks for every single slave connected to master server, i would like limit this to certain group of servers. 

For example:
User `foo` with privileges to server group `R&D` is able to create/edit/run tasks only on servers that are in `R&D` group.

For now, even if i'll add user with privileges limited to one category, he is able to create task on every single slave.

**Comment by mikeTWC1984** [comment]
It could be easier to create separate cluster for each environment/team.

**Comment by kamcio2603** [comment]
Hello everyone :), we also need ability to set privileges, but we dont want setup cluster (HA... etc) for each team/ENV. Its a waste of resources on virtualization clusters..

**Comment by mikeTWC1984** [comment]
I mean if you have 15 machines in one cluster, break them down. E.g. Have 5 machine cluster for dev/qa, and 10 for production.

**Comment by Irytacja** [comment]
> I mean if you have 15 machines in one cluster, break them down. E.g. Have 5 machine cluster for dev/qa, and 10 for production.

It's still waste of resources on virtualization clusters, i'd have to setup at least 18 additional VMs for cronicle...

**Comment by mikeTWC1984** [comment]
No additional VMs is needed for what I'm suggesting. Same exact set of servers. Just convert some workers into masters, and reassign remaining workers as needed.  You can also run multiple instances of chronicle on same VM (using different port). If your main concern is isolation, that is just simple solution you can use now (I wouldn't expect any new feature added any time soon, until v2 is released)

Regarding your original request - it's totally reasonable and  I think it's not that hard to extend "run" api to do one extra check. But the thing is that user context only exists when you manually execute the job. So it won't prevent user from creating/editing existing jobs and scheduling it on desired machine. So you'd need to implement some extra limitations for editing, which could be confusing if multiple users are meant to edit same jobs.  You can create fork and start experimenting. I can send you a PR for "run" part if needed.

**Comment by piotrkochan** [comment]
@jhuckaby what do You think about that feature request?

**Comment by jhuckaby** [comment]
I like the idea.  I already added a sub-privilege feature for limiting users to specific categories a while back.  It seems relatively straightforward to implement something similar for server groups.  It would need to be enforced both at event save time, and event run time, and enforce both groups, and servers inside those groups (for users who directly target a single server).  We'll need some UI decoration as well, to limit the drop-down menu to only the groups / servers the user has access to.

I do apologize for the lack of updates recently.  I am hard at work on Cronicle 2.0 which is a complete rewrite (actually it's not even called Cronicle anymore!  New name is "Orchestra").  But I'll get to this feature on the Cronicle v1 branch as soon as I can.

Thanks!

**Comment by jhuckaby** [comment]
Fixed in v0.8.49.

**Comment by mannharleen** [comment]
@jhuckaby Recently stumbled upon this project. Looks very promising. When will Orchestra _beta_ be out ?

**Comment by jhuckaby** [comment]
@mannharleen Thank you!  Unfortunately I don't have an ETA, as this is just a hobby project of mine, which I dabble with on nights and weekends.  Orchestra is about 75% complete I believe, and I've been working on it for about a year, so I guess I could estimate sometime in early 2021, if I were to give an estimate.  But I cannot promise anything.

Thank you for your interest!

**Comment by mannharleen** [comment]
Given that you are working on Orchestra now, are you still able to maintain Cronicle? 
How much of overlap exists between Cronicle and Orchestra? It would be good to hear why Orchestra and what makes it better? I assume there are some new/better design decisions that let you to Orchestra, but what are they?
