### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by mihha** [jhuckaby/Cronicle#328]
## Summary

I am trying to use external SMTP server which is using TLS secure method of authentication and port 587

I have to stress out that everything is working on my system except for the email sending

I am using Apache reverse proxy to access my instance by a subdomain on my domain and that works perfectly well

Apache reverse proxy is configured like this

```
<Proxy *>
   Allow from all
</Proxy>
RewriteEngine on

RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
RewriteCond %{QUERY_STRING} transport=websocket    [NC]
RewriteRule /(.*)           ws://localhost:3012/$1 [P,L]

ProxyPass        /socket.io http://localhost:3012/socket.io
ProxyPassReverse /socket.io http://localhost:3012/socket.io

ProxyPass / http://localhost:3012/
ProxyPassReverse /  http://localhost:3012/
```

## Steps to reproduce the problem

Execute cron job and check the Error.log

## Your Setup

This is the part of config.json I created for that purpose

        "email_from": "some_email@my_domain",
        "smtp_hostname": "SMTP_hostname",
        "smtp_port": 587,
        "secret_key": "f5d080bec07c95cb219daaaaaaaaaaaaaaaaaaaaaaaa",

        "mail_options": {
                "secure": true,
                "auth": { "user": "SMTP_username", "pass": "SMTP_password" },
                "connectionTimeout": 10000,
                "greetingTimeout": 10000,
                "socketTimeout": 10000
        },

I also tried to add this to my config.json but didn't help

`"ssl_cert_bypass": true,`

### Operating system and version?

Ubuntu 18.04

### Node.js version?

v14.11.0

### Cronicle software version?

Version 0.8.48

### Are you using a multi-server setup, or just a single server?

I am using single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

I am using filesystem

### Can you reproduce the crash consistently?

Yes, because the system executes the cron jobs correctly. It just can't send an email

## Log Excerpts

[1600335000.433][2020-09-17 11:30:00][my_hostname][25544][Error][error][mail]
[Failed to send e-mail for job: jkf6m50xj02: some_email@some_domain: Error: 139675533911936:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: ]
[{"text":"not really important here"}]

I would be grateful for any kind of information that could lead me to the solution for this email sending problem

**Comment by mikeTWC1984** [comment]
Just google for "ssl3_get_record:wrong version number", it's likely has something to do with proxy, not cronicle

**Comment by mihha** [comment]
I did and nothing valuable came up

That is why I opened this issue. Maybe someone else encountered something like this and can provide some help

**Comment by mihha** [comment]
Thanks! Will check nodemailer node to see if I can find anything in their github pages

BTW, I know that the same SMTP server is working with the same configuration from the same server because I have another node application which is also using nodemailer internally. I don't have this kind of issue with that other application and email sending

**Comment by mihha** [comment]
I have found the solution now that I knew where to look for it

I found in the following nodemailer issue the answer
https://github.com/nodemailer/nodemailer/issues/1172

![image](https://user-images.githubusercontent.com/3791124/93626884-66285380-f9e4-11ea-8d4a-05d16201f32c.png)

If anyone will need this in the future, this is the working config in case you are using SMTP server on port 587

```
"email_from": "some_email@my_domain",
    "smtp_hostname": "SMTP_hostname",
    "smtp_port": 587,
    "secret_key": "f5d080bec07c95cb219dbaaaaaaaaaaaaaaa",

    "mail_options": {
            "secure": false,
            "auth": { "user": "SMTP_username", "pass": "SMTP_password" },
            "connectionTimeout": 10000,
            "greetingTimeout": 10000,
            "socketTimeout": 10000
    },
```

**Comment by mitchdowney** [comment]
@mihha if you set secure to false and use 587, won't that leave your SMTP credentials exposed in your requests?

**Comment by mihha** [comment]
To be honest, I have no idea.

Is there a way to test this?

**Comment by mitchdowney** [comment]
I could be wrong, but I think SMTP 587 is safe as long as the host uses TLS. I ended up setting secure to false, and added `requireTLS=true` to `nodemailer` which is supposed to prevent the SMTP connection if the host doesn't use TLS.

**Comment by mihha** [comment]
I just checked with wireshark what is happening on the network level and you can't see any meaningful payload in the output that would allow you to see the credentials or anything else

Connection to the email server is encrypted and all seems to be ok

**Comment by markusglaetzner** [comment]
@mitchdowney how/where did you add "requiredTLS=true" to nodemailer? Where is the nodemailer-config? Did you get mail notofication over StartTLS (port 587) running successful? Thanks.

**Comment by jhuckaby** [comment]
@markusglaetzner See here for info: https://github.com/nodemailer/nodemailer/issues/527
