### ISSUE TITLE
[Feature Request] More granular user permissions

### ISSUE THREAD

**Issue by mpatel-cpi** [jhuckaby/Cronicle#33]
## Summary
We would like to be able to configure more granular permissions with Cronicle to limit the "damage" a user can do. Example:
- User can edit/run/abort a specific event or a specific "Category"
- User can edit/run/abort the events they "own"

**Comment by jhuckaby** [comment]
Fixed in [Version 0.8.22](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.22).
