### ISSUE TITLE
 [Help / Feature Request] Building a unique job queue

### ISSUE THREAD

**Issue by worldworm** [jhuckaby/Cronicle#34]
Hi there,
I'am using Croncile for a few days right now and if i should not see this feature please close this, sorry.

I know that i can work around this problem. But it is a bit difficult.

I want to build a job queue that executes multiple comands after each other. I know that you can chain command together (also mentioned [here](https://github.com/jhuckaby/Cronicle/issues/19)).
My problem is building this queue, because Cronicle is build on the idea to reshedule jobs and execute it multiple times. I want to execute a job only once and after succesfull execution it should be deleted/deactivated so there is no changce that it could be executed again.

For better understanding i will tell you my usecase.
I have a long lists of urls where i want to download files from.
I build a job for each url (shell script wget).
Now i want to hit the start button that this queue is beeing executed (or will be execute after the master server was startet) and each job is executed after each other. Here it would be great if you could set a multiplier like "Event Concurrency" (i think this is not for this or?) so you can set a multiplier how many active jobs can be per server (cause sometimes the host where you download from is slower than my connenction so that multiple wget comand can run (not the same one!)). 
If there are multiple slave servers that each one is picking the next job from the master (never executing the same job twice)
It would be great if i could add new jobs to the running queue if i found new things.

I hope you can understand this and i didn't overlook this featere.
Thanks for your help

**Comment by jhuckaby** [comment]
Hello there!

Sure thing, you have multiple options to accomplish what you are asking.  First, you should know that events **do not have to be enabled** to be chained together.  Only the *first* one does.

What I mean is, say you have events A, B, and C, and you want them to execute in sequence.  You only need to enable the "A" event.  The B and C events can remain totally disabled in the schedule, but you can still "chain" them together, and they will run when the previous one completes.  An event only needs to be "enabled" (checkbox checked) if it is scheduled to run at a particular date/time.  If the event is a chained event, you can leave it disabled.

If you also want the "A" event to only run once, you can simply select a year, month, day, hour and minute for it.  That way it won't ever repeat.  Alternatively, you can arrange for an event to literally "disable itself" upon completion, by sending back an event update command inside your job.  See here for more details:

https://github.com/jhuckaby/Cronicle#updating-the-event

Does this help?  I do apologize that Cronicle isn't really built for a "queue" of events.  It's really more of a date/time scheduler, like Cron is.

**Comment by worldworm** [comment]
Thanks, that is a great advice.
I didn't thought at disabling the jobs...
