### ISSUE TITLE
How is cronicle determining the hostname?

### ISSUE THREAD

**Issue by remedan-ih** [jhuckaby/Cronicle#342]
## Summary

As per #58 I want to set my hostname to a FQDN so that `web_socket_use_hostnames` uses a name that resolves to the server's public IP.

The FQDN is cronicle.domain.com but cronicle uses just 'cronicle' to identify the server.

The commands `hostname`, `hostnamectl status`, `echo $HOSTNAME`, and `cat /etc/hostname` all output cronicle.domain.com as the hostname.

In `/etc/hosts` I have:

```
127.0.0.1 cronicle.domain.com cronicle localhost
```

## Steps to reproduce the problem

 Add a server in the admin panel. The hostname shows as cronicle where I would expect cronicle.domain.com.

## Your Setup

AWS instance with cronicle behind Nginx. Nginx provides HTTPS. S3 as storage.

### Operating system and version?

Ubuntu 18.04.5

### Node.js version?

8.10.0

### Cronicle software version?

0.8.49

### Are you using a multi-server setup, or just a single server?

Multiple servers

### Are you using the filesystem as back-end storage, or S3/Couchbase?

S3

### Can you reproduce the crash consistently?

Yes

**Comment by mikeTWC1984** [comment]
Should be coming from env variables, below snippet is from source code
```js
// determine server hostname
var hostname = (process.env['HOSTNAME'] || process.env['HOST'] || os.hostname()).toLowerCase();
```
You probably need to remove/add that server after updating $HOSTNAME variable

When I run it in container and specify --hostname parameter as fdqn, it works as expected (I see fdqn in server list in cronicle)

**Comment by remedan-ih** [comment]
I tried the following:

1. stop cronicle on the server
2. remove the server in the admin panel
3. start cronicle again
4. add the server in the admin panel

The server still shows up as 'cronicle'.

But I noticed something else. In the log files the server gets labeled correctly as 'cronicle.domain.com'. This seems to indicate that cronicle is able to get the correct hostname.

Is it possible that the old hostname is cached somehow?

**Comment by pyrou** [comment]
if that can help I used a.deep.long.domain.tld as hostname, and on server list it only displayed me `a.deep.long`. But on hover, it shows me the complete domain.

**Comment by remedan-ih** [comment]
@pyrou Thank you. I didn't notice this before.

I first set the hostname to 'cronicle' then changed it to 'cronicle.domain.com'. Since on the Servers page it showed as 'cronicle' both before and after I made this change, I didn't realize something changed.

It does actually work now.

The UI is a bit misleading, though. As under Hostname it shows a shortened value (unless you hover). But for most things you need the full hostname. E.g. the Primary Group regexp.
