### ISSUE TITLE
different log views are empty

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [jhuckaby/Cronicle#343]
## Summary

since a couple of days my cronicle installation doesn't show any log entries in different log views:
- server activity log (#Admin?sub=activity)
- jobs completed (#History)

Only if I filter the completed job list for a special event, the log entries are shown.

## Steps to reproduce the problem

- Login with admin account
- Open server activity log -> empty
- Switch to Completed tab -> emtpy

## Your Setup
3 server (master, slave, worker)

### Operating system and version?
Ubuntu 18.04

### Node.js version?
v.8.10

### Cronicle software version?
0.8.50
the problem also exists in 0.8.49 (I upgraded to .50 because I hoped to solve the problem)

### Are you using a multi-server setup, or just a single server?
-multi server (3)

### Are you using the filesystem as back-end storage, or S3/Couchbase?
- filesystem

### Can you reproduce the crash consistently?
- no crash
- problem is permanent

## Log Excerpts
No errors or warnings in the log files while loading the problematic pages (debuglevel was set to 9).

Thanks for developing such a great peace of software. ;-)

**Comment by mikeTWC1984** [comment]
Is it persistent problem? Some times I see that main page doesn't load  unless refreshed few times, I guess that's some browser caching  stuff. If you open browser dev tools, then go to network tab and hit that history page, do you see empty json in response?
![image](https://user-images.githubusercontent.com/31977106/97651544-be666280-1a32-11eb-8cb9-48842468962f.png)

**Comment by dheise-rheinenergie-trading-com** [comment]
Persitent over multiple reboots and upgrade from .49 to .50. The JSON is emtpy for both pages (history and activity):
![image](https://user-images.githubusercontent.com/73586581/97671600-d5d03a80-1a88-11eb-8e5f-57b4d30d305c.png)

![image](https://user-images.githubusercontent.com/73586581/97671580-cbae3c00-1a88-11eb-9466-3830f2d4ac05.png)

**Comment by jhuckaby** [comment]
I can't say I've ever seen this one before.  It sounds like you may have some kind of corruption in the data which powers those tables.

At this point I would recommend an export / delete / import.  See [this section of the docs](https://github.com/jhuckaby/Cronicle#data-import-and-export) for details, specifically to understand what is and isn't included in the export / import.

So the procedure would be:

1. Stop Cronicle on all your servers: `/opt/cronicle/bin/control.sh stop`
2. Export all your data from the master: `/opt/cronicle/bin/control.sh export /path/to/cronicle-data-export.txt`
3. Backup the raw data dir just in case: `tar zcf /path/to/backup.tar.gz /opt/cronicle/data`
4. Delete all local data: `rm -rf /opt/cronicle/data/*`
5. Import your data from the export: `/opt/cronicle/bin/control.sh import /path/to/cronicle-data-export.txt`
6. Start Cronicle on all servers: `/opt/cronicle/bin/control.sh start`

You said you have a master and a slave server (new terminology: primary and secondary), but you are using the local filesystem.  How are they sharing data?  Are you using NFS?

**Comment by dheise-rheinenergie-trading-com** [comment]
Too bad that a "rm -rf" is the only solution. So I lose all my job logs, which are currently still easily accessible.
The primary and the two secondary servers share the data directory via NFS.

**Comment by dheise-rheinenergie-trading-com** [comment]
Today I did the export, stop, delete data, import, start procedure with success. Logs are now shown again. Thanks!
