### ISSUE TITLE
feature: add network/disk monitoring

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#344]
I think it would be very useful to track how network is utilized, especially if multiple jobs are running simultaneously. Same about disk read/write. I guess that could be displayed on the main page when jobs are running (along with progress bar). 

The other thing worth to monitor would be the size of data and logs folders (if filesystem is used), that could be placed in server stats section.

**Comment by jhuckaby** [comment]
Check out my [Performa](https://github.com/jhuckaby/performa) app.  It does exactly this.  In Cronicle v2.0 (a.k.a "Orchestra"), Performa will be integrated directly into the web app.

**Comment by mikeTWC1984** [comment]
Wow, I love it )  Are you going to merge it into one product, or chronicle will just include "Satellite" functionality? 
Wondering - is there any plan to add on demand real time monitoring,  updating data every few seconds vs 1 minute and without saving those results to disk (ala htop)? 
Anyway, I was playing with that tool for a few day, I guess it exceeds what I was looking for, so I'm closing the issue

**Comment by jhuckaby** [comment]
Thanks!  Yeah, it's all going to be merged into one single product.  The "satellite" installation will handle both Cronicle slave operations and Performa server monitoring.

Good idea about the htop-style real-time readings.  I was planning on having a "scope" feature which would enable it on a server-by-server basis, so it would only start grabbing readings at that super high frequency if someone was watching it.
