### ISSUE TITLE
Question: Best place to skip public holidays

### ISSUE THREAD

**Issue by welaunchcn** [jhuckaby/Cronicle#345]
All of my jobs only need to be run on working days and all public holidays need to be skipped. Curruently I'm adding checks at the begining of every job. I'm also considering doing the check in a custom plugin. Is there a better place for this requirement?

**Comment by jhuckaby** [comment]
Hello!  Yup, a [Plugin](https://github.com/jhuckaby/Cronicle#plugins) is the best way to implement this.  Just have it be a light wrapper around an exec call, which pre-checks for public holidays, then have each of your events select that Plugin.

Good luck!
