### ISSUE TITLE
feature: webhook notification - adopt for slack/messaging

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#346]
It seemed to be simple change to allow webhook notification to send messages to slack or any other comparable tool
Basically need to add api token to "Authorization" header (token could be stored in config) and attach custom payload. Below is a sample request for slack, but it should be about the same thing for most other messengers

```http
POST https://slack.com/api/chat.postMessage
Content-type: application/json
Authorization: Bearer xoxb-your-token
{
  "channel": "YOUR_CHANNEL_ID",
  "text": "Hello world :tada:"
}
```

**Comment by mikeTWC1984** [comment]
Actually I see it's already preconfigured for slack, although I don't see where to put api token, any suggestion (I assume it comes as header)?

**Comment by jhuckaby** [comment]
Ugh, I do apologize -- Slack has totally changed their API.  Back when I first wrote Cronicle in 2015, you could post a message to Slack with nothing except a URL (the auth token was on the URL itself as a query string parameter).  I see they've changed it nowadays to require that you send specific HTTP request headers.

I will add support for this in the next version!  Thanks for catching this.

**Comment by jhuckaby** [comment]
Fixed in [v0.8.51](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.51).  Added new blurb to docs:

To include custom HTTP request headers with your web hook, append them onto the end of the URL using this format: `[Header-Name: Header Value]`.  Make sure to include a space before the opening bracket.  Example URL:

```
https://slack.com/api/chat.postMessage [Authorization: Bearer xoxb-your-token]
```

(This is the best I could do on short notice.  Obviously the best thing would be to redesign the UI to provide the user with a nice custom HTTP header editor widget for every web hook, but this should suffice.)

**Comment by mikeTWC1984** [comment]
Thanks for the quick turn around! One more useful improvement - slack and other messenger can read payload data form url, e.g.  https://slack.com/api/chat.postMessage?text=hello&channelid=mychannel. However this seemed to override data sent by cronicle. That would be very useful to  merge both sources. This would allow user to specify recipient (channel) for each webhook

**Comment by jhuckaby** [comment]
Sorry, I'm not sure if I understand you.  Apologies, but I have not used the Slack API in several years.  Are you saying I should take the user's web hook URL, *parse the URL and strip off the query string from it*, then merge those query string parameters back into the JSON POST data that is sent along with the web hook request?

So basically, if the user set their web hook to this URL:

```
https://slack.com/api/chat.postMessage?text=hello&channelid=mychannel
```

I would parse it and strip the query string, ending up with this base URL:

```
https://slack.com/api/chat.postMessage
```

and these parameters:

```json
{
    "text": "hello",
    "channelid": "mychannel"
}
```

And then take the parameters and shallow-merge them into the JSON POST data, replacing any existing parameters that Cronicle itself added?

**Comment by mikeTWC1984** [comment]
Correct. More clear example - if I use this as a webhook, I'm receiving  the message "hello":
https://slack.com/api/chat.postMessage?text=hello&channelid=mychannel
I guess this means text=hello&channelid=mychannel is used instead of body generated by cronicle.
Ideally I want to use https://slack.com/api/chat.postMessage?channelid=mychannel as enpoint (specifying channel) but use text and other values from cronicle (in other words to merge it).

**Comment by mikeTWC1984** [comment]
Btw, this API is very generic, and can be adopted for any other messaging tool, not just Slack

**Comment by mikeTWC1984** [comment]
hm, looks like that update also needs form validation update, I'm getting this error if adding header

![image](https://user-images.githubusercontent.com/31977106/98457520-3a108f80-2156-11eb-9e13-6e9e2c7ef7e0.png)

**Comment by jhuckaby** [comment]
Fixed in [v0.8.52](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.52), thank you!!!

**Comment by jhuckaby** [comment]
Okay @mikeTWC1984, so regarding the query string merge request, I really cannot mutate the user's web hook URL and merge those query parameters into the JSON data.  The reason is, I would break several live Cronicle installations, including mine at work.  I use web hooks extensively, and in my case the query string parameters **must** stay put -- they cannot be moved or copied into the JSON data.  But I have another suggestion that might satisfy your request:

I could change the syntax of the URL substitution to allow both request headers **and** JSON data to be merged in.  The new syntax would look like this:

```
https://slack.com/api/chat.postMessage [header: Authorization: Bearer xoxb-your-token] [data: channelid: mychannel]
```

How does that sound?

**Comment by mikeTWC1984** [comment]
That sounds good! 
I tried to use that header feature, somehow it didn't  work, I'm checking if that's something on my end or cronicle

**Comment by jhuckaby** [comment]
FYI, If you're trying to use the Slack API, please note that it doesn't require any authorization headers.  The OAuth thing is totally optional.  Just grab the web hook URL for your Slack "app" and it has the auth token built right into it -- no header required:

<img width="704" alt="Screen Shot 2020-11-08 at 9 17 24 PM" src="https://user-images.githubusercontent.com/700765/98502820-d9da2600-2207-11eb-8402-ed3a67a9c796.png">

Ignore the entire OAuth section.  Just grab the web hook URL at the very bottom of the install app page.  I just tested it now and it works great:

<img width="681" alt="Screen Shot 2020-11-08 at 11 10 36 AM" src="https://user-images.githubusercontent.com/700765/98502845-f1191380-2207-11eb-8528-b2889a34de14.png">

**Comment by jhuckaby** [comment]
Released [v0.8.53](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.53) with new web hook URL syntax:

```
https://slack.com/api/chat.postMessage [header: Authorization: Bearer xoxb-your-token] [data: channelid: mychannel]
```

But again, I don't think this is necessary if you use a Slack "app" and their web hook URL system, which has all the auth stuff built into the URL, and is also preset to post to a specific Slack channel already.

Good luck!

**Comment by mikeTWC1984** [comment]
OK, I guess that slack channel webhook is the best solution (I was using bot so nd messed that).
Your updates are still very useful (for non slack integrations). The only thing  - I couldn't get it to work :)

Below are snippets for js (doesn't work) and curl (works). AM I missing something?

```js
var PixlRequest = require('pixl-request');
var request = new PixlRequest();
var url = "https://slack.com/api/chat.postMessage?channel=mychannel&text=test [Authorization: Bearer xoxb-...]"
request.get(url, (e,r,d)=> console.log(d))
```

```bash
curl -X POST -H "Authorization: Bearer xoxb-..." "https://slack.com/api/chat.postMessage?channel=mychannel&text=test"
```

**Comment by jhuckaby** [comment]
I'm so sorry for the confusion @mikeTWC1984 -- the syntax has changed.  Upon your request, it now supports both inline headers **and inline data properties**, both specified on the URL, so I had to add a special "prefix" for each type.  For headers, you now need a `header:` prefix inside the brackets like this:

```
[header: Authorization: Bearer xoxb-your-token]
```

For data properties the prefix is `data:` like this:

```
[data: channelid: mychannel]
```

So your example above should be changed to this:

```js
var PixlRequest = require('pixl-request');
var request = new PixlRequest();
var url = "https://slack.com/api/chat.postMessage?channel=mychannel&text=test [header: Authorization: Bearer xoxb-...]"
request.post(url, (e,r,d)=> console.log(d))
```

That should work 😊

**Comment by mikeTWC1984** [comment]
OK, there is some progress, but still it's not properly functioning on my end.
It can read header from that placeholder but only if url contain text and text is the last parameter:
```
https://slack.com/api/chat.postMessage?channel=mychannel&text=mike [header: Authorization: Bearer ...]
```
But the message I receive contains that header block too. So looks like text value and header values get combined, (however header gets detected)

below url doesn't work (returning empty string)
```
https://slack.com/api/chat.postMessage? [header: Authorization: Bearer ...] [data: channel: mychannel]
```

**Comment by jhuckaby** [comment]
Huh, how strange.  Damn, okay, well, I'll get back to this when I can.  Unfortunately I have to jump over to my day job.  I'll try to take another look at this on the weekend.

**Comment by mikeTWC1984** [comment]
Sure. I guess slack would be used in 99% cases, so it's not a critical issue since that direct webhook can be used
To close the topic, some more user experience feedback, maybe something to consider for v2:
1. It's a bit hard to read default slack feed. I'd add some emoji/hyperlinks to make it easier for brain to scan it. E.g. :
```
text=:heavy_check_mark: Job is completed <http://example.com|see more details>
```
![image](https://user-images.githubusercontent.com/31977106/98616256-7107b200-22ca-11eb-95b5-4fb53b599388.png)
2. I guess most of the people would like to be pinged only in case of error (not for each job status change). It might be useful for users to specify **error-only** slack channel
3. For that custom webhook syntax (header/data), new line could be a good separator. It would be more convenient to fill it in a text box, rather than single line
```
 https://slack.com/api/chat.postMessage?
 [header: Authorization: Bearer ...] 
 [data: channel: mychannel]
```
Or maybe even standard request string?
```
POST https://slack.com/api/chat.postMessage
Content-type: application/json
Authorization: Bearer xoxb-your-token
{
  "channel": "YOUR_CHANNEL_ID",
  "text": "Hello world :tada:"
}
```

**Comment by mikeTWC1984** [comment]
One more idea - separate slack channel can be assigned to report  stuff from Activity Log, that would be ideal "error only" channel I mentioned above (since it covers both errors and server changes)

 Played a bit with slack/cronicle "markdown" to get a bit more fun feed, luckily those are not overlapping. I think you should add date/time placeholder  (e.g. [datetime] ), since slack combines messages from same minute.

```json
"web_hook_text_templates": {  

  "job_start": ":rocket: *[event_title]* started on [hostname] @[datetime] <[job_details_url]| more details>",
  "job_complete": ":heavy_check_mark: *[event_title]* completed successfully on [hostname] @[datetime] <[job_details_url]| more details>",
  "job_failure": ":x: *[event_title]* failed on [hostname]:\nError [code]: [description]\n <[job_details_url]| more details>",
  "job_launch_failure": ":boom: Failed to launch *[event_title]*:\n[description]\n<[edit_event_url]| more details>"
}
```

**Comment by mikeTWC1984** [comment]
@jhuckaby how does failed jobs get into Activity Log? I see all other events use LogActivity function, but I can't find this route for job failures. I'm experimenting with routing activity log to slack channel, which seemed to be a simple addition to that LogActivity function, and I also want to change errors caused by missing plugin/permission/shebang to be "job_launch_failure" rather just job_failure.

**Comment by mikeTWC1984** [comment]
OK, I see how failures are logged:
https://github.com/jhuckaby/Cronicle/blob/15ba50f4a59e26de0b9a8b9b9a5f24972fa502a0/lib/job.js#L1302-L1307
I guess it could be replaced with something like below for consistency
```js
if (job.code > 0 )  self.logActivity('job_failure', {job: stub} );
```

I was playing with activity log over the weekend. I see event enabling/disabling is indicated as "event_update", which I
d change to separate category (seemed to be an easy change). 
I also realized "Incoming Webhook" is a very common term. Looks like any messaging platform would have it, and it would use "text" key in payload to indicate the message. So it shouldn't be a problem to use cronicle web-hooks on non-Slack messengers, the only problem is to set message with markdown (seem to be different on each platform).
Below is a snippet to recreate "Activity Log" in slack channel if anyone interested (it could be plugged into LogActivity function definition to start)

```js
		if (this.server.config.get('admin_web_hook')) {

			var msg = 'ℹ️ ' + action 
			var baseUrl = this.server.config.get('base_app_url');

			try {
				
				var modBy = `\n    _${data.username}@${data.ip} - ${(new Date()).toLocaleTimeString()}_`

				switch (action) {

					// categories
					case 'cat_create':
						msg = `📁 New category created: *${data.cat.title}*  ${modBy}`;
						break;
					case 'cat_update':
						msg = `📁 New category updated: *${data.cat.title}*  ${modBy}`;
						break;
					case 'cat_delete':
						msg = `📁 New category deleted: *${data.cat.title}*  ${modBy}`;
						break;

					// groups
					case 'group_create':
						msg = `🖥️ Server group created: *${data.group.title}*  ${modBy}`
						break;
					case 'group_update':
						msg = `🖥️ Server group updated: *${data.group.title}*  ${modBy}`;
						break;
					case 'group_delete':
						msg = `🖥️ Server group deleted: *${data.group.title}*  ${modBy}`;
						break;

					// plugins
					case 'plugin_create':
						msg = `🔌 Plugin created: *${data.plugin.title}*  ${modBy}`;
						break;
					case 'plugin_update':
						msg = `🔌 Plugin updated: *${data.plugin.title}*  ${modBy}`;
						break;
					case 'plugin_delete':
						msg = `🔌 Plugin deleted: *${data.plugin.title}*  ${modBy}`;
						break;

					// api keys
					case 'apikey_create':
						msg = `🔑 New API Key created: *${data.api_key.title}* ${('' + data.api_key.key).substr(0, 4) + '******'}  ${modBy}`;
						//msg += `<${baseUrl}/#Admin?sub=edit_api_key&id=${data.api_key.id} | Edit Key>`;
						break;
					case 'apikey_update':
						msg = `🔑 API Key updated: *${data.api_key.title}*  ${('' + data.api_key.key).substr(0, 4) + '******'}  ${modBy}`;
						//msg += `<${baseUrl}/#Admin?sub=edit_api_key&id=${data.api_key.id} | Edit Key>`;
						break;
					case 'apikey_delete':
						msg = `🔑 API Key deleted: *${data.api_key.title}*  ${('' + data.api_key.key).substr(0, 4) + '******'}  ${modBy}`;
						break;

					// events
					case 'event_create':
						msg = `🕘 New event added: *${data.event.title}* `;
						msg += `<${baseUrl}/#Schedule?sub=edit_event&id=${data.event.id} | Edit Event >  ${modBy}`;
						break;
					case 'event_update':
						msg =  `🕘 Event updated: *${data.event.title}* `;
						msg += `<${baseUrl}/#Schedule?sub=edit_event&id=${data.event.id} | Edit Event >  ${modBy}`;
						break;
					case 'event_delete':
						msg = `🕘 Event deleted: *${data.event.title}*  ${modBy} `;
						break;
					case 'event_enabled':
						msg = `ℹ️ Event *${data.event.title}* was enabled `;
						msg += `<${baseUrl}/#Schedule?sub=edit_event&id=${data.event.id} | Edit Event >  ${modBy}`;
						break;
					case 'event_disabled':
						msg = `ℹ️ Event *${data.event.title}* was disabled `;
						msg += `<${baseUrl}/#Schedule?sub=edit_event&id=${data.event.id} | Edit Event >  ${modBy}`;
						break;

					// users
					case 'user_create':
						msg = `👤 New user account created: *${data.user.username}* (${data.user.full_name}) `;
						msg += `<${baseUrl}/#Admin?sub=edit_user&username=${data.user.username} | Edit User>  ${modBy}`;
						break;
					case 'user_update':
						msg = `👤 User account updated: *${data.user.username}* (${data.user.full_name}) `;
						msg += `<${baseUrl}/#Admin?sub=edit_user&username=${data.user.username} | Edit User>  ${modBy}`;						
						break;
					case 'user_delete':
						msg = `👤 User account deleted: *${data.user.username}* (${data.user.full_name})  ${modBy}`;
						break;
					case 'user_login':
						msg = "👤 User logged in: *" + data.user.username + "* (" + data.user.full_name + ") ";
						break;

					// servers

					case 'server_add': // current
						msg = '🖥️ Server ' + (data.manual ? 'manually ' : '') + 'added to cluster: *' + data.hostname + '*  ' + modBy;
						break;

					case 'server_remove': // current
						msg = '🖥️ Server ' + (data.manual ? 'manually ' : '') + 'removed from cluster: *' + data.hostname + '*  ' + modBy;
						break;

					case 'server_manager': // current
						msg = '🖥️ Server has become manager: *' + data.hostname + '*'
						break;

					case 'server_restart':
						msg = '🖥️ Server restarted: *' + data.hostname + '*  ' + modBy;
						break;
					case 'server_shutdown':
						msg = '🖥️ Server shut down: *' + data.hostname + '*  ' + modBy;
						break;

					case 'server_disable':
						msg = '🖥️ Lost connectivity to server: *' + data.hostname + '*';
						break;
					case 'server_enable':
						msg = '🖥️ Reconnected to server: *' + data.hostname + '*';
						break;

					// jobs
					case 'job_run':
						msg = '📊 Job *#' + data.id + '* (' + data.title + ') manually started ';
						msg += ` <${baseUrl}/#JobDetails?id=${data.id} | Job Details> `;
						break;
					case 'job_complete':
						if (!data.code) {
							msg = '📊 Job *#' + data.id + '* (' + data.title + ') on server *' + data.hostname.replace(/\.[\w\-]+\.\w+$/, '') + '* completed successfully';
						}
						else {
							msg = '📊 Job *#' + data.id + '* (' + data.title + ') on server *' + data.hostname.replace(/\.[\w\-]+\.\w+$/, '') + '* failed with error: ' + encode_entities(data.description || 'Unknown Error').replace(/\x1B\[[0-?]*[ -/]*[@-~]/g, "");
						}
						msg += ` <${baseUrl}/#JobDetails?id=${data.id} | Job Details>`;
						break;
					case 'job_delete':
						msg = '📊 Job *#' + data.id + '* (' + data.title + ') manually deleted';
						break;

					case 'job_failure':  // xxx
						var msg = `❌ Job *${data.job.id} 📊 (${data.job.event_title})* failed:\n ${data.job.description} \n`;
						msg += `<${this.server.config.get('base_app_url')}/#JobDetails?id=${data.job.id} | More details>`;
					    break;

					// scheduler
					case 'state_update':
						msg = 'ℹ️ Scheduler manager switch was *' + (data.enabled ? 'enabled' : 'disabled') + '*  ' + modBy;
						break;

					// errors
					case 'error':
						msg = '❌ Error: ' + data.description
						break;

					// warnings
					case 'warning':
						msg = '⚠️ ' + data.description
						break;

				}
			} catch (err) {
				self.logDebug(9, "Admin Web Hook Message failed: " + err);
			}

			this.request.json(this.server.config.get('admin_web_hook'), { text: msg }, function (err, resp, data) {
				// log response
				if (err) self.logDebug(9, "Admin Web Hook Error: " + err);
				//else self.logDebug(9, "Admin Web Hook Response: HTTP " + resp.statusCode + " " + resp.statusMessage);
			});

		}
```
