### ISSUE TITLE
Wrong timezone offset for America/Sao_Paulo

### ISSUE THREAD

**Issue by eitchtee** [jhuckaby/Cronicle#356]
## Summary

Due to DST settings, America/Sao_Paulo timezone has an offset of -2 GTM/UTC. But recently DST has been phased out on Brazil, meaning it should have an offset of -3 GTM/UTC, which means tasks fire one hour earlier than they should on local time.

This seems to be a problem with moment-timezone, that can be fixed by [updating to the latest version](https://github.com/moment/moment-timezone/issues/797).

For anyone with the same problem, I've found an workaround by setting the task's timezone to America/Bahia, which isn't affected by the wrong configuration, but it's less than ideal.

## Steps to reproduce the problem

Using the latest version of Cronicle, setup a task using America/Sao_Paulo timezone.

### Operating system and version?

Ubuntu 20.04.1 LTS

### Node.js version?

v14.15.1

### Cronicle software version?

Version 0.8.53

### Are you using a multi-server setup, or just a single server?

Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

**Comment by jhuckaby** [comment]
Fixed in [v0.8.54](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.54).  Thanks!
