### ISSUE TITLE
Feature: Pushbullet notifications

### ISSUE THREAD

**Issue by swetoast** [jhuckaby/Cronicle#357]
Love this recently installed it and ditched old cronjobs in favor for this but i dont want to use smtp i wanna use pushbullet instead been using it on my old bashscripts thats running but would love if it is a native feature

https://docs.pushbullet.com/

**Comment by mikeTWC1984** [comment]
Check this for alternatives

You can use webhook notification for messengers supporting Incoming Webhooks (l guess most of them support it), which is basically auth-less endpoint you can post your data to. Looks like it's not an option for pushbullet thogh.
The latest version supposed to support adding custom headers (like oauth token) but somthing doesn't work right
You can check this issue:
https://github.com/jhuckaby/Cronicle/issues/346

**Comment by swetoast** [comment]
Yeah ok thats one way to absolutely do it just a bit messy but it works, tnx

**Comment by swetoast** [comment]
Still want this one to stand since it can be done better then the workaround
