### ISSUE TITLE
Real time STDOUT and STDERR logs for scripts

### ISSUE THREAD

**Issue by nashok1226** [jhuckaby/Cronicle#364]
Hi All,

Its a query rather than an issue.

My Script prints various messages in STDOUT and STDERR.  These logs are piped into job log after the script is finished or I think some predefined size is kept in RAM and written after into log (Guess 32KB ??). But I need the STDOUT immediately its printed should be appearing in job event log to help with real time monitoring.

Thanks
Ashok

**Comment by mikeTWC1984** [comment]
That's already implemented. When job is in progress you should be able to view live log. You might get error if you don't have direct connection to the server running job (e.g. if you under  proxy or docker)

**Comment by jhuckaby** [comment]
One thing I wanted to add here.  For many languages, STDOUT / STDERR are "buffered" and only dump after each 32K or so.  You'll need to set the STDIO filehandles / pipes to be "autoflush", or flush them after every print.  Check your language documentation for how to do this.

**Comment by nashok1226** [comment]
@jhuckaby Thanks for your help. It is indeed buffer. I have fixed it. thanks for comment and wonderful application
