### ISSUE TITLE
Cronicle doesn't archive logs

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [jhuckaby/Cronicle#374]
## Summary

My 3 Cronicle servers are not able to archive their log files. Cronicle is running with root privileges. The target directory exists on all 3 cronicle servers and is writeable.

root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01# ps -ef | grep Cronicle
root      41233  51997  0 09:52 pts/1    00:00:00 grep --color=auto Cronicle
root     105719      1  1 Jan28 ?        01:34:19 Cronicle Server
root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01# pwd
/mnt/dua/cronicle/log-archive/rtmone01
root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01# ls -la
total 0
drwxrwxrwx 2 root ret-dua 0 Feb  1 09:52 .
drwxrwxrwx 2 root ret-dua 0 Jan 28 14:07 ..
root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01# touch testfile
root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01# ls
testfile
root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01# rm testfile
root@rtmone01:/mnt/dua/cronicle/log-archive/rtmone01#

btw: the target directory is a mounted nas ressource.

## Steps to reproduce the problem

Wait till 00:00 - check the logs and I find messages like this:

[1611874801.126][2021-01-29 00:00:01][rtmone01][105719][Error][error][maint][Failed to archive logs: Error: Failed to make directories for: /mnt/dua/cronicle/log-archive/rtmone01/2021/01/28/Cronicle-2021-01-28.log.gz: Error: ENOENT: no such file or directory, mkdir '/mnt/dua/cronicle/log-archive/rtmone01/2021/01/28'][]

## Your Setup
Cronicle 0.8.53 running on 3 servers.

### Operating system and version?
Ubuntu 18.04

### Node.js version?
v.8.10

### Cronicle software version?
0.8.53

### Are you using a multi-server setup, or just a single server?
multi-server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
file system

### Can you reproduce the crash consistently?
not really a crash, but reproduciable

## Log Excerpts
[1611874801.126][2021-01-29 00:00:01][rtmone01][105719][Error][error][maint][Failed to archive logs: Error: Failed to make directories for: /mnt/dua/cronicle/log-archive/rtmone01/2021/01/28/Cronicle-2021-01-28.log.gz: Error: ENOENT: no such file or directory, mkdir '/mnt/dua/cronicle/log-archive/rtmone01/2021/01/28'][]

**Comment by mikeTWC1984** [comment]
Try to touch/ls via shellplug. Probably that mounted dir is not visible by node process. Are you mounting it via fstab?

**Comment by dheise-rheinenergie-trading-com** [comment]
The mountpoint should be readable und writeable for cronicle, because the cronicle data directory is also stored on this nas ressource.
Test:
![image](https://user-images.githubusercontent.com/73586581/106716232-7c832480-65fe-11eb-9080-4c69b0508afc.png)

Result: works
![image](https://user-images.githubusercontent.com/73586581/106716242-7f7e1500-65fe-11eb-97a8-663eb116686d.png)

Mountpoint is defined in /etc/fstab
//rtnas01p/ret_dua$ /mnt/dua cifs credentials=/root/.smbcredentials_xrtNasOperations,vers=3.0,mfsymlinks,uid=0,gid=1001,file_mode=0777,dir_mode=0777 0  0

**Comment by mikeTWC1984** [comment]
OK. That error comes from mkdirp, it cannot create directory by some reason
https://github.com/jhuckaby/pixl-logger/blob/master/logger.js#L432
Can you share these configs from your config.json? Also where did you installed cronicle, is it /opt/cronicle or that mnt drive?
	"log_dir": "logs",
	"log_filename": "[component].log",
	"log_columns": ["hires_epoch", "date", "hostname", "pid", "component", "category", "code", "msg", "data"],
	"log_archive_path": "logs/archives/[yyyy]/[mm]/[dd]/[filename]-[yyyy]-[mm]-[dd].log.gz",
	"log_crashes": true,

**Comment by dheise-rheinenergie-trading-com** [comment]
cronicle itself is installed on the local directory /opt/cronicle. The data directory is shared accross 3 servers through the mounted nas directory.

my log config:

root@rtmone01:/opt/cronicle/conf# grep "log_" config.json
        "log_dir": "logs",
        "log_filename": "[component].log",
        "log_columns": ["hires_epoch", "date", "hostname", "pid", "component", "category", "code", "msg", "data"],
        "log_archive_path": "/mnt/dua/cronicle/log-archive/rtmone01/[yyyy]/[mm]/[dd]/[filename]-[yyyy]-[mm]-[dd].log.gz",
        "log_crashes": true,
        "job_log_max_size": 0,
                "log_event_types": { "get": 0, "put": 0, "head": 0, "delete": 0, "expire_set": 0 },
root@rtmone01:/opt/cronicle/conf#

**Comment by mikeTWC1984** [comment]
OK. Try to run snippet below as shell plug, see if it works. Actually "no such file or directory" error doesn't make much sense in this context, probably mkdirp is somehow broken.

```js
#!/usr/bin/env node

const Tools = require('/opt/cronicle/node_modules/pixl-tools');

Tools.mkdirp('/mnt/dua/cronicle/log-archive/rtmone01/2022/01/28', (e) => { 
   if(e) return console.log(e)
   console.log('success')
});
```

**Comment by dheise-rheinenergie-trading-com** [comment]
seems to be. the error message below:

# Job ID: jkkqjrc0f08
# Event Title: test ls mountpoint
# Hostname: rtmone01
# Date/Time: 2021/02/04 08:37:16 (GMT+1)

{ Error: ENOENT: no such file or directory, mkdir '/mnt/dua/cronicle/log-archive/rtmone01/2022/01/28'
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/mnt/dua/cronicle/log-archive/rtmone01/2022/01/28' }

# Job completed successfully at 2021/02/04 08:37:17 (GMT+1).
# End of log.

The function seems not able to create directory structures with subfolders. The folder /mnt/dua/cronicle/log-archive/rtmone01 is existing already. So Cronicle have to create only 2022/01/28, which doesn't work. If I shorten the folder to /mnt/dua/cronicle/log-archive/rtmone01/2022 it works.

# Job ID: jkkqjv85l2c
# Event Title: test ls mountpoint
# Hostname: rtmone01
# Date/Time: 2021/02/04 08:40:18 (GMT+1)

success

# Job completed successfully at 2021/02/04 08:40:18 (GMT+1).
# End of log.

After then, I can create the folder /mnt/dua/cronicle/log-archive/rtmone01/2022/01 without any problems.

The mkdir seems to have a problem with subdirectories.

**Comment by mikeTWC1984** [comment]
OK, I guess latest Tools is using native mkdir with recursive option which is not supported by your node version. Try upgrade to LTS (12) or at least 10.

**Comment by dheise-rheinenergie-trading-com** [comment]
That

**Comment by dheise-rheinenergie-trading-com** [comment]
I upgraded NodeJS from 8 to 12. Now the directories are created without any problems. Thanks for your support.

**Comment by jhuckaby** [comment]
Thank you, @mikeTWC1984, for helping with this one.  I guess I should make Cronicle "require" Node 12+.
