### ISSUE TITLE
http url-plugin json custom params not passed on to python flask webservice

### ISSUE THREAD

**Issue by marcel-vermeulen** [jhuckaby/Cronicle#375]
## Summary

When using url-plugin to pass custom parameters to a python flask based api end-point, the parameters json format is not passed on in correct json format it seems. When adding the same data to POST Data in proper json format ( using " and not ' ) it works.  It seems the issue is related to the json formatting that is output to the receiving api endpoint, not using " .
Not sure if I'm missing something. Apologies if this was already posted, I tried to search for relevant issues.

## Steps to reproduce the problem

Run a local python flask web service that simply accepts an http post request with content-type : 'application/json' header, and then prints out the json content and returns a {'complete':1} response.

1. Create new plugin based on HTTP Request example.
2. Add url to the python flask webservice, with POST method.
3. Add one custom parameter to test, e.g. "hostname" .

Submit a new Event using this plugin, and run On Demand.
Result: the http request is rejected with a 500error,  and it seems the json data is not included in the params{}

Python error:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Researching this error indicates the json passed through from the originating request is not properly formated.

## Your Setup

Ubuntu Linux based machine for small development work only. Standard implementation.

### Operating system and version?

Ubuntu 20.04

### Node.js version?

v14.15.4

### Cronicle software version?

0.8.56

### Are you using a multi-server setup, or just a single server?
SIngle server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem
### Can you reproduce the crash consistently?
Yes
## Log Excerpts

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

-->

Performance Metrics: scale=1000&total=1413.974&dns=11.776&send=0&connect=249.058&wait=627.21&receive=507.412&c_bytes_sent=172&c_bytes_received=24233

Job failed at 2021/02/11 13:33:52 (GMT+2).
Error 500: HTTP 500 INTERNAL SERVER ERROR
End of log

**Comment by mikeTWC1984** [comment]
Can you make a screenshot of your event parameters?
Did you try to test this endpoint with curl? Quite possible this is just related to this specific endpoint, e.g. request may contain invalid parameters/headers.
You can also debug it by sending request to cronicle. E.g. create shellplug event like this:
```shell
#!/usr/bin/env bash
cat - 
```
If you have or can install jq (bash json parser) then better do "cat - |  jq"
Then create API key that can run events
Then in your ulr plugin replace flask endpoint with url below to invoke this new event:
http://localhost:3012/api/app/run_event?id=EVENTID&post_data=1&api_key=API_KEY
Then see if you are getting 200 code and take a look at "POST_DATA" key in event output,

**Comment by marcel-vermeulen** [comment]
Hi mikeTWC1984, thank you for your response.
Feedback as follows:
1. Event parameters - literally as simple as {"dummyname" : "test1"} as a test. When adding this is POST Data it works flawlessly, but specifying hostname as key name and entering a value does not . When looking at the params data on the web endpoint side, the parameters are not included.
2. Try with curl? I did not, however was repeatedly successful using python request test script to call same endpoint with same data.
3. I will try your suggestion to debug and will post back.

I'm basically just trying to achieve an outcome of using an HTTP plug-in with custom params to POST json data to a webservice.
I appreciated your response.

**Comment by marcel-vermeulen** [comment]
Hi Mike - I managed to set up the debug job, and have attached the resulting logs. Connection is made successfully but only if I do a GET request, and under params it's clear that it does not include the data values for my custom jsondata key.

Thanks for any response in advance. Still hoping to get the json data to pull through as params so I can use it in subsequent processing.

**Http Request Event**
[Cronicle-Job-Log-jkl9ftxgz0h.txt](https://github.com/jhuckaby/Cronicle/files/5995789/Cronicle-Job-Log-jkl9ftxgz0h.txt)

**Shell Event**
[Cronicle-Job-Log-jkl9ftxkg0i.txt](https://github.com/jhuckaby/Cronicle/files/5995774/Cronicle-Job-Log-jkl9ftxkg0i.txt)

**Comment by mikeTWC1984** [comment]
How do you specify post data? It should be a valid JSON. The below event work just fine on my end.
![image](https://user-images.githubusercontent.com/31977106/108218305-83339080-7102-11eb-922c-37200dc7f48a.png)

**Comment by marcel-vermeulen** [comment]
Hi - Your example works on my side too indeed, but this is not how I want to pass in the data to post.

I want to use custom parameters like a "form" where the fields and values becomes the json data added to a POST request to the webservice.

My current workaround is to use a shell plugin that collects those custom parameters from stdin and then inside a python script I do a post request to same http webservice using the keys/values from params. This adds and additional step however that I thought should be possible to do in a similar fashion using the url plugin. So my current understanding is that any custom parameters I specify will get passed as json data into the http post request.

As an alternative, is there a way to collect the custom parameters and append it to the POST Data field then perhaps?

**Comment by marcel-vermeulen** [comment]
My screenshots - difference is I dont use POST Data field:
![image](https://user-images.githubusercontent.com/62619796/108252943-e43e8100-7161-11eb-8c42-19c67a746048.png)

Result:
![image](https://user-images.githubusercontent.com/62619796/108253027-fddfc880-7161-11eb-8c77-2f5a4b21bd5d.png)

**Comment by mikeTWC1984** [comment]
What is the source of that custom data you want to post? Is it some other cronicle event?

**Comment by marcel-vermeulen** [comment]
Source key/values are supposed to come from the custom fields I specify on the same event. So as per my example, if I have a custom field name "jsonkey1" , populated with value "jsonvalue1" , this should become the json payload that is added to the http request that POST to the web endpoint.

![image](https://user-images.githubusercontent.com/62619796/108359101-37fba980-71f8-11eb-839f-d88f80a63344.png)

In the job log it shows POST Data is empty (as it should be as I did not add manual json values), but I cannot determine if any other json data was added to the http request (as happens on a shell job).

![image](https://user-images.githubusercontent.com/62619796/108359683-f91a2380-71f8-11eb-95d8-e54d37014504.png)

**Comment by marcel-vermeulen** [comment]
@mikeTWC1984 Thank you very much! This was the guidance I needed. 
Adding "custom_fieldname":"[/params/custom_fieldname]" for every fill in field I need in the POST "data" field, and setting method to POST solves this. I was even able to hide the data field after first adding my custom fields on the plugin config.
