### ISSUE TITLE
API entry point for failed and succeed tasks?

### ISSUE THREAD

**Issue by meteoDaniel** [jhuckaby/Cronicle#379]
Dear all, 

I just want to know if there is a Rest-API entry point to check out failed tasks e.g. within the last x hours?

Thanks a lot for your support.

**Comment by mikeTWC1984** [comment]
There is no much options for advanced querying. I guess just use get_history api, pull like last 1000 jobs and then do some filtering on your end.
http://localhost:3012/api/app/get_history?offset=0&limit=1000&api_key=123456

**Comment by meteoDaniel** [comment]
@mikeTWC1984  thanks for this hint! I guess this will work for me :)
