### ISSUE TITLE
community platform?

### ISSUE THREAD

**Issue by mcfetz** [jhuckaby/Cronicle#383]
hi all,
is there any community platform (discussion board, forum or something else) where cronicle users can share there experiences, best practices, tricks and so on? 
I would find an exchange outside of the classical issues at github very interesting.

Daniel

**Comment by mikeTWC1984** [comment]
I haven't seen one. Github Discussions might be a good option for such thing (needs to be enabled separately)

**Comment by jhuckaby** [comment]
Good idea guys.  I've enabled GitHub Discussions for Cronicle.  Never tried this before!

https://github.com/jhuckaby/Cronicle/discussions

**Comment by mcfetz** [comment]
Thank you Joseph!
