### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by carlonuccio** [jhuckaby/Cronicle#389]
## Summary

I found some vulnerabilities in Cronicle. 

## Steps to reproduce the problem

Each session file and conf file are readable from all users (chmod 644). So if a root user login to cronicle, another user can take his token and use it in bash inside cronicle.

Another vulnerability is XSS, so an attacker can inject javascript malware. Vulnerable URLs:
_/api/app/update_event
/api/app/create_event
/api/user/update_

You can write javascript in 'title' and 'form' fields. Can I solve it setting Content-Type and X-Content-Type-Options?

## Your Setup

Installed using 

`curl -s https://raw.githubusercontent.com/jhuckaby/Cronicle/master/bin/install.js | node`

### Operating system and version?

RedHat 7.3

### Node.js version?

v6.17.1

### Cronicle software version?

0.8.56

### Are you using a multi-server setup, or just a single server?

Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

**Comment by mikeTWC1984** [comment]
Regarding you first point - if you are going to share access to Cronicle with other people yes, you need to set proper permission at least for data and conf directories. You also need to set shell plug to run as non-root user.

Regarding the second one - title indeed allows you to set any non-empty value , including html with script tags (or you mean something else?). Good catch. I don't think headers will help. I think to start some more restrictive validation regex for titles need to be set .  I guess ideally there should be some html encoding for any user input. @jhuckaby any thoughts?

**Comment by mikeTWC1984** [comment]
Speaking of vulnerabilities, when you install Cronicle you might see bunch of warnings from npm. I usually do ```npm audit fix --force``` afterwards. This in theory can bring some braking changes, but I have never had any issue (for a very long time). It will fix vast majority of npm reported vulnerabilities. There will be only one "high" left, which is about "null byte", which Cronicle seemed to take care of.

**Comment by carlonuccio** [comment]
Regarding first point, yes, I need to share with other people. I set to run as non-root users, but conf and data directories can be read from any users, this is very critical.

Regarding second point, yes, you can include html with script tags in 'title' and 'form' fields.

**Comment by jhuckaby** [comment]
Thanks for bringing this to my attention.  I will strip HTML tags from all titles.

I will say that I designed Cronicle to run inside a trusted organization, behind a firewall and/or VPN, so the assumption was that the users would never attempt something like stuffing HTML into text fields, and that the user interface would not be exposed to the public internet.  There are probably a variety of attack vectors along these lines.  I mean, when you think about it, the Shell Plugin essentially allows any user to run any shell commands on your servers, right from the UI.  This could be seen as an enormous security vulnerability, but it is literally by design.

I will sanitize the titles tho.

As far as the directory permissions go, feel free to chmod them as you see fit.  Just make sure that the data directory is root readable and writable.  The conf directory can be 0400 I think, but I've never tested that.

**Comment by skynuccioc** [comment]
Regarding first point, I set 400 and it seems it works. Thank you for support.

Let me know when you strip HTML tags. Thank you

**Comment by carlonuccio** [comment]
Regarding first point, I set 400 and it seems it works. Thank you for support.

Let me know when you strip HTML tags. Thank you

**Comment by carlonuccio** [comment]
@jhuckaby about stripping HTML, do you think are you able to release next week?

**Comment by carlonuccio** [comment]
the same problem is in tag 'full_name' of user update

**Comment by mikeTWC1984** [comment]
@carlonuccio  if it's an emergency you can update validation regex yourself. 
To tweak event related apis you can locate **requireValidEventData** function definition and update corresponding regex. E.g. if you want title to only be alphanumeric with white space or underscore, replace /\S/ with  /^[\w\s\_]+$/ . if api file contains **requireParams** function you probably need to mirror that change too. Api files are in lib/api. 

Aslo (if not yet) set permission (like 0700) for /opt/cronicle/data directory (or whatever you use for data)

**Comment by jhuckaby** [comment]
Fixed in [v0.8.57](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.57).
