### ISSUE TITLE
update some npm packages 

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#404]
Upon "npm install" is over a critical vulnerability is reported:
https://npmjs.com/advisories/1708
Need to upgrade nodemailer to 6.4.16 or higher. This actually need to be done on pixl-mail package

There is also a buch of new "high" vulnerabilities reported, which I haven't seen before. Vast majority still could be fixed via "npm audit fix --force", the only thing - it upgrades chart.js to v3 which has some breaking changes. But updating it to version 2.9.4 (from 2.7.1) would avoid this problem.

**Comment by jhuckaby** [comment]
Thank you for bringing this to my attention.  I'll get on this ASAP, either tonight or this weekend.

**Comment by mikeTWC1984** [comment]
One more thing for clean up - on the Admin tab, there are few places where user input can appear on html table. See the list below. Those could be wrapped using "encode_entities" function. The "description" from activity log is a bit more complicated, since it's html by design. Probably can use js-xss module (it would keep basic html elements but encode script related tags/attributes)

Activity Log:  Description

API Keys: API Key

Categories: Description 

Servers: Hostname Match

Users: Full Name, Email Address

**Comment by jhuckaby** [comment]
Thanks, I fixed most of these.  I don't see the activity log as a huge issue, because almost all of the values are sanitized previously (e.g. hostnames, IP addresses, etc.), and the general "description" properties for warnings and errors are already entity-encoded.

**Comment by jhuckaby** [comment]
Also released v0.8.60 with fix to pixl-mail for nodemailer vuln.
