### ISSUE TITLE
Can't schedule a cron after booting 

### ISSUE THREAD

**Issue by RahulnKumar** [jhuckaby/Cronicle#406]
I didn't find any option for scheduling a cron after booting or rebooting a machine.
There should by an option **after boot** in timing pop menu in web ui of chronicle.
Like in our local machine, we can schedule a cron at boot time with some time gap with the following cron command :
`@reboot sleep 90 && cd ~/projects && /usr/bin/python test.py`
*This isn't a bug, I'm only suggesting it as a feature.*

**Comment by mikeTWC1984** [comment]
Do you mean machine reboot or cronicle process restart?

**Comment by RahulnKumar** [comment]
I mean machine reboot.

**Comment by mikeTWC1984** [comment]
OK. I think it's a good idea to have "at start up" trigger to launch a job or at least fire a webhook. I guess it's not trivial to define "machine startup" from inside node process though.  Probably the good "heuristic" would be os.uptime(). E.g. trigger would check any node start up and then optionally limit uptime duration.

**Comment by RahulnKumar** [comment]
Yes, I agree.
Thanks.  :)
