### ISSUE TITLE
Service won't stay started; TypeError: storage.addRecordType is not a function

### ISSUE THREAD

**Issue by ODA-AG** [jhuckaby/Cronicle#409]
## Summary

I tried to upgrade Cronicle from v0.8.57 to v0.8.61 and while the control.sh version says it is at v0.8.61 when I start the control.sh, it immediately stops.

This was in the crash log:

TypeError: this.storage.addRecordType is not a function
    at constructor.startup (/opt/cronicle/lib/engine.js:76:16)
    at /opt/cronicle/node_modules/pixl-server/server.js:229:10
    at /opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:3110:16
    at replenish (/opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:995:17)
    at /opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:969:16
    at /opt/cronicle/node_modules/pixl-server-web/web_server.js:207:9
    at Server.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:398:4)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)

This happens if I run the control.sh setup command:

/opt/cronicle/bin/storage-cli.js:120
        storage.addRecordType( 'cronicle_job', {

TypeError: storage.addRecordType is not a function
    at /opt/cronicle/bin/storage-cli.js:120:10
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:70:4
    at constructor.startup (/opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:31:3)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:68:15)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:48:19
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

### Are you using a multi-server setup, or just a single server?
Single Server

**Comment by jhuckaby** [comment]
What a bizarre problem.  It looks like somehow you have an older [pixl-server-storage](https://github.com/jhuckaby/pixl-server-storage) module.  The custom record types were added in [v2.0.7](https://github.com/jhuckaby/pixl-server-storage/commit/38063de3fe81306b06951fc28b3ab80e11dbee42), and Cronicle's [package.json file](https://github.com/jhuckaby/Cronicle/blob/master/package.json#L55) requires at least version v2.0.10, so this crash should **never** occur.

The only thing I can think is that you have an old version of Node.js, or perhaps a broken version of NPM, which messed up the dependencies, and installed an old version of pixl-server-storage, and god knows what else.  Can you please run these three commands on your server, and paste the output of each here into this GitHub issue?  That might shed some light on the problem:

```
node --version
npm --version
grep version /opt/cronicle/node_modules/pixl-server-server/package.json
```

Depending on what those commands say, I will probably recommend that you upgrade your Node.js on your server to the latest stable LTS version, and then force a reinstall of all Cronicle's node modules.  Here is how you do that:

- First, upgrade your server to the latest Node.js.  This comes with the latest NPM as well.  As of this writing, it is version 14.17.0.  Unfortunately, you didn't say which OS or OS version you are using, so here is the main Node.js download page.  You can figure it out from there: https://nodejs.org/en/download/
- Become the root (superuser) user on your server.
- Next, wipe out the `node_modules` folder in Cronicle:
    - `rm -rf /opt/cronicle/node_modules`
- Force a reinstall of the node modules like this:
    - `cd /opt/cronicle && npm install`
- Start Cronicle

**Comment by ODA-AG** [comment]
I ended up deleting and installing Cronicle over again. Now it works, but I would like to understand what files can I backup so I don’t have to recreate everything next time?

Arnold Garcia · IT Manager
OnDemandAnalysis · PO Box 1073, White Salmon, Washington 98672
SITE.WORK Software LLC · PO Box 1073, White Salmon, Washington 98672
Cell: (360) 947-5209 · Office: (503) 460-0605

**Comment by jhuckaby** [comment]
> I ended up deleting and installing Cronicle over again. Now it works, but I would like to understand what files can I backup so I don’t have to recreate everything next time?

If you are using the local filesystem, then backup the `/opt/cronicle/data` directory.  Also, your config file located at `/opt/cronicle/conf/config.json`.
