### ISSUE TITLE
Headers are not being sent properly for HTTP call

### ISSUE THREAD

**Issue by ericklind** [jhuckaby/Cronicle#410]
## Summary

When I save the headers for an event for the HTTP plugin, they seem to save correctly, but are sent incorrectly when the call is made.

## Steps to reproduce the problem

When I POST to create_event, the headers show up in the event like this:

`'x-api-key': 'MY_KEY', 'Accept': '*/*', 'Content-Type': 'application/json'`

When the call is made the header are return like this:

```
 'accept-encoding': 'gzip, deflate, br',
    'user-agent': 'PixlRequest 1.0.36',
    "'x-api-key'": "'MY_KEY', 'Accept':
 '*/*', 'Content-Type': 'application/json'",
    'content-length': '32',
```
As you can see the header variable name becomes: 

 ` "'x-api-key'" `

The value is: 
```
"'MY_KEY', 'Accept':
 '*/*', 'Content-Type': 'application/json'"

```
## Your Setup

Calling Cronicle with a react app.

### Operating system and version?

Ubuntu.

### Node.js version?

14.15

### Cronicle software version?

Cronicle Version 0.8.61

### Are you using a multi-server setup, or just a single server?

Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

### Can you reproduce the crash consistently?

No crash, but yes this happens every time.

**Comment by mikeTWC1984** [comment]
Are you using single quotes/commas when specifying headers? If so you should omit it:
![image](https://user-images.githubusercontent.com/31977106/120950428-c3039f80-c714-11eb-9248-5bcad88a8404.png)

**Comment by ericklind** [comment]
I was finally able to get it working. I have to do this:
```
let headers = `x-api-key: MY_KEY
Accept: */*
Content-Type: application/json`
```
This is not really ideal. I would recommend having it be an array that gets parsed. Just my $.02.
