### ISSUE TITLE
Question: Where the job logs are stored?

### ISSUE THREAD

**Issue by Servod** [jhuckaby/Cronicle#411]
Hello! Сould you please tell me where the job logs are stored on the disk? I am using single server mode. Instructions on the main page tells that "job logs and other data is stored as plain JSON files on local disk". I've found the /opt/Cronicle/logs/jobs directory on my server, but I have a lot of jobs and the files in this directory are very small. They hardly contain logs of all jobs. So can you please tell me correct path and default filename(s) of job logs. Thank you!

**Comment by jhuckaby** [comment]
The logs are stored in a "database" on disk, which is distributed across many directories.  If you used the default settings and are using local disk for storage, then it will be in `/opt/cronicle/data/`, but you will find it difficult to locate what you want, as this is traversing a raw database hash structure on disk.  This is so the logs can be quickly retrieved in the UI.

If you want copies of your logs, your best bet is to use the [copy_job_logs_to](https://github.com/jhuckaby/Cronicle#copy_job_logs_to) configuration property.  Set this to any directory on your disk, and your job logs will be copied there.

Good luck!
