### ISSUE TITLE
Add localisation / translation

### ISSUE THREAD

**Issue by julian-weinert** [jhuckaby/Cronicle#414]
I really like Cronicle for its simplicity. This leads to even more possible use cases like connecting to hardware and scheduling automation related things.
In the field I'm looking at using Cronicle in it would be nice to support other languages as well. So I wanted to offer a translation and realised while browsing through the code that this is not (yet?) accounted for.

I would also like to offer my time to implement something like this, but didn't want to invest a lot of work into a PR you may not even be interested in.

Are there any plans for this already? Would there be some preferred library for or would you also go with something written "bare metal"?

I'm happy with any kind of input

**Comment by jhuckaby** [comment]
Thank you!  Unfortunately I did not design Cronicle with localisation in mind.  All the strings are hard-coded in a million different places, strewn across the codebase.   Not only that, but the time and date representation needs to be internationalized as well, and this is not a small thing by any stretch.  It's a massive undertaking.

However, I will NOT make this mistake with Cronicle v2.0 (new name: "Orchestra"), which is currently in active stealth development.  I am doing the correct thing this time, by having localized JSON files for each locale (e.g. `en-US.json`) containing all the various strings, as well as full international date and time support.  I would be very happy to accept your help in adding new locales!

If It is okay, I'll reach out to you when Orchestra comes out of stealth and is ready for localization.

**Comment by julian-weinert** [comment]
Oh, that's good and sad to hear at the same time :)
I would have put some effort into it myself, but it's clear there is no reason, since you're already at it.
Meaning there is no short term solution (which is fine).

But I'm even more glad to hear there's something new in the pipeline and I'm very looking forward it.

Yes of course! Please feel free to contact me, if the time comes.
I'm also happy to lend a hand with implementation stuff, if needs be.

Thanks!

**Comment by julian-weinert** [comment]
Hey @jhuckaby!
Can you comment in any way on the progress of the project?
I'm really keen on seeing this progress :)
Cheers

**Comment by jhuckaby** [comment]
Hey @julian-weinert, thank you for the interest!  I do apologize, but I can't comment on the progress of the project.  I am developing Orchestra "in stealth" (i.e. offline), mostly to reduce stress on myself.  I am a one-person team here, and just doing this for fun, in my free time.  I can tell you that the current estimate for release is "early 2022".  I'll make sure to add a comment here on this thread when it is released 😊

**Comment by julian-weinert** [comment]
Great, thank you!

**Comment by sdhzwc** [comment]
I'm really keen on seeing this progress

**Comment by jhuckaby** [comment]
Oh man, this thread was started back in 2021!  I am SO SORRY this is taking me so long, everyone.  Orchestra development continues every day, but it's a huge app with a ton of new features (localisation being one of them), so it's taking me much, much longer than I originally planned.  But I WILL finish it!  Or I will die trying!  😝
