### ISSUE TITLE
setup fails with TypeError: this.logger.print is not a function

### ISSUE THREAD

**Issue by gerner** [jhuckaby/Cronicle#416]
## Summary

During setup I get a node stacktrace saying TypeError: this.logger.print is not a function

## Steps to reproduce the problem

```
mkdir -p /opt/cronicle
cd /opt/cronicle
curl -s https://raw.githubusercontent.com/jhuckaby/Cronicle/master/bin/install.js | sudo node
sudo /opt/cronicle/bin/control.sh setup
```

Observe the error message:
```
/opt/cronicle/node_modules/pixl-server/component.js:69
                        this.logger.print({
                                    ^

TypeError: this.logger.print is not a function
    at __construct.logDebug (/opt/cronicle/node_modules/pixl-server/component.js:69:16)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:57:8)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:50:19
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

I also tried this via manual steps:

```
git clone git@github.com:jhuckaby/Cronicle.git cronicle
sudo ln -s $(pwd) /opt/cronicle
cd /opt/cronicle
npm install
node bin/build.js dist
/opt/cronicle/bin/control.sh setup
```

Same result.

If I edit component.js and simply comment out that `this.logger.print` call (inside of logDebug) and re-run setup, then setup _appears_ to succeed and I can start cronicle, log in, create an event, run it without obvious problems.

### Operating system and version?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$ uname -a
Linux nickpad-t14s 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Node.js version?

```
$ node --version
v14.17.1
```

### Cronicle software version?

I tried this with both master (d2cc143224da31c11af68389a6f7bd819892fb46) and v0.8.61

### Are you using a multi-server setup, or just a single server?

Haven't gotten that far :)

### Are you using the filesystem as back-end storage, or S3/Couchbase?

config/config.json out of the box, I believe that's filesystem

### Can you reproduce the crash consistently?

yep

## Log Excerpts
```
/opt/cronicle/node_modules/pixl-server/component.js:69
                        this.logger.print({
                                    ^

TypeError: this.logger.print is not a function
    at __construct.logDebug (/opt/cronicle/node_modules/pixl-server/component.js:69:16)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:57:8)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:50:19
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by jhuckaby** [comment]
Oh my god.  Thank you for bringing this to my attention.  This was caused by a very recent commit to one of the Cronicle dependencies.  I am fixing it ASAP, right this very minute.  Thank you!!!

**Comment by gerner** [comment]
Haha, I was expecting to hear that I'm obviously doing something wrong. Thanks for the prompt response. I was about to say, "oh well, I guess it's back to Jenkins."

I'm eagerly awaiting a fix/workaround.

**Comment by jhuckaby** [comment]
All fixed, and I pushed out [v0.8.62](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.62) just to make sure Cronicle will never pull that old dependency version ever again.

Thanks man!

**Comment by jhuckaby** [comment]
Just tested on a AWS EC2 instance and the installer is working properly.  It took a few minutes for NPM to catch up on the dependency release.

**Comment by gerner** [comment]
Just tried the latest version and it works for me too. Thanks so much for being so responsive!
