### ISSUE TITLE
Cronicle Daemon crashes with new SSL certificates

### ISSUE THREAD

**Issue by DevNull-00** [jhuckaby/Cronicle#430]
## Summary

Hello everyone, I was trying to update my SSL certificates on my server but Cronicle daemon keeps crashing. When I try to start it giving me a "bad decrypt" error. I don't understand why I have this problem, since I'm using the same certificate/key files for multiple services on my server (such as apache) and they all are working with the new certificates.

## Steps to reproduce the problem

I don't really know how you could reproduce this issue, maybe the private key password has been changed since last time(?). I don't remember it was more than 1 year ago.

## Your Setup

A simple master Cronicle server with no slaves, just 1 server.

### Operating system and version?

Ubuntu 18.04.5 LTS

### Node.js version?

v13.14.0

### Cronicle software version?

Version 0.8.62

### Are you using a multi-server setup, or just a single server?

Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Nope

### Can you reproduce the crash consistently?

Yes, always with the new certificates

## Log Excerpts

```
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Object.createSecureContext (_tls_common.js:149:17)
    at Server.setSecureContext (_tls_wrap.js:1318:27)
    at Server (_tls_wrap.js:1182:8)
    at new Server (https.js:64:14)
    at Object.createServer (https.js:88:10)
    at constructor.startHTTPS (/opt/cronicle/node_modules/pixl-server-web/web_server.js:444:34)
    at /opt/cronicle/node_modules/pixl-server-web/web_server.js:205:10
    at Server.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:398:4)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)

```

**Comment by mikeTWC1984** [comment]
So you are saying it worked with old certs, but now it's crashing? What is the difference between those certs? Like old one is RSA other is ECDSA, or key length is different? Do you have some ancient  version of openssl?

**Comment by DevNull-00** [comment]
I think I found out the problem, I was trying to pass an encrypted private key to the daemon and so it kept crashing :/
Next time I will remember to pass only unencrypted keys
