### ISSUE TITLE
Customise page layout.

### ISSUE THREAD

**Issue by audetto** [jhuckaby/Cronicle#433]
Hi I am using 0.8.62.

Since we have 2 Cronicle instances, I was wondering if there is a way to customise the page name to draw the attention of the user to which one is being run.
Or even a way to change the background color.

Regards.

**Comment by jhuckaby** [comment]
Sure, change this line in your `/opt/cronicle/conf/config.json` file:

https://github.com/jhuckaby/Cronicle/blob/master/sample_conf/config.json#L49

```js
"name": "Cronicle",
```

Set it to any title you want, and this is displayed on every page in large text in the header.  You don't even have to restart the service, as it hot-reloads the file after ~10 seconds or so.

<img width="268" alt="Screen Shot 2021-07-21 at 11 26 34 AM" src="https://user-images.githubusercontent.com/700765/126540595-09a37213-171a-4b4e-ac84-87a7faf29e86.png">
