### ISSUE TITLE
feature request - ability to specify host for s3

### ISSUE THREAD

**Issue by jhoustek23** [jhuckaby/Cronicle#435]
## Summary

I'd like to connect to my own S3 compatible storage (Ceph RadosGW)

## Steps to reproduce the problem

Thewre is no "host" configuration in S3 connection settings.

## Your Setup

New install.

### Operating system and version?

Debian 10.10
### Node.js version?
latest

### Are you using a multi-server setup, or just a single server?
Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
S3

**Comment by mikeTWC1984** [comment]
cronicle could work with non-aws s3 storages. At least it works with minio. Check out the config below:
```json
"Storage": {
		"engine": "S3",
		"AWS": {
			"endpoint": "http://minio:9000",
			"endpointPrefix": false,
			"s3ForcePathStyle": true,
			"region": "east",
			"hostPrefixEnabled": false,
			"accessKeyId": "admin",
			"secretAccessKey": "admin_secret",
			"correctClockSkew": true,
			"maxRetries": 5,
			"httpOptions": {
				"connectTimeout": 5000,
				"timeout": 5000
			}
		},
		"S3": {
			"fileExtensions": true,
			"params": {
				"Bucket": "cronicle"
			}
		}
	},
```

**Comment by jhoustek23** [comment]
@mikeTWC1984 thanks man!
