### ISSUE TITLE
Cronicle version: querying and upgrading

### ISSUE THREAD

**Issue by aldanor** [jhuckaby/Cronicle#44]
Two minor suggestions that could make Cronicle easier to manage via deployment tools (like Ansible):

- Would be nice to have `control.sh version` that would output e.g. `v0.7.4` (matching the git release). This would allow to check automatically whether an upgrade is needed on a managed node.
- Currently, supplying an invalid version to `control.sh upgrade` does two things: restarts the daemon and returns 0 (while printing the error to console); I would probably naturally expect it to just return 1 instead and take no further action.

Thanks!

**Comment by jhuckaby** [comment]
Added to TODO list, thanks!

**Comment by aldanor** [comment]
Looks like this can be now closed? (65769a9cb24a1bb660f301d7ad4f256fe8ebc9a7 and b52be49535ddb4dff853bc14f925e384fcbf960d)

A few other issues that I've opened or parts of them seem to also be fixed in master (thanks!!). Any plans on releasing a new version in the foreseeable future?

**Comment by jhuckaby** [comment]
Yup, sorry for the delay, have been dealing with holiday / family stuff.  I will release a new version this weekend, and close these issues.  Thanks for the ping!

**Comment by jhuckaby** [comment]
Fixed in [v0.7.5](https://github.com/jhuckaby/Cronicle/releases/tag/v0.7.5).  Thanks!
