### ISSUE TITLE
Trying to make a donation

### ISSUE THREAD

**Issue by chrisdlangton** [jhuckaby/Cronicle#464]
I don't see anything in the README
No Github Sponsor available
The site has no obvious way to donate

I love the project, came across it recently and after trying many paid and free alternatives that didn't come close to my needs or did way too much it was a bad experience

I saw the project dying (refusing PRs and announcing Orchestra) and was happy to see the release 3 days ago! Let's keep this alive!

**Comment by jhuckaby** [comment]
Thank you for your offer to make a donation!  I never got any of that stuff set up (GitHub Sponsors, etc.).  I may do it someday.  I guess I just feel bad asking for money for open source work.

Cronicle is still maintained, but I am spending most of my time working on new major features on Orchestra, and thus Cronicle has moved to a maintenance-only phase.  I do accept some PRs, but usually only for small bug fixes.  Large PRs get me into trouble, as I lose control of the project, and become unable to troubleshoot bugs.  This has happened to me on a number of previous projects, so I try to only accept bug fix PRs that are small in scope.

I know I am missing out on awesome contributions by other excellent developers, but I have to weigh that against my own ability to maintain the project over time.

Anyway, thank you for your kind words, and thank you for using Cronicle.
