### ISSUE TITLE
Cronicle login page does not load up behind a load balancer

### ISSUE THREAD

**Issue by mpatel-cpi** [jhuckaby/Cronicle#47]
## Summary

I installed Cronicle on an AWS EC2 instance (in private subnet) and put it behind a load balancer (ALB).

Cronicle login page does not load up completely. Chrome developer tools show a websocket request is being made with the private DNS name of the cronicle master (but its inaccessible since its behind a load balancer).

How can I make Cronicle work with a load balancer?

## Steps to reproduce the problem

Brand new Cronicle setup behind a load balancer. Run setup and start Cronicle.

## Your Setup

I installed Cronicle on an AWS EC2 instance (in private subnet) and put it behind a load balancer (ALB).

### Operating system and version?

Ubuntu 16.04

### Node.js version?

v4.2.6

### Cronicle software version?

0.7.5

### Are you using a multi-server setup, or just a single server?

Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

### Can you reproduce the crash consistently?

Yes

## Log Excerpts

WebSocket connection to 'wss://cronicle-master-1.local:3013/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.

VM100:164 WebSocket connection to 'wss://cronicle-master-1.local:3013/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

**Comment by mpatel-cpi** [comment]
Looks like this is happening without load balancer too. The websocket URI uses the local hostname of the server instead of DNS name of the load balancer. So it was not resolving.

Changing the local hostname to DNS name resolved the issue. I think we should fix the websocket URI to use the DNS name instead of local hostname.

**Comment by jhuckaby** [comment]
Hello,

I believe this is as designed.  Cronicle requires direct connections to servers in the cluster.  While it can work behind a load balancer, you still need to be able to connect to all your servers directly. 
 
Cronicle will connect to each server using it's local LAN IP address, unless you set the [web_socket_use_hostnames](https://github.com/jhuckaby/Cronicle#web_socket_use_hostnames) and/or [server_comm_use_hostnames](https://github.com/jhuckaby/Cronicle#server_comm_use_hostnames) configuration parameters.  Then it will use the server's local hostname.  If you choose to use hostnames, then they need to resolve in DNS to IP addresses.

If you set [web_socket_use_hostnames](https://github.com/jhuckaby/Cronicle#web_socket_use_hostnames) to true, then your clients need to be able to resolve and connect to the local hostnames of each server in your cluster.  If you set [server_comm_use_hostnames](https://github.com/jhuckaby/Cronicle#server_comm_use_hostnames), then your master server needs to be able to resolve and connect to the local hostnames of each server in your cluster.

Please see the Cronicle docs on [Load Balancers](https://github.com/jhuckaby/Cronicle#load-balancers) and [Ops Notes](https://github.com/jhuckaby/Cronicle#ops-notes) for other things to keep in mind.

Sorry for the confusion.
