### ISSUE TITLE
Maybe bug when start Cronicl daemon "Error: EEXIST: file already exists, mkdir 'logs'"

### ISSUE THREAD

**Issue by VladimirZaytsev** [jhuckaby/Cronicle#470]
After pixl-server version upgrade from 1.0.31 -> 1.0.32. We starts receiving the error:
```
---[ Cronicle ]---
Update current HOST and IP to: cronicle-app-0 (10.233.102.229)
Writing record from STDIN: global/server_groups/0
Record successfully saved: global/server_groups/0
Writing record from STDIN: global/servers/0
Record successfully saved: global/servers/0
/opt/cronicle/bin/control.sh start: Starting up Cronicle Daemon...
Error: FATAL ERROR: Log directory could not be created: logs: Error: EEXIST: file already exists, mkdir 'logs'
    at __construct.__init (/opt/cronicle/node_modules/pixl-server/server.js:101:11)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server/server.js:380:8)
    at Object.<anonymous> (/opt/cronicle/lib/main.js:35:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
/opt/cronicle/bin/control.sh start: Cronicle Daemon could not be started
```

I could fix this problem with pinning pixl-server@1.0.31 by "npm install pixl-server@1.0.31"

## Your Setup
We use docker image from "node:10.11-alpine" with mounted volumes: ["/opt/cronicle/data", "/opt/cronicle/logs", "/opt/cronicle/plugins"]

with cronicle 0.8.57 installed via npm

### Operating system and version?
Alpine 3.8.1

### Node.js version?
10.11

### Cronicle software version?
0.8.57

### Are you using a multi-server setup, or just a single server?
just single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
fs backend

### Can you reproduce the crash consistently?
yep

**Comment by jhuckaby** [comment]
Looks like you're using Node v10.  This is very old at this point, and is no longer compatible with Cronicle.  We only support the latest LTS version (currently v16).

I'll work on putting in a warning for this, so something obvious is emitted to the console on startup, or something.

**Comment by traveltek-jnewall** [comment]
# /opt/cronicle/bin/control.sh restart
stop: Cronicle Daemon not running (pid 28945?)
/opt/cronicle/bin/control.sh start: Starting up Cronicle Daemon...
/opt/cronicle/bin/control.sh start: Cronicle Daemon started
-cronicleserver-stage:~# /opt/cronicle/bin/control.sh status
status: Cronicle Daemon not running (pid 29200?)
-cronicleserver-stage:~#

I had a similar issue to the above error and trying to figure out why the daemon is not starting. I was initially running on nodejs v8.10.0 but have tried different versions and now getting the above issue. It says it is starting and has started and then says it is not running. The version of cronicle is  0.8.39  

Any help would be much appreciated
