### ISSUE TITLE
Cronicle installation issue

### ISSUE THREAD

**Issue by traveltek-jnewall** [jhuckaby/Cronicle#472]
Hello i am looking for any guidance or advise on anyone who has experience with this error message on Cronicle:

Welcome to Cronicle!
First time installing?  You should configure your settings in '/opt/cronicle/conf/config.json'.
Next, if this is a master server, type: '/opt/cronicle/bin/control.sh setup' to init storage.
Then, to start the service, type: '/opt/cronicle/bin/control.sh start'.
For full docs, please visit: http://github.com/jhuckaby/Cronicle
Enjoy!

fatal error: An error occurred (404) when calling the HeadObject operation: Key "configs///cronicleconfig.json" does not exist

We terminated the server we were running cronicle on and span up a new one and when trying to start the daemon we are getting the following issue 

root@i-02756d6f2129b3e08-cronicleserver-stage:/opt/cronicle/conf# /opt/cronicle/bin/control.sh start
/opt/cronicle/bin/control.sh start: Starting up Cronicle Daemon...
Error: FATAL ERROR: Log directory could not be created: logs: Error: EEXIST: file already exists, mkdir 'logs'
    at __construct.__init (/opt/cronicle/node_modules/pixl-server/server.js:101:11)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server/server.js:380:8)
    at Object.<anonymous> (/opt/cronicle/lib/main.js:35:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
/opt/cronicle/bin/control.sh start: Cronicle Daemon could not be started

We removed the logs and started again although this did not help so proceeded to try and manually install cronicle due to it not succeeding during the bootstrap by running: source /opt/tt-install/snippets/cronicleserver and that's when we then get the error:

fatal error: An error occurred (404) when calling the HeadObject operation: Key "configs///cronicleconfig.json" does not exist
The thing is s3://<>-ec2-userdata/configs/stage/eu1/cronicleconfig.json still exists. And I know from tailing the /var/log/cloud-init-output.log log file that it successfully got copied:
download: s3://<>-ec2-userdata/configs/stage/eu1/cronicleconfig.json to conf/config.json
Within /opt/cronicle/confconfig.json is there.

We looked in the file and there is no obvious issues although the key " "configs///cronicleconfig.json " does not seem right.

We are not sure where this is being referenced and just wondering if anyone has come across this issue previously?

**Comment by jhuckaby** [comment]
This is not a Cronicle issue.  You are using a modified version that has additional code.  Cronicle **never** loads its configuration from S3, and doesn't have any error message that even remotely resembles this one:

> fatal error: An error occurred (404) when calling the HeadObject operation: Key "configs///cronicleconfig.json" does not exist

Clearly this is some kind of "fork", hack or modification of Cronicle, so I cannot offer support for it.

You also removed the GitHub new issue template and didn't provide me with any of the necessary information to help you troubleshoot, including your OS version, Node.js version, and logs.

There isn't much I can do here.  Closing this as invalid.
