### ISSUE TITLE
websocket  conf error

### ISSUE THREAD

**Issue by coutouly** [jhuckaby/Cronicle#473]
## Summary

i try to run cronicle inside a single node docker .
everything is right except one thing:
the websocket url to print logs
the url the ws is trying to connect to is :
 
Live Job Event Log View Full Log Download Log
Log Watcher: Connecting to server: http://172.23.0.15:3012...
Log Watcher: Server Connect Error: Error: websocket error (http://172.23.0.15:3012)
Log Watcher: Server Connect Error: Error: websocket error (http://172.23.0.15:3012)

that is the docker inside ip adresse.
i try to set true to 
	"web_direct_connect": true,
	"web_socket_use_hostnames": true,
with
"base_app_url": "http://myserver.fr:8080",
in this case it doesnt show the webui with no master found

ws://172.23.0.15:3012/socket.io/?EIO=4&transport=websocket
it should be
ws://myserver.fr:8080/socket.io/?EIO=4&transport=websocket

**Comment by coutouly** [comment]
i found :+1: 
CRONICLE_client__custom_live_log_socket_url='http://cronicle.example.com'

**Comment by tushar9953** [comment]
I am facing the same issue. @coutouly @jhuckaby  can you please help with this? I am new to cronicle.

**Comment by jhuckaby** [comment]
@tushar9953 I am so sorry, but I have no idea how to use Docker.  Please see @coutouly's second comment.  It looks like they solved the problem, and closed this issue.

**Comment by tushar9953** [comment]
thank @jhuckaby 

@coutouly can you please help with this?

**Comment by mikeTWC1984** [comment]
@tushar9953 Did you try to set **client.custom_live_log_socket_url** config? The thing is that current live log mechanism requires direct connection to cronicle worker. If you using docker it acts like a proxy, so your browser is hitting that auto-generated docker hostname (which is unreachable from outside). If you run it on local machine you need to set that setting to localhost.

**Comment by tushar9953** [comment]
@mikeTWC1984 no I didn't make such config changes. Can you please guide how can I make it? Do I need to make it to all workers at individual level?

Thanks in advance :)

**Comment by coutouly** [comment]
hello
it is in this file
config.json
`
....
"client": {
		
		"custom_live_log_socket_url":"your url with port",
....
`

**Comment by tushar9953** [comment]
@coutouly 
I checked my config.json and found that there is no custom_live_log_socket_url available. Do I need to add it manually?

For your reference, adding it here as attachment.
[config.txt](https://github.com/jhuckaby/Cronicle/files/9249875/config.txt)

**Comment by coutouly** [comment]
yes you have to add it
