### ISSUE TITLE
Account is locked out

### ISSUE THREAD

**Issue by Eddy1210** [jhuckaby/Cronicle#48]
![image](https://user-images.githubusercontent.com/18549520/33412622-7c2f6c98-d5c7-11e7-84ec-759065b40f00.png)
This is because the admin user is not associated with this email address?

Any other way to reset the admin account's password？

**Comment by jhuckaby** [comment]
Recovery instructions here: [Recover Admin Access](https://github.com/jhuckaby/Cronicle#recover-admin-access)

**Comment by dreadedhamish** [comment]
Now located here: https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#recover-admin-access
