### ISSUE TITLE
Unable to setup with Couchbase

### ISSUE THREAD

**Issue by MrMeeb** [jhuckaby/Cronicle#490]
## Summary

When attempting to configure Cronicle to use Couchbase as a storage backend, running `/opt/cronicle/bin/control.sh setup` fails with the following error:

```
root@cronicle-osprey:/opt/cronicle# /opt/cronicle/bin/control.sh setup
/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:51
                        this.cluster.authenticate(this.config.get('username'), this.config.get('password'));
                                     ^

TypeError: this.cluster.authenticate is not a function
    at constructor.setup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:51:17)
    at constructor.startup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:33:8)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:110:15)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:50:19
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

## Steps to reproduce the problem

1. Install OS
2. Install NodeJS LTS and NPM using [Node Version Manager](https://github.com/nvm-sh/nvm)
3. Run Cronicle install script
4. Install Couchbase module: `cd /opt/cronicle`, `npm install couchbase`
5. Configure storage option in config
6. Run `/opt/cronicle/bin/control.sh setup`

## Your Setup

Latest version of Cronicle as of writing, 0.9.3
Debian 11 VM
Succesfully configured local storage method in the same environment

### Operating system and version?

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Node.js version?

v16.14.2

### Cronicle software version?

0.9.3

### Are you using a multi-server setup, or just a single server?
Planning to use a multi-server setup with Couchbase storage backend

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Couchbase

### Can you reproduce the crash consistently?
N/A

## Log Excerpts

```
root@cronicle-osprey:/opt/cronicle# npm install couchbase

up to date, audited 195 packages in 4s

11 packages are looking for funding
  run npm fund for details

8 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run npm audit for details.
root@cronicle-osprey:/opt/cronicle# /opt/cronicle/bin/control.sh setup
/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:51
                        this.cluster.authenticate(this.config.get('username'), this.config.get('password'));
                                     ^

TypeError: this.cluster.authenticate is not a function
    at constructor.setup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:51:17)
    at constructor.startup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:33:8)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:110:15)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:50:19
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
root@cronicle-osprey:/opt/cronicle#
```

Configuration excerpt:
```
	"Storage": {
		"engine": "Couchbase",
		"Couchbase": {
			"connectString": "couchbase://10.147.17.33",
			"bucket": "cronicle",
			"username": "cronicle",
			"password": "removed",
			"serialize": false,
			"keyPrefix": ""
		}
```

**Comment by jhuckaby** [comment]
I'm so sorry you ran into this.  See previous discussion and workaround here: https://github.com/jhuckaby/Cronicle/issues/448

It's still on my TODO list to upgrade pixl-server-storage to support the Couchbase v3.x API. I just haven't gotten around to it. Forcing a downgrade to v2 "works", and there are so few Couchbase users, that I didn't prioritize this.  That may have been a mistake.

I will update the Cronicle docs to force Couchbase v2 in the installation instructions, and try to find some time to work on the v3 API.

Thanks, and sorry.

**Comment by MrMeeb** [comment]
Not an issue, I was just evaluating options for multi-node storage as an exercise. As suggested, downgrading to Couchbase v2 worked as expected. Thanks!
