### ISSUE TITLE
Changing the Category ID via import

### ISSUE THREAD

**Issue by dsturgilljr** [jhuckaby/Cronicle#494]
The documentation says "The Category ID which is an auto-generated alphanumeric ID used only by the API. This cannot be changed." The Category ID can be changed via storage import/export (i.e. create category, export storage records, change id in exported text file, importing text file with new id). This doesn't seem to cause any obvious issues.

Is this going to cause a problem that I am not foreseeing?

**Comment by jhuckaby** [comment]
No problem, go right ahead.  That warning is really because I never wrote an API to change the ID.  But inside the underlying storage system, i.e. via export/import, you can change whatever you want.
