### ISSUE TITLE
"Event History" empty, but job listed in "All Completed Jobs"

### ISSUE THREAD

**Issue by jkrenge** [jhuckaby/Cronicle#499]
## Summary

> **1.**

Event `el3oivykgvp` is scheduled for execution once per day _(see `#Schedule?sub=edit_event&id=el3oivykgvp`)_
<img width="686" alt="Screen Shot 2022-05-30 at 10 50 07" src="https://user-images.githubusercontent.com/625618/170955180-ce0b55d8-6a66-4887-bf14-c30fc0601e1a.png">

> **2.**

I can see execution with job id `jl3s32hlm2i` in "All Completed Jobs" _(see `#History?sub=history&offset=25&limit=25`)_
<img width="1422" alt="Screen Shot 2022-05-30 at 10 43 20" src="https://user-images.githubusercontent.com/625618/170955529-6822ea53-97d3-41bf-a7fb-92838ab9692c.png">

> **3.**

I also can view the details & logs for that job id _(see `#JobDetails?id=jl3s32hlm2i`)_
<img width="530" alt="Screen Shot 2022-05-30 at 10 53 57" src="https://user-images.githubusercontent.com/625618/170955823-bfcff3ea-e51c-4ffe-bcc8-d51ed69b5329.png">

> **4.**

But the event history for that specific event is empty _(see `#History?sub=event_history&id=el3oivykgvp`)_
<img width="835" alt="Screen Shot 2022-05-30 at 10 55 19" src="https://user-images.githubusercontent.com/625618/170956180-df8d5c86-3579-4f19-87eb-13342acbaa5e.png">

## Steps to reproduce the problem

Unfortunately, I cannot reproduce this consistently

* Setup: Single Primary with Workers
* 2 server groups:
  * "Backend" are servers in an auto-scaling group that register and deregister as worker through the API
  * "Primary" is just the primary node
* Event history is missing both for jobs that are run on either groups
* Not a definitive finding: It seems to be correlated with the frequency of the job execution: jobs run every 30mins have an event history, longer schedules don't
* I also have 14,594 of job executions already, maybe that is an issue?

<img width="346" alt="Screen Shot 2022-05-30 at 11 07 52" src="https://user-images.githubusercontent.com/625618/170958260-8b746b16-c357-486e-97b4-f52cd66839d1.png">

## Your Setup

Setup type: Single Primary with Workers

* 1 static primary instance that never changes
* Multiple worker nodes that register and deregister when they are ready to perform jobs, their scaling is happening through an AWS Auto Scaling Group
* Data is stored on S3

### Operating system and version?

Ubuntu 20.04.4 LTS

### Node.js version?

v16.15.0

### Cronicle software version?

Version 0.9.7

### Are you using a multi-server setup, or just a single server?

Single Primary with Workers

### Are you using the filesystem as back-end storage, or S3/Couchbase?

S3 storage

### Can you reproduce the crash consistently?

No

## Log Excerpts

-/-

**Comment by mikeTWC1984** [comment]
Probably file with event history is missing. Check files under data/logs/. I guess there should be json files with eventid names.

**Comment by jkrenge** [comment]
> Probably file with event history is missing. Check files under data/logs/events/. I guess there should be json files with eventid names.

**Comment by jkrenge** [comment]
If I understand correctly, those files would be written in:

[lib/job.js#L1329-L1331](https://github.com/jhuckaby/Cronicle/blob/master/lib/job.js#L1329-L1331)
```js
this.storage.enqueue( function(task, callback) {
	self.storage.listUnshift( 'logs/events/' + job.event, stub, callback );
});
```

That references to [listUnshift of jhuckaby/pixl-server-storage](https://github.com/jhuckaby/pixl-server-storage/blob/master/docs/API.md#listunshift), which makes sense because as per docs:
> If the list doesn't exist, `listUnshift()` will create it. 

in [`listUnshift`](https://github.com/jhuckaby/pixl-server-storage/blob/2161546301ab267996402ff9271f0367c77c3059/list.js#L229-L232), `_listLoad` is called:
```js
self._listLoad(key, create_opts, function(err, data) {
	list = data; 
	callback(err, data);
} );
```

I know my instance entered this function because the logs say so:
[jhuckaby/pixl-server-storage:list.js#L53](https://github.com/jhuckaby/pixl-server-storage/blob/master/list.js#L53)
```js
this.logDebug(9, "Loading list: " + key);
```

And my logs have the same flow:
```
...[Storage][debug][9][Unshifting 1 items onto beginning of list: logs/events/el2vtedh31s][]
...[Storage][debug][9][Requesting lock: |logs/events/el2vtedh31s][]
...[Storage][debug][9][Locked key: |logs/events/el2vtedh31s][]
...[Storage][debug][9][Loading list: logs/events/el2vtedh31s][]
...[Storage][debug][9][List could not be loaded: logs/events/el2vtedh31s: AccessDenied: Access Denied][]
...[Storage][debug][9][Unlocking key: |logs/events/el2vtedh31s (0 clients waiting)][]
```

But as I can see, I do not enter the code block that creates the list, because for me the condition `err.code == "NoSuchKey"` does not return true. And the error block tells me `AccessDenied: Access Denied`.

This is odd, because if I create the file manually it works. So the read generally works, but fails somehow for this case. So I'm diving deeper into `get()`. I am on S3, therefore looking at this engine. Logs of my S3 engine:
```
...[S3][debug][9][Fetching S3 Object: cronicle/logs/events/el2vtedh31s][]
...[S3][error][s3][Failed to fetch key: cronicle/logs/events/el2vtedh31s: Access Denied][{"message":"Access Denied","code":"AccessDenied","region":null,"time":"2022-11-19T00:00:01.354Z","requestId":"...","extendedRequestId":"...","statusCode":403,"retryable":false,"retryDelay":15.61043420700785}]
```

I'll investigate further tomorrow why a read of a non-existing object gives me an `Access Denied`.

**Comment by jkrenge** [comment]
I found the issue, and it's overwhelmingly obvious: the user I use to access S3 had incorrect access rights.

`Effect` and `Action` are okay...
```json
"Effect": "Allow",
"Action": "s3:*",
```

...but `Resource` has to be:
```json
"Resource": [
    "arn:aws:s3:::my-bucket",
    "arn:aws:s3:::my-bucket/*"
]
```

And not like it was before only `"Resource": "arn:aws:s3:::my-bucket/*"`.

Solved ✅
