### ISSUE TITLE
How to clean history logs safely ?

### ISSUE THREAD

**Issue by iambocai** [jhuckaby/Cronicle#5]
RT,  is there any suggestions? it seems all run history stored in logs dir, is it safe to complete erase everything under that dir  ?

**Comment by jhuckaby** [comment]
Sure, you can periodically delete everything in the log dir if you want, and that shouldn't break anything, but Cronicle does come with a nightly log archiver feature, if you want to use it.  Just set this config param to a destination directory path, and all the logs will be gzipped, date/time stamped and stored there for you, wiping the logs directory as it does it:

https://github.com/jhuckaby/Cronicle#log_archive_path

### log_archive_path

Every night at midnight (local server time), the logs can be archived (gzipped) to a separate location.  This parameter specifies the path, and the directory naming / filenaming convention of the archive files.  It can utilize date placeholders including `[yyyy]`, `[mm]` and `[dd]`.

This can be a partial path, relative to the Cronicle base directory (`/opt/cronicle`) or a full path to a custom location.  It defaults to `logs/archives/[yyyy]/[mm]/[dd]/[filename]-[yyyy]-[mm]-[dd].log.gz`.

**Comment by iambocai** [comment]
It works, thanks @jhuckaby ! I should read the manual first, hah~

**Comment by healthiansdotcom** [comment]
Is there any way to move the archived files to S3 to free-up disk space on the local disk?

**Comment by jhuckaby** [comment]
@healthiansdotcom That feature is coming in Cronicle v2, but for v1 you can do it fairly easily with the AWS CLI, assuming you have that installed.  Add this to a crontab or Cronicle shell event to run nightly:

```
aws s3 cp /opt/cronicle/logs/archives s3://YOUR_BUCKET/YOUR_PATH/
rm -rf /opt/cronicle/logs/archives/*
```

The logs are archived every night at midnight, so it's better to avoid that hour, and run this later in the morning, maybe 3 AM.

Hope this helps!
