### ISSUE TITLE
Cannot read property 'child' of undefined

### ISSUE THREAD

**Issue by alexbogias** [jhuckaby/Cronicle#53]
## Summary
It was working without a problem and now this...

## Steps to reproduce the problem
I just try to start cronicle: /opt/cronicle/bin/control.sh start

## Your Setup
3 x 3 Magento crons 

### Operating system and version?
Debian Linux 9 Linux 4.9.0-5-amd64 on x86_64

### Node.js version?
v9.3.0

### Cronicle software version?
Latest v0.7.6

### Are you using a multi-server setup, or just a single server?
Single Server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
back-end storage

## Log Excerpts
TypeError: Cannot read property 'child' of undefined
    at constructor.abortLocalJob (/opt/cronicle/lib/job.js:869:14)
    at constructor.abortJob (/opt/cronicle/lib/job.js:795:9)
    at constructor.monitorAllActiveJobs (/opt/cronicle/lib/job.js:1486:10)
    at /opt/cronicle/lib/engine.js:256:10
    at /opt/cronicle/lib/job.js:1668:18
    at ChildProcess.exithandler (child_process.js:264:7)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by jhuckaby** [comment]
Hello, and thank you for the bug report.  This is a very strange crash -- one I have never seen before.  Your stack trace tells me that Cronicle was in the middle of trying to abort one of your jobs when it crashed.  It looks like the job ran too long.  I would like to get more information, so I can attempt to reproduce your exact setup here.

Can you possibly provide me the last 1,000 or so lines of your `/opt/cronicle/logs/Cronicle.log` file, leading up to the crash?  This log may contain sensitive information, so feel free to audit / censor, or you can PM it to me via e-mail: jhuckaby_AT_gmail_DOT_com.

Anything else you can tell me would be greatly helpful, such as more information about the job that exceeded its max run time.  For example, which Plugin you were using (Shell Plugin?  Custom Plugin?), and how long it was running, what your max timeout was set at, and the concurrency setting.

Thanks!

**Comment by jhuckaby** [comment]
Okay @alexbogias, thanks for your e-mail.  I received the log excerpt, and I believe I see what may be going on here.  It looks like there may actually be two separate crashes.  Your Cronicle daemon died or crashed at 2018-01-05 07:17:00 with no obvious log message that I can see.  But then, when it was starting back up 3 hours later, at 10:43:08, it crashed again.  I believe the stack trace you pasted above is from the 2nd crash, when Cronicle was trying to start back up.

The bug I found and fixed deals with the second crash, which is a weird race condition when you have detached jobs that were running, and the main service gets restarted, but the detached jobs completed while it was down.  Then, when it is starting back up and trying to recover its jobs, the time delta was such that they exceeded their max time as well.  So Cronicle was getting confused and trying to abort the jobs that already completed.

Anyway, I have released [Cronicle v0.7.7](https://github.com/jhuckaby/Cronicle/releases/tag/v0.7.7) just now, which fixes the weird detached restart timeout bug.  If you [upgrade](https://github.com/jhuckaby/Cronicle#upgrading-cronicle) to this version, it should be happier now.  However, from your log excerpt I think something ELSE may have caused the original crash, which eventually led us to this 2nd crash here.

Do you see anything else in your `crash.log` file besides that one stack trace you pasted?  Anything on or around 2018-01-05 07:17:00?

Thanks again for the issue report and the follow-up log data.

**Comment by alexbogias** [comment]
Thanks a lot @jhuckaby it looks ok with v0.7.7 now! I dont see anything else on crash log. Maybe it overwrites all crashes before
