### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by alreadylostmyself** [jhuckaby/Cronicle#54]
## Summary

i've got this error `Failed to send e-mail for job: jjci4gtu923: my@email.com: Error: self signed certificate`
On every job
I not see any issues about that, so maybe it's little bug?

## Steps to reproduce the problem

Really dont know

## Your Setup

1 master server, 2 slaves

### Operating system and version?

Debian 9.3

### Node.js version?

9.3.0

### Cronicle software version?

0.7.8

### Are you using a multi-server setup, or just a single server?

Single Master with Slaves

**Comment by jhuckaby** [comment]
You need to set this configuration parameter:

https://github.com/jhuckaby/Cronicle#ssl_cert_bypass

**Comment by Servod** [comment]
Hello. I'm sorry, I have the same problem. In my dockerfile, I specified the following parameters to set environment variables, just in case:
```
    ENV     CRONICLE_ssl_cert_bypass 1
    ENV     CRONICLE_NODE_TLS_REJECT_UNAUTHORIZED 1
    ENV     NODE_TLS_REJECT_UNAUTHORIZED 1
    ENV     CRONICLE_web_hook_custom_opts__rejectUnauthorized 1
    ENV     CRONICLE_web_hook_ssl_cert_bypass 1
```
but none of them work. I still get error messages when the event tries to send an email:
Failed to send e-mail for job: jlo8jovtlqx: Error: self signed certificate.
