### ISSUE TITLE
Import jobs programmatically

### ISSUE THREAD

**Issue by dry4ng** [jhuckaby/Cronicle#541]
I would like to keep all job definitions in a source control. Is there a way to programmatically import jobs as crontab/json either during startup or through API?

**Comment by jhuckaby** [comment]
Check out [Data Import and Export](https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#data-import-and-export) in the docs.

If you export your data, you can check that file into source control.  It's just a text file.  You can also edit it and remove everything except the schedule data if you want.

The format is line-delimited JSON, but each line starts with a storage key, followed by a ` - ` (space dash space).  Also, it is commented at the top (shell-style comments).
