### ISSUE TITLE
Want to remove unnecessary job data frequently

### ISSUE THREAD

**Issue by adisapphire** [jhuckaby/Cronicle#548]
Cronicle job data has so much of folders and files instead i had restricted job_data_expire_days to 1. is it normal or am i missing something, i want to remove the job data frequently without manual interference so that my server is not store un-necessary data.

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/26599651/199964930-7a75c471-a56e-4a2f-b7e4-d7ed47d2ac8e.png">

**Comment by jhuckaby** [comment]
Yes this is as designed.  Cronicle is a database, so it writes many files to disk, to manage and index its lists and job logs.  Those hash directories you're seeing (00, 01, 02, 03) are designed to reduce load on the filesystem (so there aren't too many files in one single directory).

If you are scaling so high as this is becoming a problem, I recommend using a different storage backend like S3, which can easily handle this sort of thing.

Setting `job_data_expire_days` to 1 is just fine.  That's entirely up to you.  Just note that the configuration setting only affects new jobs -- it doesn't retroactively reset the expiration on old completed jobs.  So it may be a while before all those existing files and directories are actually deleted.
