### ISSUE TITLE
storage engine's runMaintenance won't run until nothing to clean up

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#555]
Just an observation. I noticed that runMaintenance  function for specific storage engine is never executed on fresh installs. I believe that's because clean up  queue is empty (as far as I understand first clean up will occur after 180 days by default)
Until then,  "err" variable at this line will always have some value (like list not found):
https://github.com/jhuckaby/pixl-server-storage/blob/master/storage.js#L706
so this code will never run
https://github.com/jhuckaby/pixl-server-storage/blob/master/storage.js#L718
I was working on a plugin which requires some maintenance (not related to expired records), so it might be an issue in this case.

**Comment by jhuckaby** [comment]
Good catch, thank you.  I'll address this in the next release of `pixl-server-storage`.

**Comment by jhuckaby** [comment]
Fixed in `pixl-server-storage@3.1.1`
