### ISSUE TITLE
[Feature Request] Ability to use GCloud MySQL as database

### ISSUE THREAD

**Issue by HamiltonWang** [jhuckaby/Cronicle#56]
Google Cloud is getting popular these days, is it possible to include GCLoud MySQL as one of the supported database? Thanks a lot.

**Comment by jhuckaby** [comment]
Thanks for the feature request!  Unfortunately, Cronicle wasn't designed to use a relational database.  It's really only meant to use a key/value store, like a NoSQL DB or a filesystem, which can store both JSON records and huge binary files (up to 100MB or more).  MySQL just isn't meant for this kind of thing.

If Google's cloud has a service similar to Amazon's S3, that might be more suitable.  Unfortunately I don't know anything about G's service offering.

**Comment by HamiltonWang** [comment]
I see your point. How about MongoDB or Redis? Or something that is free?

**Comment by jhuckaby** [comment]
Yup!  Someone has already submitted a PR for MongoDB support:

https://github.com/jhuckaby/pixl-server-storage/pull/1

I need to find the time to install MongoDB and test this, then I can accept it.  Redis is also on my TODO list.

**Comment by HamiltonWang** [comment]
Good! thanks!

**Comment by tushar9953** [comment]
Hi @jhuckaby 

Any plans for MongoDB?
