### ISSUE TITLE
Multiple Web Hooks URLs

### ISSUE THREAD

**Issue by Punkado** [jhuckaby/Cronicle#564]
Hello,

Is there a option to setup different web hooks URLs for the job_start, job_complete and job_failure? 

The difference between the URLs would not be so big, for example, the job_complete would be https://hook.domain.com and the job_start would be https://hook.domain.com/start

I tried to play around with the web_hook_text_templates in the config.json but it didn't work.

Thanks for the amazing tool.

**Comment by jhuckaby** [comment]
This feature is included in Cronicle v2.0 (Orchestra), which is coming in 2023, but I'm sorry to say there's no way to do it in Cronicle v1.

However, if you parse the JSON payload sent by the web hook HTTP POST, the `action` property will be set to `job_start` for jobs starting, and `job_complete ` for jobs completing.  And for the latter, you can determine success or failure by looking at the `code` property.

Reference: https://github.com/jhuckaby/Cronicle/blob/master/docs/WebUI.md#event-web-hook

**Comment by Punkado** [comment]
Thanks for the answer, i will wait for the version 2.0.
