### ISSUE TITLE
S3 compatible storage for minio

### ISSUE THREAD

**Issue by harshgpt816** [jhuckaby/Cronicle#569]
## Summary

Cronicle is a really great product and it does support S3 storage. The problem here is that there are many s3 compatible industry proven object storage in this case i am trying to use min.io self hosted cluster as a storage for logs.  

As the support for S3 is already present, there are just minor tweeks required to change the s3 config to direct the storage to min.io cluster for object storage.

## Your Setup

My setup includes a 3 node croncle cluster running as container on proxmox self hosted cloud.

### Operating system and version?

Ununtu 22.04 containers on proxmox.

**Comment by jhuckaby** [comment]
I've never used minio, but I believe I've seen someone use a config setup like this:

```json
    "Storage": {
        "engine": "S3",
        "AWS": {
            "endpoint": "http://minio:9000",
            "endpointPrefix": false,
            "forcePathStyle": true,
            "region": "us-east-1",
            "hostPrefixEnabled": false,
            "credentials": {
                "secretAccessKey": "minioadmin",
                "accessKeyId": "minioadmin"
            },
            "correctClockSkew": true,
            "maxRetries": 5,
            "httpOptions": {
                "connectTimeout": 5000,
                "timeout": 5000
            }
        },
        "S3": {
            "fileExtensions": true,
            "params": {
                "Bucket": "demo"
            }
        }
    },
```

Copied from: https://github.com/mikeTWC1984/s3engine

**Comment by harshgpt816** [comment]
Thank you for such a quick response, I will try this and update my observation soon.

**Comment by harshgpt816** [comment]
This is been great!, I used the above shared config in "/opt/cronicle/conf/config.json" and first the server showed me "waiting for master server", but after few manual restarts it worked. 

You have been such helpful @jhuckaby .

Thank you. 

Please resolve this issue.
