### ISSUE TITLE
forgot password always shows timeout

### ISSUE THREAD

**Issue by hariprasadiit** [jhuckaby/Cronicle#57]
First of all thanks for the awesome project.

## Summary

server times out when sending password reset email

## Your Setup
```
 "smtp_hostname": "smtp_server",
    "smtp_port": 2525,
    "mail_options":{
        "host": "smtp_server",
        "port": 2525,
        "secure": false,
        "auth": {
            "user": "user",
            "pass": "pass"
        }
    },
```

### Operating system and version?

Ubuntu 16.04

### Node.js version?

8.9.4

### Cronicle software version?

0.8.1

### log
```
[1520363332.97][2018-03-06 19:08:52][cron.vizmoconnect.com][User][debug][6][Successfully created recovery key][]
[1520363452.984][2018-03-06 19:10:52][cron.vizmoconnect.com][User][error][email][Failed to send e-mail: Error: Connection timeout][]
[1520363452.984][2018-03-06 19:10:52][cron.vizmoconnect.com][User][error][email][Connection timeout][]
```

 I've tested my smtp server using telnet on the same server and it's working. but unable to send forgot password email.

**Comment by jhuckaby** [comment]
Thank you for the issue report.  I believe I have found the source of the bug, and will be pushing out a new version with a fix shortly.

**Comment by jhuckaby** [comment]
Version 0.8.2 released, which should fix this bug: 
https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.2

Thanks!
