### ISSUE TITLE
A command line option to clean the storage

### ISSUE THREAD

**Issue by audetto** [jhuckaby/Cronicle#574]
I recently had this issue where the data storage filled the available space making the server unusable.
I tried to change `list_row_max` and `job_data_expire_days`, then restarted the server hoping that it would reduce the size, but nothing.

Tried as well to force some maintenance, but this did not help either.

I wished there was a command like "delete everything older than 1 month", but it does not exist.

Eventually I did a full reset.
Was there a better way to force cronicle to garbage collect old entries in the data storage?

**Comment by jhuckaby** [comment]
Using the local filesystem plugin?  You can do something like this:

```
find /opt/cronicle/data/jobs -mtime +30 -type f -delete
```

**Comment by audetto** [comment]
Good to know, thanks.
