### ISSUE TITLE
Can't change the configuration without stopping

### ISSUE THREAD

**Issue by arnoo** [jhuckaby/Cronicle#577]
I wish I could hot-reload the Cronicle config file, or even better, change the configuration with a command line call.

My current use case is that I have a large job queue and wish I could use a cron job to set max_jobs to a higher value at night only. Restarting Cronicle implies stopping the currently running processes.

During the first days of our current Cronicle use, I also wished for this feature a few times as I was tweaking the parameters and was not fond of always stopping running jobs to reload the config.

**Comment by jhuckaby** [comment]
You CAN change the config.json file, and it is indeed hot-reloaded.  It takes about 10 seconds to detect a change on disk and reload the file.

```
[1676426356.365][2023-02-14 17:59:16][mini.local][928][Cronicle][debug][2][Configuration was reloaded][{"base_app_url":"http://mini.local:3012","email_from":"admin@localhost","smtp_hostname":"localhost","smtp_port":25...snip...}]
```

Note that SOME configuration properties require a full restart, such as the HTTP web server listening port and the Storage engine.  But most properties, including [max_jobs](https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#max_jobs), are supported for hot-reload.

**Comment by arnoo** [comment]
Awesome, thanks a lot !
