### ISSUE TITLE
How to set E-mail configuration via environment variables?

### ISSUE THREAD

**Issue by USMortality** [jhuckaby/Cronicle#589]
How do you provide the e-mail configuration instead of via config.json, via environment variables? Thanks!

**Comment by jhuckaby** [comment]
See: https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#environment-variables

**Comment by USMortality** [comment]
Perfect, that worked in my Docker container:
```
ENV CRONICLE_mail_options__auth__user=${SENDINBLUE_USER}
ENV CRONICLE_mail_options__auth__pass=${SENDINBLUE_PASS}
```
Thanks!
