### ISSUE TITLE
Correct way to send variable parameters to a program started by Cronicle

### ISSUE THREAD

**Issue by carcamano** [jhuckaby/Cronicle#59]
Hi Mr. Huckaby,

Thank you for this amazing job scheduler!! You Rock!!

Sorry for the noob question, but I checked docs, Issues and source code and didn't figure out the best way to send variable parameters to a program started by Cronicle.

I have a program build in Go, and I want to start it with a few params like follow:
```yalm
xfersmart -env $ENV -flow $FLOW $PARAM $DEBUG
```
If you prefer, SS:
![image](https://user-images.githubusercontent.com/11354012/38053659-17c79f3c-32ab-11e8-8ea6-cc1c8ac4b2c8.png)

This "plugin" works fine and any variable param is passed my program. The problem is, every execution is marked with error on my "Event History" even if it has been executed fine, something like that:
![image](https://user-images.githubusercontent.com/11354012/38053970-e979e2f6-32ab-11e8-8739-d707323f4449.png)

So, if you have a minute please point me a way about how can I implement this plugin..

Thank you again!

**Comment by jhuckaby** [comment]
Hey there, thank you for the kind words!

This is actually "as designed" behavior.  Cronicle Plugins are expected to communicate with JSON messages.  Cronicle prints a JSON message to your executable's STDIN, and your executable is expected to print some JSON to its STDOUT.  This is all explained in the [Writing Plugins](https://github.com/jhuckaby/Cronicle#writing-plugins) section of the docs.

JSON is how your Plugin communicates things like progress (for the progress percentage indicator), performance metrics, and also **successful completion and errors**.  What is happening in your case is that your `xfersmart` executable isn't printing any JSON to STDOUT, so Cronicle thinks that the Plugin is broken.

You basically have two options here.  First, you can change your `xfersmart` executable to print some JSON to STDOUT when it completes.  The absolute bare minimum required to signal a "successful" completion to Cronicle is to print this very simple JSON message to STDOUT right before you exit:

```js
{ "complete": 1 }
```

That's it.  That little snippet is all Cronicle needs to assume your Plugin "succeeded", and will show a green checkmark and report the job as success in the event history.  This is all explained in the [JSON Output](https://github.com/jhuckaby/Cronicle#json-output) section of the docs.

Alternatively, if you don't want to change your `xfersmart` executable, or don't have access to the source code, you should consider using Cronicle's built-in [Shell Plugin](https://github.com/jhuckaby/Cronicle#built-in-shell-plugin) instead.

The Shell Plugin handles all the basic JSON communication with Cronicle, and you can execute any arbitrary shell command(s) you want, and they don't have to emit any JSON or anything.  They can just run, and the exit code signals success or error.

If you want to add special parameters to the Shell Plugin, as in your screenshot above, then you can simply duplicate it, using the "Copy Plugin" button.

Hope this helps!
