### ISSUE TITLE
Cronicle Keeps shutting down

### ISSUE THREAD

**Issue by sudhakovid** [jhuckaby/Cronicle#602]
## Summary

Cronicle keeps shutting down often by itself every couple of hours or so.

## Your Setup

Installed and configured cronicle as per the recommended steps from the git.

### Operating system and version?

CentOS Linux release 7.4.1708 (Core)

### Node.js version?

node version 16.20.0

### Cronicle software version?

cronicle v0.9.21

### Are you using a multi-server setup, or just a single server?

Single Server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
S3 

### Can you reproduce the crash consistently?
It does fail automatically. Whenever, i try hitting up my url it gives me a bad gateway and we have to restart cronicle.

## Log Excerpts

Below is log from Cronicle.log:

[Cronicle][debug][2][Caught SIGTERM][]
[Cronicle][debug][2][Shutting down][]
[Cronicle][debug][9][Deleting PID File: logs/cronicled.pid: <PID>][]
[Cronicle][debug][3][Stopping component: Cronicle][]
[Cronicle][debug][2][Shutting down Cronicle][]
[Cronicle][debug][9][Closing client socket: aLniuHVz6l_D-a4qAAAB][]
[Cronicle][debug][5][Socket.io client disconnected: aLniuHVz6l_D-a4qAAAB (IP: ::ffff:127.0.0.1)][]
[Cronicle][debug][9][Closing client socket: qQh4RbwWqvEG3KrqAAAD][]
[Cronicle][debug][5][Socket.io client disconnected: qQh4RbwWqvEG3KrqAAAD (IP: ::ffff:127.0.0.1)][]
[Cronicle][debug][3][Shutting down UDP server][]
[Cronicle][debug][3][Stopping component: User][]
[Cronicle][debug][3][Stopping component: API][]
[Cronicle][debug][3][Stopping component: WebServer][]
[Cronicle][debug][3][Stopping component: Storage][]
[Cronicle][debug][2][Shutdown complete, exiting][]

**Comment by jhuckaby** [comment]
This is the clue:

```
[Cronicle][debug][2][Caught SIGTERM][]
```

That means Cronicle received a SIGTERM (terminate) signal.  So something told it to shut down.  You probably have some other piece of software running on the server that is shutting down services for some reason.  Possibly to save memory?  Not sure.
