### ISSUE TITLE
Cronicle Doesn't start as root user

### ISSUE THREAD

**Issue by sudhakovid** [jhuckaby/Cronicle#603]
## Summary

There are couple of things to this issue. After I installed cronicle v0.9.21 as cronicle user it doesn't start as root user but stops. Also, same with systemctl command.

## Steps to reproduce the problem

Just installed cronicle as cronicle user logged in to server as root and switched user to cronicle before I install nodejs and cronicle

### Operating system and version?

Cent OS 7.4

### Node.js version?

16.20.0

### Cronicle software version?

0.9.21
### Are you using a multi-server setup, or just a single server?
Single Server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
S3
### Can you reproduce the crash consistently?
Yes
## Log Excerpts

[root@ip cronicle]# bin/control.sh start
bin/control.sh start: Starting up Cronicle Daemon...
Error: FATAL ERROR: Log directory could not be created: logs: Error: EEXIST: file already exists, mkdir 'logs'
    at __construct.__init (/opt/cronicle/node_modules/pixl-server/server.js:101:11)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server/server.js:393:8)
    at Object.<anonymous> (/opt/cronicle/lib/main.js:35:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
bin/control.sh start: Cronicle Daemon could not be started

[root@ip- cronicle]# systemctl start cronicle
Job for cronicle.service failed because the control process exited with error code. See "systemctl status cronicle.service" and "journalctl -xe" for details.
[root@ip cronicle]# systemctl status cronicle
● cronicle.service - Cronicle Distributed Task Runner
   Loaded: loaded (/etc/systemd/system/cronicle.service; static; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2023-05-16 13:36:32 UTC; 11s ago
  Process: 31622 ExecStart=/opt/cronicle/bin/control.sh start (code=exited, status=3)

systemd[1]: Failed to start Cronicle Distributed Task Runner.
systemd[1]: Unit cronicle.service entered failed state.
systemd[1]: cronicle.service failed.
systemd[1]: cronicle.service holdoff time over, scheduling restart.
systemd[1]: start request repeated too quickly for cronicle.service
systemd[1]: Failed to start Cronicle Distributed Task Runner.
systemd[1]: Unit cronicle.service entered failed state.
systemd[1]: cronicle.service failed.

**Comment by jhuckaby** [comment]
This error occurs with older versions of Node.js.  Are you absolutely sure you have Node.js v16 on the server?  Is it the version that runs when you type:

```
node --version
```

Cronicle will launch the Node.js version that is your PATH.

Try removing Cronicle, Node.js, and reinstalling everything as root.

🤷🏻‍♂️

**Comment by sudhakovid** [comment]
so here is the thing...the root user has node version 8 and cronicle user has node version 16.20.0 so probably I need to install node 16.20.0 as root user as well to make everything work?
