### ISSUE TITLE
Pass script using shell plugin using API

### ISSUE THREAD

**Issue by lissilla** [jhuckaby/Cronicle#604]
Is there a way to send a script with api to be executed when an event is created by api/app/create_event/v1  using the shell plugin without having to write it in the GUI once the event is created?

**Comment by jhuckaby** [comment]
Yes, specify a `params` object, and inside that a `script` property.

See: https://github.com/jhuckaby/Cronicle/blob/master/docs/APIReference.md#event-data-format

**Comment by lissilla** [comment]
> Yes, specify a `params` object, and inside that a `script` property.
> 
> See: https://github.com/jhuckaby/Cronicle/blob/master/docs/APIReference.md#event-data-format

Thank you!
