### ISSUE TITLE
Move the Scheduler Enabled button away from the Logout button

### ISSUE THREAD

**Issue by bthai** [jhuckaby/Cronicle#606]
## Summary

The problem is the _Scheduler Enabled_ is in the top right corner, right next to the Logout button. Users are accidentally unchecking the _Scheduler Enabled_ and ends up disabling all of our crons.

## Steps to reproduce the problem

When users are ready to logout by using the _Logout_ button, we have some users that accidentally uncheck the _Scheduler Enabled_ button unintentionally before actually logging out. 

## Your Setup

Version 0.8.47

### Are you using a multi-server setup, or just a single server?

Multi

### Are you using the filesystem as back-end storage, or S3/Couchbase?

S3

## Log Excerpts

![image](https://github.com/jhuckaby/Cronicle/assets/2927659/8c6707e0-910f-49fb-92b4-9856bc12c744)

**Comment by dheise-rheinenergie-trading-com** [comment]
I totally agree. It has also happened to us several times that we have stopped the scheduler unintentionally. A small dialog box (do you really want to stop the scheduler? - yes, no) would probably be enough here to be on the safe side.

**Comment by jhuckaby** [comment]
Fixed in v0.9.22: https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.22
