### ISSUE TITLE
Improvement in Documentation

### ISSUE THREAD

**Issue by rgcouto** [jhuckaby/Cronicle#615]
https://github.com/jhuckaby/Cronicle/blame/c3750f75f927bf8b85cf400ed179c3463a7ea38f/docs/Plugins.md#L87

The example for custom plugins success status message is not 100% correct. It is missing the code parameter.

You have `{ "complete": 1 }` but in reallity it should be `{ "complete": 1, "code":0 }`, otherwise you'll never have a successfull exit status.

Hope it helps other people :)

**Comment by jhuckaby** [comment]
Thanks, updated the doc.
