### ISSUE TITLE
Search with a digit only pattern only doesn't work

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [jhuckaby/Cronicle#624]
## Summary

Search for events doesn't work if the search pattern only contains digits.

## Steps to reproduce the problem

- fresh installation (0.9.27)
- create event "event_01a" and "event_02b"
- search for 01 or 02 doesn't work - nothing happens
- search for _01 or 01a or _02 or 02b works - the result is as expected

## Your Setup
fresh out of the box installation

### Operating system and version?
alma-linux 9

### Node.js version?
node 16

### Cronicle software version?
0.9.27

### Are you using a multi-server setup, or just a single server?
single

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem

### Can you reproduce the crash consistently?
yes

**Comment by jhuckaby** [comment]
Fixed in [v0.9.28](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.28).  Thank you!

**Comment by dheise-rheinenergie-trading-com** [comment]
Wow! That was a really fast bugfix! Thanks a lot and have a nice weekend.

**Comment by mikeTWC1984** [comment]
did you guys try it?  
```js
if (('keywords' in args) && words.indexOf(args.keywords.toString().toLowerCase()) == -1) continue;
```

When I applied this on my fork, it crashed the schedule page (console had "args.keywords is undefined" error).

 For some reason, the old code works ok (can search by numeric values). I might miss/mess something though (it's too late :)), but make sure it working on your end

**Comment by jhuckaby** [comment]
I always test my fixes.  It works great here:

<img width="1352" alt="Screenshot 2023-08-29 at 10 24 10 PM" src="https://github.com/jhuckaby/Cronicle/assets/700765/5c25e374-81f9-4186-be93-e5bc535b9780">

No errors in console:

<img width="1220" alt="Screenshot 2023-08-29 at 10 25 35 PM" src="https://github.com/jhuckaby/Cronicle/assets/700765/20d0b673-ebf6-4673-9fbe-26e4292851a4">

**Comment by dheise-rheinenergie-trading-com** [comment]
Works for me too. No errors:

![image](https://github.com/jhuckaby/Cronicle/assets/73586581/99dd63e1-1e59-4bbf-a1e6-ce09f648a4f5)

But I'm more likely waiting for the bugfix in your fork because we use your version in our company. 😁
