### ISSUE TITLE
Can "get_event_history" be made available 

### ISSUE THREAD

**Issue by dsturgilljr** [jhuckaby/Cronicle#636]
A way to query jobs that have run as a result of an event would be a very useful feature. It is available via the Cronicle UI. Is possible to get that added to the public API and added to the reference documentation?

Thanks!

**Comment by jhuckaby** [comment]
Please see: https://github.com/jhuckaby/Cronicle/issues/247

You can start using it right now.  I'll try to get it added to the docs for the next release.
