### ISSUE TITLE
Issue with Log Watcher when host name and URL for service aren't in same domain/subdomain

### ISSUE THREAD

**Issue by mrkcmo** [jhuckaby/Cronicle#640]
## Summary

I have an issue where the domain of the host is different from the domain of the Cronicle server. For example the hostname of the machine is "server1.zone.test.com" and the URL (DNS entry) for the Croncile server is "scheduler.test.com". The cert specified in the config.json is for the "scheduler.test.com" name and the "base_app_url" and "custom_live_log_socket_url" is set to "https://scheduler.test.com". Everything works fine expect when I go to the Log Watcher it always tries to use the hostname of the machine "server1.zone.test.com" and not the "custom_live_log_socket_url". 

## Steps to reproduce the problem

Use a sub domain for the server name and the main domain for the URL with main domain certificate and the live log will try and connect and fail as it states it is trying to connect to the server name in the sub domain which the certificate doesn't cover.

## Your Setup

Standalone

### Operating system and version?

CentOS7

### Node.js version?

16.20.2

### Cronicle software version?

0.9.30

**Comment by mrkcmo** [comment]
@jhuckaby not sure if you have seen this issue but I tried to follow where it breaks but can't seen to track it down. Looks like the "custom_live_log_socket_url" isn't getting applied to the start_live_watcher or the at least the UI isn't using it to try and connect to the live log feed. Thoughts?

**Comment by jhuckaby** [comment]
Well, I think the core issue here is that you're trying to use HTTPS/SSL.  Unfortunately, Cronicle v0.x doesn't support SSL.  People have gotten it to work "sort of", but I don't think the live log watcher system works at all under SSL.

Cronicle v2 (due out later this year) will fully support SSL, but in the meantime, check out the [cronicle-edge](https://github.com/cronicle-edge/cronicle-edge) fork, maintained by @mikeTWC1984.  I believe he has solved the log watcher issue by proxying it via the master server (so there is no need for a secondary websocket connection):

https://github.com/cronicle-edge/cronicle-edge#livelog-new-api

**Comment by mrkcmo** [comment]
@jhuckaby understood. I think the main issue that I am trying to work around is that the "custom_live_log_socket_url" setting doesn't seem to be honored. Could that be only when HTTPS/SSL is enabled? I was just thinking it might be worth checking if that gets passed through correctly as it appears it doesn't in my environment.

**Comment by jhuckaby** [comment]
Hmmm, are you putting `custom_live_log_socket_url` in the correct place in your config file?  It needs to go *inside* the `client` object.

In your browser, open up the dev console, and see if it is defined and set properly by typing:

```js
console.log( config.custom_live_log_socket_url );
```

**Comment by mrkcmo** [comment]
![image](https://github.com/jhuckaby/Cronicle/assets/32075075/8ad32ac5-6466-45fd-befc-b0f0baeb21a9)

Looks like it isn't defined. In the original config file it isn't under the "client" section it is just at the root level. Let me try moving it under the "client" block and see if that does it.

**Comment by mrkcmo** [comment]
I think I found it in a closed issue a while back and added it in the config file. It was before I went to HTTPS/SSL and therefore I just put it in the wrong place to be honest.
