### ISSUE TITLE
Workers must be on same port as master to be added.

### ISSUE THREAD

**Issue by seanford** [jhuckaby/Cronicle#641]
## Summary

Workers must be on same port as master to be added.

## Steps to reproduce the problem

Create a Master server and change the web port to 80.  Then install a worker server and make sure the secret keys match.  The server will show up in the Nearby Servers list, but Adding the server fails.  Why?  It seems that if the master server is using port 80, then the workers must as well.

Problem is that I want the Web interface to run on a dedicated LXC in Proxmox, which it is just fine, but I'd prefer if I could access it via port 80 instead of 3012.  It seems that the server list would benefit from an additional field identifying the port that the worker server is using.

## Your Setup

MAster Server running on Debian 12 LXC inside Proxmox...workers on various LXC containers and Docker containers.  Even have a worker server running inside a Unifi Console.

### Operating system and version?

See above.

### Node.js version?

v16.20.1

### Cronicle software version?

Version 0.9.30

### Are you using a multi-server setup, or just a single server?

Single Master, many workers.

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

### Can you reproduce the crash consistently?

No crash, just a bug in adding worker servers.

**Comment by jhuckaby** [comment]
Fixed in [v0.9.31](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.31).

Docs: https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#remote_server_port

**Comment by seanford** [comment]
Thank you.  For orchestra, it would be great to be able to change the port on a server by server basis, but this is perfect for my particular use case now.

**Comment by jhuckaby** [comment]
Orchestra turns the whole thing on its head.  In Orchestra, the worker servers connect to the master server, not the other way around.  It simplifies the whole thing, so there is only one single socket listener (per master), and the worker servers don't need to expose an incoming port at all.

So hopefully, this whole thing will just "go away" with Orchestra 😊

**Comment by seanford** [comment]
any updated timeline for a beta?   Just curious.

**Comment by jhuckaby** [comment]
Ugh, I apologize for lack of updates.  Life keeps getting in the way.  I am still working on it, and it's looking great so far, but the best I can do is still say "late 2023" 😬
