### ISSUE TITLE
Please add `package-lock.json` to the index

### ISSUE THREAD

**Issue by careyminaieva** [jhuckaby/Cronicle#656]
## Summary

Please, add your `package-lock.json` to the git index

## Steps to reproduce the problem

Downgrade to version `0.9.30`, try to install app as recommended with default config

## Your Setup

Arch Linux, Node.js LTS

### Operating system and version?

Arch Linux

### Node.js version?

LTS

### Cronicle software version?

0.9.30

## Log Excerpts

```
TypeError: Cannot read properties of undefined (reading 'listeners')
    at Server.attach (/opt/cronicle/node_modules/engine.io/build/server.js:654:34)
    at attach (/opt/cronicle/node_modules/engine.io/build/engine.io.js:53:12)
    at Server.initEngine (/opt/cronicle/node_modules/socket.io/dist/index.js:293:43)
    at Server.attach (/opt/cronicle/node_modules/socket.io/dist/index.js:232:14)
    at constructor.startSocketListener (/opt/cronicle/lib/comm.js:311:11)
    at constructor.startup (/opt/cronicle/lib/engine.js:117:8)
    at /opt/cronicle/node_modules/pixl-server/server.js:446:10
    at /opt/cronicle/node_modules/async/dist/async.js:3113:16
    at replenish (/opt/cronicle/node_modules/async/dist/async.js:1014:17)
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:998:17)
```

Basically, its now fixed in `lib/comm.js` as it seems, but it would be great to have frozen dependencies of first-level dependencies in `package-lock.json`.

**Comment by mikeTWC1984** [comment]
Good point. Just caught the same issue on my setup

**Comment by jhuckaby** [comment]
Ah damn, I didn't expect that anyone would upgrade dependencies without also upgrading Cronicle at the same time.  I did not foresee this complication.

Sorry about that.  The `listeners` thing was definitely a breaking change in pixl-server-web, and in retrospect I should have bumped that with semver major, but Cronicle was the ONLY app affected, so I thought I could get away with upgrading both at the same time.

Nope!

So sorry about that.  I'll try to clean this up.

**Comment by jhuckaby** [comment]
Okay, I just pushed [pixl-server-web v1.3.23](https://github.com/jhuckaby/pixl-server-web/releases/tag/v1.3.23) with a legacy fix for this issue.

I'll work on getting a package-lock.json file in place for Cronicle for future versions.  It's complicated because of my local dev setup.  I do NOT use package-locks at all, because all my local modules symlink to each other.  This is so I can work on multiple modules and apps at once without having to publish.  This works great for me, but it REALLY confuses npm.

I'll figure it out tho.

Thanks for finding this issue, and sorry for the inconvenience I have caused.

**Comment by jhuckaby** [comment]
Added package-lock.json in [v0.9.37](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.37).

**Comment by careyminaieva** [comment]
That's really great, @jhuckaby! :stars: 

I'm really grateful for your time and your work, it's just that I, personally, use hand-made Docker image for my project that needs Cronicle to run effectively and I just accidentally re-created image from scratch (because of  `--no-cache`) option when tried to make some changes to the Dockerfile :)
Didn't expect it to crash and noticed that you've added a fix in the recent changes to `lib/comm.js` file (just checked Github history), so I just upgraded first and then opened this issue just so similar inconveniences could be omitted in the future :))

Once again, thanks a lot! :pray:

**Comment by jhuckaby** [comment]
No worries at all, and thank you for finding this issue!  I completely missed it.
