### ISSUE TITLE
Crash: TypeError: Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by dropthemic** [jhuckaby/Cronicle#66]
## Summary
Cronicle crashes fatally when a child job does not exist. 

To fix: 
https://github.com/jhuckaby/Cronicle/blob/06a6e6c4e6313c59cec6d434fe5d1104e6ca3c72/lib/scheduler.js#L285

Change to:
`if (err || event == null) {`

It would be helpful if you fixed the api add/update event to validate the chain and give hard error if child job doesn't exist.

## Steps to reproduce the problem

1. Create two jobs: job1 and job2. Make job2 run after job1 completes. 
2. Delete job2.
3. Run job1. Crash.

### Operating system and version?
MacOS

### Node.js version?
v9.5

### Cronicle software version?
0.8.6

### Are you using a multi-server setup, or just a single server?
Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?
fs

### Can you reproduce the crash consistently?
Yes

## Log Excerpts

> pixl-server-storage/list.js:610
> 									if (criteria[k].test) {
> 									                ^
> 
> TypeError: Cannot read property 'test' of undefined
>     at /Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:610:26
>     at /Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:85:5
>     at constructor.get (/Users/bman/git/Cronicle/node_modules/pixl-server-storage/storage.js:326:11)
>     at constructor._listLoadPage (/Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:82:8)
>     at /Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:604:12
>     at Object.whilst (/Users/bman/git/Cronicle/node_modules/async/dist/async.js:5213:5)
>     at /Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:601:11
>     at /Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:58:5
>     at constructor.get (/Users/bman/git/Cronicle/node_modules/pixl-server-storage/storage.js:326:11)
>     at constructor._listLoad (/Users/bman/git/Cronicle/node_modules/pixl-server-storage/list.js:55:8)
>

**Comment by jhuckaby** [comment]
Fixed in HEAD revision, thanks for catching this!

Will add validating the chain event in the API to my TODO list.

**Comment by jhuckaby** [comment]
Should be fixed in [v0.8.7](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.7)
