### ISSUE TITLE
Failed to send e-mail for job. Error: self signed certificate.

### ISSUE THREAD

**Issue by Servod** [jhuckaby/Cronicle#662]
## Summary

Hello. I'm sorry to open this problem again, but I can't fix it.
I get error messages when the event tries to send an email:
Failed to send e-mail for job: jlo8jovtlqx: Error: self signed certificate.

### Operating system and version?

FROM  centos:7

### Node.js version?

v16.14.2

### Cronicle software version?

Version 0.9.37

### Are you using a multi-server setup, or just a single server?

single

In my dockerfile, I specified the following parameters in all variations, just in case, to set environment variables:
```
    ENV     CRONICLE_ssl_cert_bypass 1
    ENV     CRONICLE_NODE_TLS_REJECT_UNAUTHORIZED 1
    ENV     NODE_TLS_REJECT_UNAUTHORIZED 1
    ENV     CRONICLE_web_hook_custom_opts__rejectUnauthorized 1
    ENV     CRONICLE_web_hook_ssl_cert_bypass 1
```
but none of them work. I still get error messages when the event tries to send an email:
Failed to send e-mail for job: jlo8jovtlqx: Error: self signed certificate.

**Comment by mikeTWC1984** [comment]
You need to update mail configuration (pretty sure it comes from nodemailer package). Check this for example
https://stackoverflow.com/questions/46742402/error-self-signed-certificate-in-certificate-chain-nodejs-nodemailer-express

**Comment by Servod** [comment]
UPD: Problem solved. I change all options with "REJECT_UNAUTHORIZED" to 0 instead of 1 and it worked!
