### ISSUE TITLE
Success webhook called twice

### ISSUE THREAD

**Issue by jnewc** [jhuckaby/Cronicle#663]
## Summary

I have a basic stock configuration with one server that calls an internet webhook, and then calls a local webhook on Home Assistant if it succeeds.

When I run the event manually, I get a single run / job details in Cronicle as expected. However, Home Assistant receives the webhook twice (I've confirmed this by looking at the HA trace for the automation which show two trigger receipts in the same moment).

Is the duplicated webhook call a bug or have I set something up wrong.

## Steps to reproduce the problem

1. Install Home Assistant and Cronicle 
2. Create an automation in Home Assistant with a webhook trigger
3. Create an event with a success webhook call to the HA trigger
4. Run the event
5. Observe the traces for the automation in Home Assistant.

## Your Setup

Stock config. Installed in docker container on linux

### Operating system and version?

Docker on latest Ubuntu Server 

### Node.js version?

18.16.0

### Cronicle software version?

0.9.23

### Are you using a multi-server setup, or just a single server?

Single server

**Comment by jhuckaby** [comment]
Grep your logs to see all the web hook requests Cronicle sends out:

```sh
grep -i "web hook" /opt/cronicle/logs/Cronicle.log
```

This will also include the responses.

**Comment by jnewc** [comment]
Thanks, based on the logs it does look like it's firing twice within a couple of seconds:

```
[1698512570.894][2023-10-29 01:02:50][main][1][Cronicle][debug][9][Firing web hook for job start: jloaaj3et0a: http://<REDACTED>/api/webhook/-BTyJ9feaih9uvj79Loae_Zx_][]
[1698512570.899][2023-10-29 01:02:50][main][1][Cronicle][debug][9][Web Hook Error: http://<REDACTED>/api/webhook/-BTyJ9feaih9uvj79Loae_Zx_: SyntaxError: Unexpected end of JSON input][]
[1698512572.316][2023-10-29 01:02:52][main][1][Cronicle][debug][9][Firing web hook for job complete: jloaaj3et0a: http://<REDACTED>/api/webhook/-BTyJ9feaih9uvj79Loae_Zx_][]
[1698512572.328][2023-10-29 01:02:52][main][1][Cronicle][debug][9][Web Hook Error: http://<REDACTED>/api/webhook/-BTyJ9feaih9uvj79Loae_Zx_: SyntaxError: Unexpected end of JSON input][]
```

It also appears to be trying to parse a JSON response, but HA is unfortunately incapable of providing one. I'm not 100% if that's what is leading to the duplication (e.g. due to a retry)

**Comment by jhuckaby** [comment]
Yup, so this is as designed behavior.  Cronicle fires web hooks for multiple different actions, including jobs starting, AND jobs completing.  What you're seeing here in your log is a web hook firing for the job starting, and one for the job completing.

https://github.com/jhuckaby/Cronicle/blob/master/docs/WebUI.md#event-web-hook

You have to look inside the JSON payload to see which `action` the web hook is being sent for.

**Comment by jnewc** [comment]
Perfect, fixed in HA with a condition that checks the trigger payload. Thanks for your help.

For completeness, this is the (template type) condition I used:

```
{{ trigger.json.action == 'job_complete' }}
```
