### ISSUE TITLE
How to handle self-signed https request with http plugin?

### ISSUE THREAD

**Issue by Aavon** [jhuckaby/Cronicle#67]
I got the following error 
```
Job failed with error: Error: unable to verify the first certificate
```
It is necessary here to implement a new plugin that ingores the verification?

**Comment by jhuckaby** [comment]
You can add this feature to the existing HTTP Request Plugin.  Here are the instructions:

- Click on the "Admin" tab, then the "Plugins" side tab.
- Click on the "HTTP Request" Plugin to edit it.
- Click the "Add Parameter..." button.
- Add a new checkbox with this exact ID: `ssl_cert_bypass`:

<img width="518" alt="screenshot 2018-06-12 21 02 39" src="https://user-images.githubusercontent.com/700765/41329689-fa78bd0c-6e83-11e8-9b15-a44c93f37fec.png">

- Click "Add" to dismiss the dialog.
- Click "Save Changes" to save the Plugin.
- Go back and edit your scheduled event, and make sure you check the new checkbox:

<img width="225" alt="screenshot 2018-06-12 21 03 52" src="https://user-images.githubusercontent.com/700765/41329715-2738fa46-6e84-11e8-8511-5bef9a260c8e.png">

- Save the event and run it.

Hope this helps!

\- Joe

**Comment by Aavon** [comment]
Thanks! It works.
