### ISSUE TITLE
Possibility to autoremove hanging servers from servers list

### ISSUE THREAD

**Issue by marcispauls** [jhuckaby/Cronicle#674]
## Summary

First thank you for great tool - we cant wait for v2 and api support + some postgresql or mysql support on aws or any non s3 backend.

We are currently registering servers on container launch using nondocumented api.
All cool, but as its containerized happens that containers cycle etc and there would be awesome feature if we could:
1) autoremove such servers based on ttl
or
2) have an api to list all servers and then we could use the api to remove server

**Comment by mikeTWC1984** [comment]
Speaking of mysql/postgres/custom engines, you can try those
https://github.com/cronicle-edge/cronicle-edge/tree/main/engines
Need to install knex orm package first, and then SQL driver of your choice.

**Comment by marcispauls** [comment]
any way to do this? some surgery in db files etc?

**Comment by marcispauls** [comment]
Cool, will give a try.
To delete 2k pods manually nop tnx

**Comment by mikeTWC1984** [comment]
@jhuckaby  does cornicle v1 support admin-level API keys?

**Comment by jhuckaby** [comment]
@mikeTWC1984 Not officially, but I've had a few people ask so I described how to do it in a discussion thread.  You have to hack the DB a wee bit, but it works:

The process is described here: https://github.com/jhuckaby/Cronicle/discussions/479

At some point I'll just go ahead and add it to the UI, but I haven't had the time to really test it thoroughly.

(Orchestra supports this fully of course, and it's in the UI.)

**Comment by marcispauls** [comment]
@jhuckaby any way to get the status for the server as well in the call? I mean if its alive or not?

**Comment by jhuckaby** [comment]
@marcispauls If a server is offline it will have a `disabled` property set to true.  Otherwise you can assume it's online.

Orchestra doesn't have a link yet, sorry.  It's still unreleased.  But coming soon!

**Comment by marcispauls** [comment]
In /api/app/get_servers i cant see that info sadly :/

**Comment by jhuckaby** [comment]
It works fine for me.

```
http://mini.local:3012/api/app/get_servers?api_key=da323d6cb9c29a37a59bf95d1726920b&pretty=1
```

```json
{
	"code": 0,
	"servers": {
		"mini.local": {
			"hostname": "mini.local",
			"ip": "192.168.3.46",
			"master": 1,
			"uptime": 95,
			"data": {
				"cpu": 5.7,
				"mem": 57663488
			},
			"disabled": 0
		},
		"joework.local": {
			"hostname": "joework.local",
			"ip": "192.168.3.40",
			"master": 0,
			"uptime": 0,
			"data": {},
			"disabled": true
		}
	}
}
```

Notice the `"disabled": true` on the `joework.local` server.

Please note that it takes up to a minute to "realize" that a server has gone offline.

**Comment by marcispauls** [comment]
ehh, full moon :D works as you described. there was issue between chair and monitor

**Comment by marcispauls** [comment]
At the end i ended by creating job in cronicle itself:

```
#!/bin/sh

CRONICLE_API_KEY=apikeygoesthere
CRONICLE_HOST=http://127.0.0.1:3012

disabled_servers=$(curl -s "$CRONICLE_HOST/api/app/get_servers?api_key=$CRONICLE_API_KEY" | jq -r '.servers | with_entries(select(.value.disabled == true)) | keys[]')

if [ -n "$disabled_servers" ]; then
  echo "$disabled_servers" | while IFS= read -r disabled_server; do
    echo "Removing $disabled_server"
    curl -s "$CRONICLE_HOST/api/app/remove_server" -X DELETE -d "api_key=$CRONICLE_API_KEY&hostname=$disabled_server"
  done
fi
```
