### ISSUE TITLE
jobs log not found

### ISSUE THREAD

**Issue by hidakafinzelz** [jhuckaby/Cronicle#689]
I run many jobs here,
![1701919262348](https://github.com/jhuckaby/Cronicle/assets/131435470/35c49758-8417-40ae-b85d-96e557b6f929)
but not found the jobs log

this is callback post data
![1701919343625](https://github.com/jhuckaby/Cronicle/assets/131435470/c6ae80fd-6c1b-4231-8410-17b141b2aea7)

this is log path
![1701919368015](https://github.com/jhuckaby/Cronicle/assets/131435470/27466c60-56b5-4d96-94d9-67261775ef84)

**Comment by hidakafinzelz** [comment]
Thanks.
Where is path of this log file on the master server? 
I want download this log with api and with json format
.

**Comment by jhuckaby** [comment]
You didn't say which Storage Plugin you are using.  I'm assuming you are using the Filesystem Plugin?

If so, it's not that easy.  As I said above, the files are stored in a hash file format tree, with hexadecimal directories.  You should use the API, as I said above:

You can curl it like this:

```sh
curl -o LOG_FILE.txt "http://SERVER:PORT/api/app/get_job_log?id=JOB_ID"
```

Replace `SERVER` with your master server hostname, `PORT` with your port number (3012, etc.), and `JOB_ID` with the job ID.  This will download the log file and store it wherever you want.

It is "very difficult" to get access to the raw files on the filesystem, when you are using the Filesystem Storage Plugin.  They are stored in a cryptic, distributed, hashed file directory tree format like this:

```
/opt/cronicle/data/jobs/ff/ae/5a/ffae5a2df778d3780edf058aba5d0988.gz 
```

It is MUCH better to use the API as shown above.

**Comment by hidakafinzelz** [comment]
> You didn't say which Storage Plugin you are using. I'm assuming you are using the Filesystem Plugin?
> 
> If so, it's not that easy. As I said above, the files are stored in a hash file format tree, with hexadecimal directories. You should use the API, as I said above:
> 
> You can curl it like this:
> 
> ```shell
> curl -o LOG_FILE.txt "http://SERVER:PORT/api/app/get_job_log?id=JOB_ID"
> ```
> 
> Replace `SERVER` with your master server hostname, `PORT` with your port number (3012, etc.), and `JOB_ID` with the job ID. This will download the log file and store it wherever you want.
> 
> It is "very difficult" to get access to the raw files on the filesystem, when you are using the Filesystem Storage Plugin. They are stored in a cryptic, distributed, hashed file directory tree format like this:
> 
> ```
> /opt/cronicle/data/jobs/ff/ae/5a/ffae5a2df778d3780edf058aba5d0988.gz 
> ```
> 
> It is MUCH better to use the API as shown above.

Thanks for you replay.
Curl can resolve my problem.

By the way.
In addition to Filesystem Storage, it also supports other Storage Plugin? Like MongoDB, MySQL, PostSQL and so on.

**Comment by jhuckaby** [comment]
> In addition to Filesystem Storage, it also supports other Storage Plugin? Like MongoDB, MySQL, PostSQL and so on.

Currently S3 and Couchbase: https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#storage-configuration

**Comment by hidakafinzelz** [comment]
> > In addition to Filesystem Storage, it also supports other Storage Plugin? Like MongoDB, MySQL, PostSQL and so on.
> 
> Currently S3 and Couchbase: https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#storage-configuration

OK, Thanks.
