### ISSUE TITLE
[Question] Cronicle multi server installation

### ISSUE THREAD

**Issue by pioardi** [jhuckaby/Cronicle#69]
Cronicle multi server installation ( 3 processes on the same node , all three processes are master , i need high availability so i need more master servers and not one master with backups )  , need clarifications .
Basically I have all master servers  and they share the same file system .
I note that  a scheduled job it runs just once time , the process/instance change for different jobs ,  ( and I am very happy of this ) **, but I ' d like to know how Cronicle is handling this** , I ' m testing this on a low load and my fear is that the same job run on more istances on an high load .

Could you help me to understand how cronicle is handling this , please ?

Please find more details below ( if you need , i will share logs of all 3 instances)  , thanks in advance .

Operating system and version : 
 I' m deploying a docker image into kubernetes , so operating system is alpine ( linux distro for docker) .

Cronicle Version :
0.8.6

Storage :
I' m using a shared file system .

My setup : 

{
	"base_app_url": "http://localhost:3012",
	"email_from": "admin@localhost",
	"smtp_hostname": "localhost",
	"smtp_port": 25,
	"secret_key": "405d7bf2d46f1763b3bc3e2b023fa15a",

	"log_dir": "logs",
	"log_filename": "[component].log",
	"log_columns": ["hires_epoch", "date", "hostname", "component", "category", "code", "msg", "data"],
	"log_archive_path": "logs/archives/[yyyy]/[mm]/[dd]/[filename]-[yyyy]-[mm]-[dd].log.gz",
	"log_crashes": "1",
	"copy_job_logs_to": "",
	"queue_dir": "queue",
	"pid_file": "logs/cronicled.pid",
	"debug_level": 9,
	"maintenance": "04:00",
	"list_row_max": 10000,
	"job_data_expire_days": 180,
	"child_kill_timeout": 10,
	"dead_job_timeout": 120,
	"master_ping_freq": 20,
	"master_ping_timeout": 60,
	"udp_broadcast_port": 3014,
	"scheduler_startup_grace": 10,
	"universal_web_hook": "",

	"server_comm_use_hostnames": 0,
	"web_socket_use_hostnames": 0,

	"job_memory_max": 1073741824,
	"job_memory_sustain": 0,
	"job_cpu_max": 0,
	"job_cpu_sustain": 0,
	"job_env": {},

	"client": {
		"name": "Cronicle",
		"debug": 1,
		"privilege_list": [
			{ "id": "admin", "title": "Administrator" },
			{ "id": "create_events", "title": "Create Events" },
			{ "id": "edit_events", "title": "Edit Events" },
			{ "id": "delete_events", "title": "Delete Events" },
			{ "id": "run_events", "title": "Run Events" },
			{ "id": "abort_events", "title": "Abort Events" },
			{ "id": "state_update", "title": "Toggle Scheduler" }
		],
		"new_event_template": {
			"enabled": 1,
			"params": {},
			"timing": { "minutes": [0] },
			"max_children": 1,
			"timeout": 3600,
			"catch_up": 0,
			"queue_max": 1000
		}
	},

	"Storage": {
		"engine": "Filesystem",
		"list_page_size": 50,
		"concurrency": 4,

		"Filesystem": {
			"base_dir": "data",
			"key_namespaces": 1
		}
	},

	"WebServer": {
		"http_port": 3012,
		"http_htdocs_dir": "htdocs",
		"http_max_upload_size": 104857600,
		"http_static_ttl": 3600,
		"http_static_index": "index.html",
		"http_server_signature": "Cronicle 1.0",
		"http_gzip_text": 1,
		"http_timeout": 30,
		"http_regex_json": "(text|javascript|js|json)",
		"http_response_headers": {
			"Access-Control-Allow-Origin": "*"
		},

		"https": 1,
		"https_port": 443,
		"https_cert_file": "conf/ssl.crt",
		"https_key_file": "conf/ssl.key",
		"https_force": 0,
		"https_timeout": 30,
		"https_header_detect": {
			"Front-End-Https": "^on$",
			"X-Url-Scheme": "^https$",
			"X-Forwarded-Protocol": "^https$",
			"X-Forwarded-Proto": "^https$",
			"X-Forwarded-Ssl": "^on$"
		}
	},

	"User": {
		"session_expire_days": 30,
		"max_failed_logins_per_hour": 5,
		"max_forgot_passwords_per_hour": 3,
		"free_accounts": 0,
		"sort_global_users": 1,
		"use_bcrypt": 1,

		"email_templates": {
			"welcome_new_user": "conf/emails/welcome_new_user.txt",
			"changed_password": "conf/emails/changed_password.txt",
			"recover_password": "conf/emails/recover_password.txt"
		},

		"default_privileges": {
			"admin": 0,
			"create_events": 1,
			"edit_events": 1,
			"delete_events": 1,
			"run_events": 0,
			"abort_events": 0,
			"state_update": 0
		}
	}

}

**Comment by jhuckaby** [comment]
Oh dear, you're in for a lot of trouble here.  Cronicle only supports a **single master server** at any given time.  You cannot have multiple master servers sharing the same storage system.  It will inevitably step all over itself and cause corruption and disasters.

> I note that a scheduled job it runs just once time , the process/instance change for different jobs , ( and I am very happy of this ) , but **I ' d like to know how Cronicle is handling this**

In short, **it is not**.  You are surviving by pure random chance.  Eventually, probably very soon, Cronicle will corrupt the file data by having both your master servers writing the same file at the same time.  I suspect you already have lots of corruption already, but it just hasn't resulted in a crash (yet).  It will, trust me.  Cronicle is not designed for this.

Please, [read the documentation](https://github.com/jhuckaby/Cronicle#single-master-with-slaves) on how to run multiple Cronicle servers.  You need to have a **single master server**, and then you can have one or more slave servers that receive commands from the master.

**Comment by pioardi** [comment]
Hi @jhuckaby  thanks for your response ,
I realized that multiple instances of cronicle (as master)  will run the same job several times, but removing the cache this is not happening .
Very thanks for your response , maybe i will try to change storage system in order to support multiple masters.

Thanks again .
