### ISSUE TITLE
Install on Shared Hosting cPanel with NodeJS capability

### ISSUE THREAD

**Issue by DmitryAdam** [jhuckaby/Cronicle#692]
Hi, can we install it on shared hosting running with cPanel and NodeJs Plugin

**Comment by jhuckaby** [comment]
I highly doubt it.  Cronicle is a background service that runs continually as a daemon.  It needs to be installed on the server directly.

https://github.com/jhuckaby/Cronicle/blob/master/docs/Setup.md
