### ISSUE TITLE
Mail configuration is a disaster!

### ISSUE THREAD

**Issue by markusglaetzner** [jhuckaby/Cronicle#704]
Please implement functional mail configuration - sendmail is no usable option (installing a complete mail server is easier than configure sendmail!) and pixl-mail does not support tls.

**Comment by markusglaetzner** [comment]
why did you close this issue without comment? It seems impossible to config sendmail with starttls and my own mailcow server, and cronicle (don´t missunderstand me - this ios a really great app!) without notifications is not really useful. Cronicla is installed in less than 5 min, but trying to install and config sendmail now took many hours without success. It would be cool if you could use another method for working notifications. Sendmail is the worst option and pixl-mail is not state of the art (no tls support, only SSL3).

**Comment by jhuckaby** [comment]
This issue was closed because it is an insult to the project.  Saying "Mail configuration is a disaster!" with an exclamation point no less, is basically saying "Your app sucks!" and expecting a meaningful response.

Feel free to try again with a nicer subject line, and you may get a better response.

**Comment by markusglaetzner** [comment]
You are totally right. I like cronicle very much and it is not your fault, that I wasn't able to get sendmail working. I am sorry!

**Comment by jhuckaby** [comment]
All good, man.  I hope you are able to get it working.

pixl-mail is just a thin wrapper around the hugely popular [nodemailer](https://nodemailer.com/smtp/) system.  You can pass ANY nodemailer configuration parameters in the [mail_options](https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#mail_options) config property, and they are passed verbatim, directly to it.  Check their docs for usage.  At a glance, you might need:

> **requireTLS** – if this is *true* and secure is *false* then Nodemailer tries to use STARTTLS even if the server does not advertise support for it. If the connection can not be encrypted then message is not sent
