### ISSUE TITLE
Log live watcher will not connect

### ISSUE THREAD

**Issue by catchdave** [jhuckaby/Cronicle#715]
## Summary

I have tried a few different ways, including editing the websocket code slightly, but can't seem to get live log watcher to work.
The error I get is below (x.y is obviously the real IP address).
```
Log Watcher: Connecting to server: http://192.168.x.y:3012...

Log Watcher: Server Connect Error: Error: timeout (http://192.168.x.y:3012)

Log Watcher: Server Connect Error: Error: timeout (http://192.168.x.y:3012)

Log Watcher: Server Connect Error: Error: timeout (http://192.168.x.y:3012)
```

## Steps to reproduce the problem

Run a job that lasts a minute or longer and view it.

## Your Setup

I have one master and one worker node. The master is running in docker and has ngnix in front of it for HTTPS and is on a custom domain. The worker node is running on ubuntu (not in docker). Everything else seems to work in this setup EXCEPT for live logs. 

So the master/primary node is `https://croncile.mydomain.com:443` and the worker node does not have a domain or SSL => `http://192.168.x.y:3012`

I have tried setting `remote_server_port`, but that did nothing. I have also played around with `web_direct_connect` and `web_socket_use_hostnames` but they did not seem to help either.

I noticed in the code in `htdocs/js/pages/JobDetails.class.js` that it does not use the `remote_server_port` and simply uses the proto and port of the master, regardless of the remote server. I modified the JS to use the remote_server_port that works for the worker node and manually set the proto to both `http://` and `ws://` but both results in the timeout error above.

I used apidog (AKA postman) to connect to the worker node websocket and it succeeds on `ws://192.168.x.y:3012/socket.io/`

### Operating system and version?

Worker node:  Ubuntu 22.04.3 LTS
Master node: Docker image: `bluet/cronicle-docker:latest`

### Node.js version?

v20.11.0

### Cronicle software version?

Version 0.9.40

### Are you using a multi-server setup, or just a single server?
Yes, per above, one master and one worker

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem

### Can you reproduce the crash consistently?
Yes

**Comment by jhuckaby** [comment]
I'm terribly sorry to say this, but Cronicle v1 doesn't support HTTPS.  Several people have hacked it to sort of make it kind of work, but live log watching is a no-go, because it opens a secondary web socket directly to the worker server.

The good news is, this is all fixed in Cronicle v2, which is coming this year (2024).  Unfortunately it would be way too much work to backport full HTTPS support into v1.

**Comment by catchdave** [comment]
No problem, I can wait for v2! Thanks for replying.
