### ISSUE TITLE
Puppeteer Cron Job Event

### ISSUE THREAD

**Issue by kuwaitman** [jhuckaby/Cronicle#718]
hi, i was wondering how can i create a puppeteer job, from the Cronicle Scheduled event interface. when i click on add an event i cannot see an option that i can run a nodejs task. Thank you.

Kind Regards,

**Comment by jhuckaby** [comment]
Just use the [Shell Plugin](https://github.com/jhuckaby/Cronicle/blob/master/docs/Plugins.md#built-in-shell-plugin).  It can launch any shell command(s) you want.  You will need to write your own Puppeteer control script.
