### ISSUE TITLE
Api's are not using proxy url

### ISSUE THREAD

**Issue by subi-kp** [jhuckaby/Cronicle#72]
## Summary
I am running cronicle in kubernetes as a docker container. And exposed UI using ingress.

Websocket is working fine but while clicking login button, after entering password i am getting 500. 

Error:  Network Error: 500: An unknown network error occurred. Please try again.
I inspected from my browser, the request url is hitting internal hostname of the container instead of my endpoint url.
container url: http://cronicle-75987bb6b6-8j7w9:3012/api/user/login --> (current issue )
endpoint url: http://cronicle.xyz.com:3012/api/user/login --> (expected)

**Comment by jhuckaby** [comment]
This is actually as designed.  See: https://github.com/jhuckaby/Cronicle/issues/63 for details.

**Comment by subi-kp** [comment]
This will work on same network. but in my case container is a private network and meanwhile, I am accessing from public. 
Websocket is working perfectly for me, but not apis.

**Comment by jhuckaby** [comment]
That's really bizarre.  The websocket and API requests are both supposed to hit the same endpoint.  I guess this is an open bug.

**Comment by subi-kp** [comment]
Can I get any ETA for this bug?

**Comment by jhuckaby** [comment]
I'm sorry, but I don't do ETAs.  This is an open-source free project, that I only work on in my spare time.  I also have never used Docker before, so I am not even sure how to reproduce this bug.

You might want to take a look at this pull request: https://github.com/jhuckaby/Cronicle/pull/65

Perhaps his fork corrects this issue.

Apologies.

**Comment by subi-kp** [comment]
Thanks for your valuable time. Actually I looked into the PR, where the issue is about the  web socket port. But in my case url endpoint is an issue, while running cronicle over the nginx proxy. Will send you steps to reproduce it soon

**Comment by dol-leodagan** [comment]
I'm currently working on a Docker Image for Cronicle, served behind a nginx reverse-proxy and I made a workaround in the entrypoint for this error :

```sh
export HOSTNAME="${VIRTUAL_HOST}"
```

```VIRTUAL_HOST``` is the FQDN of the service

This can bring other problems if you arbitrarily change the ```HOSTNAME``` after storage setup but that's not a limitation for my usage...
