### ISSUE TITLE
How to properly update plugins?

### ISSUE THREAD

**Issue by klimmilk** [jhuckaby/Cronicle#721]
I can't figure out how to properly update plugins, preferably with zero downtime.
I have many scheduled tasks using my custom plugins. Quite often, changes need to be made to these plugins (sometimes only the logic may change, and sometimes the number of plugin parameters changes).
I'm currently using Cronicle in docker (but you can describe the solution for a non-docker installation) and haven't come up with anything yet other than:

1. Building new docker image
2. Creating backup from current container using `control.sh export`
3. Replacing old container with new one
4. Importing backup using `control.sh import`
5. Bulk update task parameters if needed via API

But this fill junky and this way I lose all task execution logs.

How to properly update plugins without losing your schedule and logs?

**Comment by jhuckaby** [comment]
Moving to discussion.  This is not an issue.
