### ISSUE TITLE
how to clean log

### ISSUE THREAD

**Issue by Re20211101** [jhuckaby/Cronicle#727]
i have modified list_row_max and job_data_expire_days ,but these logs still exist in All Completed Jobs

**Comment by jhuckaby** [comment]
I'm so sorry, but [job_data_expire_days](https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#job_data_expire_days) only handles setting the expiration on **new** jobs.  It doesn't retroactively expire or delete past jobs.

The [list_row_max](https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#list_row_max) will chop lists to the max every night, but this doesn't actually delete the job log data itself, only the entries in the completed tables.

If you are concerned about disk space, and you are using the local filesystem for storage, you can wipe the logs for *all* jobs.  See here for details: https://github.com/jhuckaby/Cronicle/issues/304

Note that this whole thing has been completely redesigned in Cronicle v2, coming out later this year.  It will be much more flexible and easy to delete old job data, and change the settings on the fly.

**Comment by Re20211101** [comment]
Thank you for your answer.
