### ISSUE TITLE
Shell plugin does not work on AIX. Cannot execute shell.

### ISSUE THREAD

**Issue by paulgiordano** [jhuckaby/Cronicle#729]
## Summary

Shell plugin does not work on AIX 7.2

## Steps to reproduce the problem

Set up an event, simple echo will do, and specify any shell - /bin/ksh is what I'm using. Run the event and get an error:
 Error: Child spawn error: bin/shell-plugin.js: Child process failed to spawn (Check executable location and permissions?)

## Your Setup

Cronicle server on Linux
Cronicle worker on AIX

### Operating system and version?

AIX 7.2

### Node.js version?

21.7.0

### Cronicle software version?

Version 0.9.40

### Are you using a multi-server setup, or just a single server?

Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

the filesystem

### Can you reproduce the crash consistently?

yes

## Log Excerpts

Job ID: jltir680plf
Event Title: serviceprod test one
Hostname: serviceprod71
Date/Time: 2024/03/08 08:29:24 (GMT-6)

Job failed at 2024/03/08 08:29:24 (GMT-6).
Error: Child spawn error: bin/shell-plugin.js: Child process failed to spawn (Check executable location and permissions?)
End of log.

**Comment by jhuckaby** [comment]
See: https://github.com/jhuckaby/Cronicle/issues/673
