### ISSUE TITLE
Feature: HTTP Request Plugin: forwarding of chained data to / from HTTP request

### ISSUE THREAD

**Issue by sebastianhaberey** [jhuckaby/Cronicle#73]
First off, thanks for putting all that work into Cronicle! I've been trying it out recently and I really like the look of it and its versability. Before we start using it in production, there's one feature that we need to have and we are currently thinking about the best way to implement it.

We would like to be able to forward values returned by HTTP requests (via HTTP request plugin) to the next request in the chain. For example the first HTTP request (performed by the first job in the chain) returns a UUID that will be used in subsequent HTTP requests (performed by subsequent jobs in the chain).

I was thinking of extending the existing HTTP plugin (url-plugin.js) with an option to map input values from _chain_data_ to URL variables. And another option to map results from the HTTP request to output values in _chain_data_. And maybe a third option to "pass through" values to the next job without touching them at all.

Would you say this is a reasonable idea? Or maybe you have a better / simpler idea on how to implement this? Any feedback would be appreciated.

**Comment by jhuckaby** [comment]
Hello there, and thank you for the feature request!

I would be happy to add something like this, but I need to understand more about your specific needs.  Namely, you mention a "UUID", but you don't say how it is returned in the HTTP response.  Are we talking about a HTTP response header here?  Something like `X-UUID: 7617a494-823f-4566-8f8b-f479c2a6e707`?  Or is this something embedded in the actual content body (data) of the response?  The latter would be difficult, because the content body can be in any format (JSON, XML, HTML, etc.).

Assuming you mean the former (i.e. HTTP response headers) then I can easily stuff all those as key/value pairs into the `chain_data` property and pass them back to Cronicle.  Then, subsequent jobs can use a placeholder expansion system to insert them into the URL or request headers.  Like this:

<img width="612" alt="screenshot 2018-07-09 20 00 56" src="https://user-images.githubusercontent.com/700765/42486845-ee9edd56-83b2-11e8-8c2c-654db8f11465.png">

In my example I am inserting the chained X-UUID into both the URL, and another request header.  The placeholder syntax is square brackets with a slash-delimited path, e.g.

```
[/chain_data/headers/x-uuid]
```

In this case the URL would get expanded to:

```
http://apps.myserver.com/rest/v1?uuid=7617a494-823f-4566-8f8b-f479c2a6e707
```

And the headers expanded to:

```
User-Agent: Cronicle/1.0
X-UUID: 7617a494-823f-4566-8f8b-f479c2a6e707
```

This is the format used by [my own placeholder system](https://github.com/jhuckaby/pixl-tools#sub), so it is the easiest for me to implement quickly.  Would something like this work for your needs?

**Comment by sebastianhaberey** [comment]
Hi Joseph. I love the simplicity of your idea, and the syntax of the URL variable replacement. I think this solution would help right away.

There's one or two drawbacks that may or may not affect us in the future. First, I read that HTTP custom headers are intended for informational data only and may be removed by strict firewalls. This would break our system, but so far it looks unlikely that we'll have that kind of firewall between the Cronicle host and our services.

Second, we'd have to modify all our services to pass values on to the subsequent job as custom HTTP headers. For our current use case (the UUID) we should be fine because the UUID is relevant to all our services. But in a scenario where there is a chain of jobs A -> B -> C, with C relying on output of both, A and B, we'd have to make B forward A's output, which would break separation of concerns and become messy fast.

To address these issues, we'd have to go for a more specialised solution which would probably involve something JSON-specific, like "if response content type is JSON, add its data to chain_data" plus a way to access results of earlier jobs, like

`http://apps.myserver.com/rest/v1?uuid=[/chain_data/results/ejje1hbb702/uuid]`

But, like I said in the beginning, these points are not an issue now and your solution would definitely work nicely right now. If you find some time to work on this, that would be excellent. Or, if you are kind of busy, you could also point us in the general direction and we'd give it a try.

**Comment by jhuckaby** [comment]
That is a very cool idea, but I think it is a **VERY** specific use case for you, and no one else would ever need that kind of complexity.  I could be wrong, but that's just my read on it.  I will, however, meet you half way.  I added chain reaction support, with both headers **and JSON content body** (assuming the response has the correct Content-Type and is less than 1 MB in total size), but each request can only read the chain data from the previous one.

[Cronicle 0.8.12](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.12) has been released with this feature implemented.  Here are the updated docs:

https://github.com/jhuckaby/Cronicle#built-in-http-request-plugin
https://github.com/jhuckaby/Cronicle#http-request-chaining

## Built-in HTTP Request Plugin

Cronicle ships with a built-in "HTTP Request" Plugin, which you can use to send simple GET, HEAD or POST requests to any URL, and log the response.  You can specify custom HTTP request headers, and also supply regular expressions to match a successful response based on the content.  Here is the user interface when selected:

![HTTP Request Plugin](https://pixlcore.com/software/cronicle/screenshots-new/http-request-plugin.png)

Here are descriptions of the parameters:

| Plugin Parameter | Description |
|------------------|-------------|
| **Method** | Select the HTTP request method, either GET, HEAD or POST. |
| **URL** | Enter your fully-qualified URL here, which must begin with either `http://` or `https://`. |
| **Headers** | Optionally include any custom request headers here, one per line. |
| **POST Data** | If you are sending a HTTP POST, enter the raw POST data here. |
| **Timeout** | Enter the timeout in seconds, which is measured as the time to first byte in the response. |
| **Follow Redirects** | Check this box to automatically follow HTTP redirect responses (up to 32 of them). |
| **SSL Cert Bypass** | Check this box if you need to make HTTPS requests to servers with invalid SSL certificates (self-signed or other). |
| **Success Match** | Optionally enter a regular expression here, which is matched against the response body.  If specified, this must match to consider the job a success. |
| **Error Match** | Optionally enter a regular expression here, which is matched against the response body.  If this matches the response body, then the job is aborted with an error. |

### HTTP Request Chaining

The HTTP Request Plugin supports Cronicle's [Chain Reaction](https://github.com/jhuckaby/Cronicle#chain-reaction) system in two ways.  First, information about the HTTP response is passed into the [Chain Data](https://github.com/jhuckaby/Cronicle#chain-data) object, so downstream chained events can read and act on it.  Specifically, all the HTTP response headers, and possibly even the content body itself (if formatted as JSON and smaller than 1 MB) are included.  Example:

```js
"chain_data": {
	"headers": {
		"date": "Sat, 14 Jul 2018 20:14:01 GMT",
		"server": "Apache/2.4.28 (Unix) LibreSSL/2.2.7 PHP/5.6.30",
		"last-modified": "Sat, 14 Jul 2018 20:13:54 GMT",
		"etag": "\"2b-570fb3c47e480\"",
		"accept-ranges": "bytes",
		"content-length": "43",
		"connection": "close",
		"content-type": "application/json",
		"x-uuid": "7617a494-823f-4566-8f8b-f479c2a6e707"
	},
	"json": {
		"key1": "value1",
		"key2": 12345
	}
}
```

In this example an HTTP request was made that returned those specific response headers (the header names are converted to lower-case), and the body was also formatted as JSON, so the JSON data itself is parsed and included in a property named `json`.  Downstream events that are chain-linked to the HTTP Request event can read these properties and act on them.

Secondly, you can chain an HTTP Request into *another* HTTP Request, and use the chained data values from the previous response in the next request.  To do this, you need to utilize a special `[/bracket/slash]` placeholder syntax in the second request, to lookup values in the `chain_data` object from the first one.  You can use these placeholders in the **URL**, **Request Headers** and **POST Data** text fields.  Example:

![HTTP Request Chain Data](https://pixlcore.com/software/cronicle/screenshots-new/http-request-chained.png)

Here you can see we are using two placeholders, one in the URL and another in the HTTP request headers.  These are looking up values from a *previous* HTTP Request event, and passing them into the next request.  Specifically, we are using:

| Placeholder | Description |
|-------------|-------------|
| `[/chain_data/json/key1]` | This placeholder is looking up the `key` value from the JSON data (body content) of the previous HTTP response.  Using our example response shown above, this would resolve to `value1`. |
| `[/chain_data/headers/x-uuid]` | This placeholder is looking up the `X-UUID` response header from the previous HTTP response.  Using our example response shown above, this would resolve to `7617a494-823f-4566-8f8b-f479c2a6e707`. |

So once the second request is sent off, after placeholder expansion the URL would actually resolve to:

```
http://myserver.com/test.json?key=value1
```

And the headers would expand to:

```
User-Agent: Mozilla/5.0
X-UUID: 7617a494-823f-4566-8f8b-f479c2a6e707
```

You can chain as many requests together as you like, but note that each request can only see and act on chain data from the *previous* request (the one that directly chained to it).

Hope this helps!

**Comment by sebastianhaberey** [comment]
Hi Joseph, just wanted to confirm that I tested the new feature in v0.8.12 today (both variants, "headers" and "json") and it works like a charm. Thank you for implementing this, it's very helpful for us :+1: Keep up the great work!

**Comment by jhuckaby** [comment]
Awesome, thank you!

**Comment by marcelinhov2** [comment]
I did not understand how to use this feature

```
const test = await request({
				url: `http://xx.xx.xx.xx:3012/api/app/create_event/v1?api_key=${apiKey}`,
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				json: {
					"category": "cjp09o7en08",
					"enabled": 1,
					"notify_fail": "",
					"notify_success": "",
					"params": {
						"establishment": currentEstablishment,
						"engine": currentEngine,
						"event": _.find(currentEstablishment.engines, {'engine': current.engine})
					},
					"plugin": "urlplug",
					"timezone": "America/Sao_Paulo",
					"timing": cronParser.parse_crontab(current.repeatInterval, current.name),
					"title": `${currentEstablishment.name} - ${currentEngine.name}`,
					"target": "ip-172-31-64-54",
					// "web_hook": "https://webhook.site/b79a2033-0de3-4bbc-87d3-94e1e3bc0c27"
				},
				chain_data: {
					"headers": {
						"date": "Sat, 14 Jul 2018 20:14:01 GMT",
						"server": "Apache/2.4.28 (Unix) LibreSSL/2.2.7 PHP/5.6.30",
						"last-modified": "Sat, 14 Jul 2018 20:13:54 GMT",
						"etag": "\"2b-570fb3c47e480\"",
						"accept-ranges": "bytes",
						"content-length": "43",
						"connection": "close",
						"content-type": "application/json",
						"x-uuid": "7617a494-823f-4566-8f8b-f479c2a6e707"
					},
					"json": {
						"key1": "value1",
						"key2": 12345
					}
				}
				// transform: body => JSON.parse(body)
			});
```

Am I using it at the wrong place?

**Comment by marcelinhov2** [comment]
Do you have any use example of error_match feature? I tried to use here, no sucess.
