### ISSUE TITLE
Error fetching object from logs/events in version 0.8.10

### ISSUE THREAD

**Issue by abnerjacobsen** [jhuckaby/Cronicle#74]
## Summary
When executing some scheduled jobs the server dies with the following FAILURE:

> /opt/cronicle/lib/job.js:1734
> 					fs.stat( job.log_file, function(err, stats) {
> 					             ^
> 
> TypeError: Cannot read property 'log_file' of undefined
>     at /opt/cronicle/lib/job.js:1734:19
>     at replenish (/opt/cronicle/node_modules/async/dist/async.js:998:17)
>     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
>     at /opt/cronicle/node_modules/async/dist/async.js:958:16
>     at /opt/cronicle/lib/job.js:1736:7
>     at FSReqWrap.oncomplete (fs.js:171:5)

NOTE: Before this job 187 others had executed withou problem. Restarting Cronicle I was able to execute the hob manually without problem.

## Your Setup

Running using this Dockerfile: https://github.com/belsander/docker-cronicle/blob/master/Dockerfile
I buid the docker image locally to use the newest Cronicle version

### Operating system and version?
Alpine

### Node.js version?
9.11.2

### Cronicle software version?
0.8.10

### Are you using a multi-server setup, or just a single server?
No

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem

### Can you reproduce the crash consistently?
Yes

## Log Excerpts

> [1531242661.908][2018-07-10 17:11:01][localhost][Storage][debug][9][Pushing 1 items onto end of list: _cleanup/2019/01/06][]
> [1531242661.908][2018-07-10 17:11:01][localhost][Storage][debug][9][Requesting lock: |_cleanup/2019/01/06][]
> [1531242661.908][2018-07-10 17:11:01][localhost][Storage][debug][9][Locked key: |_cleanup/2019/01/06][]
> [1531242661.908][2018-07-10 17:11:01][localhost][Storage][debug][9][Loading list: _cleanup/2019/01/06][]
> [1531242661.908][2018-07-10 17:11:01][localhost][Filesystem][debug][9][Fetching Object: _cleanup/2019/01/06][data/_cleanup/19/fe/4d/19fe4d3e3e041157904d55ef6a33a903.json]
> [1531242661.909][2018-07-10 17:11:01][localhost][Storage][debug][9][Running async task: custom][{"action":"custom"}]
> [1531242661.909][2018-07-10 17:11:01][localhost][Storage][debug][9][Unshifting 1 items onto beginning of list: logs/events/ejjfwtv0v1g][]
> [1531242661.909][2018-07-10 17:11:01][localhost][Storage][debug][9][Requesting lock: |logs/events/ejjfwtv0v1g][]
> [1531242661.909][2018-07-10 17:11:01][localhost][Storage][debug][9][Locked key: |logs/events/ejjfwtv0v1g][]
> [1531242661.909][2018-07-10 17:11:01][localhost][Storage][debug][9][Loading list: logs/events/ejjfwtv0v1g][]
> [1531242661.909][2018-07-10 17:11:01][localhost][Filesystem][debug][9][Fetching Object: logs/events/ejjfwtv0v1g][data/logs/e2/8c/ce/e28cce1d1d5ce4a181a614e985fcaffb.json]
> [1531242661.91][2018-07-10 17:11:01][localhost][Storage][debug][9][Running async task: custom][{"action":"custom"}]
> [1531242661.91][2018-07-10 17:11:01][localhost][Storage][debug][9][Unshifting 1 items onto beginning of list: logs/completed][]
> [1531242661.91][2018-07-10 17:11:01][localhost][Storage][debug][9][Requesting lock: |logs/completed][]
> [1531242661.91][2018-07-10 17:11:01][localhost][Storage][debug][9][Locked key: |logs/completed][]
> [1531242661.91][2018-07-10 17:11:01][localhost][Storage][debug][9][Loading list: logs/completed][]
> [1531242661.91][2018-07-10 17:11:01][localhost][Filesystem][debug][9][Fetching Object: logs/completed][data/logs/90/cc/44/90cc4491b6a8f2a5127146f132944847.json]
> [1531242661.911][2018-07-10 17:11:01][localhost][Filesystem][debug][9][Storing Binary Stream Object: jobs/jjjfycf5tot/log.txt.gz][data/jobs/2e/59/d3/2e59d357f0cf4e3815af7c129295ff96.gz]
> [1531242661.912][2018-07-10 17:11:01][localhost][Storage][debug][9][List not found, creating it: logs/events/ejjfwtv0v1g][{}]
> [1531242661.912][2018-07-10 17:11:01][localhost][Storage][debug][9][Creating new list: logs/events/ejjfwtv0v1g][{"page_size":50,"first_page":0,"last_page":0,"length":0,"type":"list"}]
> [1531242661.912][2018-07-10 17:11:01][localhost][Filesystem][debug][9][Fetching Object: logs/events/ejjfwtv0v1g][data/logs/e2/8c/ce/e28cce1d1d5ce4a181a614e985fcaffb.json]
> /opt/cronicle/lib/job.js:1734
> 					fs.stat( job.log_file, function(err, stats) {
> 					             ^
> 
> TypeError: Cannot read property 'log_file' of undefined
>     at /opt/cronicle/lib/job.js:1734:19
>     at replenish (/opt/cronicle/node_modules/async/dist/async.js:998:17)
>     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
>     at /opt/cronicle/node_modules/async/dist/async.js:958:16
>     at /opt/cronicle/lib/job.js:1736:7
>     at FSReqWrap.oncomplete (fs.js:171:5)

**Comment by jhuckaby** [comment]
Thank you very much for this detailed bug report.  I cannot reproduce this, but it looks like a race condition with the new code that monitors job log sizes.  I can see how this might happen.  I'll fix this ASAP and release a new version in a few minutes.

**Comment by jhuckaby** [comment]
Released Cronicle [v0.8.11](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.11) which should fix this race condition.  Thanks again!
