### ISSUE TITLE
Cronicle UI constantly reloading landing page (completely blank) when accessing via exposed port

### ISSUE THREAD

**Issue by SeifMejri21** [jhuckaby/Cronicle#740]
**Environment:**
- **Cronicle Version**: v0.9.45
- **Operating System**: Ubuntu 20.04.6 LTS (Focal Fossa)
- **Node.js Version**: v20.12.1
- **Browser**: Chrome

**Summary:**
After successfully installing Cronicle on a remote server and verifying its functionality locally, I exposed port 3012 to allow remote access. However, when trying to access the landing page remotely, the page continuously reloads and fails to display the login inputs, rendering the UI inaccessible.

**Steps to Reproduce:**
1. Install Cronicle on a remote server.
2. Verify local access on localhost.
3. Expose port 3012 for remote access.
4. Attempt to access the Cronicle UI from a remote location using a browser.

The UI continuously reloads without displaying login inputs, making it impossible to interact with Cronicle remotely. The page appears almost blank, and the console logs show several errors.

**Console Errors:**

VM137:1 Uncaught TypeError: Cannot redefine property: googletag
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:196
    at <anonymous>:1:524
    
   WebSocket connection to 'ws:<URL>/socket.io/?EIO=4&transport=websocket' failed: WebSocket is closed before the connection is established.
    
    
![image](https://github.com/jhuckaby/Cronicle/assets/58209253/0ebb8e3e-0dcf-4f37-9be9-daa9d0566395)
![image](https://github.com/jhuckaby/Cronicle/assets/58209253/912c1bee-19f1-4487-ac7e-4e5052ef11fd)
![image](https://github.com/jhuckaby/Cronicle/assets/58209253/a2267c24-bd5e-468c-a3a6-b7a9be4989cf)
![image](https://github.com/jhuckaby/Cronicle/assets/58209253/9ebb733c-c109-41e3-be67-18d221930d47)

**Comment by SeifMejri21** [comment]
thank you so much,  resetting web_direct_connect to false solved the issue.
 i did not read the docs well the first time well enough so i thought setting web_direct_connect to true is necessary to serve the UI.
 
 on a completely unrelated matter but equally important. is there way to change user thta cronnicle uses.
 i am using it to run some python script, i am using  whoami to see the user and it's root, however i need it to use another user called **ubuntu** is there to do that ?

**Comment by jhuckaby** [comment]
You can change this at the Plugin level.  Edit the Plugin you are using (e.g. Shell Plugin, or whatever) and see this section:

![Screenshot 2024-04-12 at 11 08 53 AM](https://github.com/jhuckaby/Cronicle/assets/700765/1a4a0ea2-88ce-4c37-afaa-afb79a3c3f69)

Cronicle itself (the daemon / server process) should run as root, so it has the ability to change the UID of its child (job) processes.
