### ISSUE TITLE
Increase number of jobs in history page

### ISSUE THREAD

**Issue by Giattuck** [jhuckaby/Cronicle#756]
Hello, I have around 2000 completed events daily and the jobs history only shows 25/page making it difficult to search.

Looking at the source code this is defined on the History.class.js row 60:

`if (!args.limit) args.limit = 25;`

I was wondering if is it possible to change this kind of settings on the config file, without changing the code?

I would like to change this limit on the graph page too.

Thank you very much for this great tool!

**Comment by jhuckaby** [comment]
Excellent feature suggestion.  I'll make this configurable in the next release.  Thanks!

**Comment by Giattuck** [comment]
Sorry for the late reply @jhuckaby i've missed your reply!!

I'll test it asap. Thank you very very much!!!
