### ISSUE TITLE
[Feature request] Filter by result on history page

### ISSUE THREAD

**Issue by Taz4Git** [jhuckaby/Cronicle#76]
## Summary

On the history page you can "Filter by event", it would be very nice if we can "Filter by result", so we find errors much faster.

At this moment we have 7,913 events found in the history (within 2 days of cronicle use) and it's a little hell to find a failed event :)

**Comment by jhuckaby** [comment]
I'm sorry about that.  However, the good news is, all failed jobs are logged to the **Admin / Activity** tab, so you can easily see them all there, in correct order.  Very little else is logged to Admin / Activity, so it shouldn't be too hard to find what you are looking for.  Example:

<img width="979" alt="screenshot 2018-07-14 14 34 01" src="https://user-images.githubusercontent.com/700765/42728604-f8346b10-8772-11e8-9298-e6783cc5f53e.png">

I will add add search / filter feature to the Completed Events screen someday, but please note that it will be rather difficult, as these things aren't in a database, but rather just a long linked list.  This will probably be a v2.0 feature.

I hope the Admin / Activity screen helps!

**Comment by Taz4Git** [comment]
Sorry for the late reply,
Thank you for the explanation, I will use the Admin / Activity screen and wait for v2.0 👍
