### ISSUE TITLE
Not able to change IP of server on my AWS Ubuntu 22.04 server

### ISSUE THREAD

**Issue by iamumairayub** [jhuckaby/Cronicle#761]
So I have these settings
```
Items from list: global/server_groups: [
        {
                "id": "maingrp",
                "title": "Primary Group",
                "regexp": "^(scrapers)$",
                "master": 1
        }
]
```
and
```
Items from list: global/servers: [
        {
                "hostname": "scrapers",
                "ip": "54.22.77.99"
        }
]
```

But its showing `10.0.0.130` here 

![image](https://github.com/jhuckaby/Cronicle/assets/13570295/c2e6d409-b758-4f87-9359-859b2e302497)

and due to that, its trying to connect to that IP which makes me unable to see running logs.

![image](https://github.com/jhuckaby/Cronicle/assets/13570295/b88d9b31-25df-46a1-86d7-5b9a08ce92a9)

WHERE IS THIS `10.0.0.130` COMING FROM???

I dont have any domain, **I just want to be able to access the UI via my http://54.22.77.99:3012/#Home and also be able to see live logs.**

Following the https://github.com/jhuckaby/Cronicle/issues/58#issuecomment-373954033 advice, I set 

```
	"web_direct_connect": true,
	"web_socket_use_hostnames": true,
```
	
and also put `10.0.0.130 scrapers` in `/etc/hosts`

but I get `{"code":"master","description":"No master server found"}` in the network tab requests

![image](https://github.com/jhuckaby/Cronicle/assets/13570295/b14fbeaf-4ce5-429d-ad7a-6417a82ca5d2)

## Summary

Not able to change IP of server on my AWS Ubuntu 22.04 server

## Steps to reproduce the problem

just setup Cronicle on an AWS machine

### Operating system and version?

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

### Node.js version?

18

### Cronicle software version?

installed it using `curl -s https://raw.githubusercontent.com/jhuckaby/Cronicle/master/bin/install.js | node` so it must be latest

### Are you using a multi-server setup, or just a single server?
single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

it must be file? because I just installed it using above single command.

**Comment by jhuckaby** [comment]
> WHERE IS THIS 10.0.0.130 COMING FROM???

When Cronicle starts up, it sniffs all network interfaces on the server and picks the first non-local one with a IPv4 address.  Usually this is what people want, but not always.

Try overriding the server's hostname and IP by setting these two top-level config properties in Cronicle's `config.json` file:

```js
"hostname": "scrapers",
"ip": "54.22.77.99"
```

These are undocumented properties but they will override the "auto-detection" that happens on startup, where the system tries to figure out its own hostname and IP.

Note: Cronicle v2 fixes this, due out later this year.

**Comment by iamumairayub** [comment]
Your suggestion fixed my issue. Thanks a lot.
