### ISSUE TITLE
How to export all the content data and config

### ISSUE THREAD

**Issue by jmeiracorbal** [jhuckaby/Cronicle#775]
Hi @jhuckaby 

Can I export the storage data to make another instance of Cronicle with the same config and same users? Or is only possible copying the data content generated when the project is working?

**Comment by matthewjhands** [comment]
I think this is what you're looking for: https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#data-import-and-export

**Comment by jmeiracorbal** [comment]
> I think this is what you're looking for: https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#data-import-and-export

Thanks!
