### ISSUE TITLE
storage-cli.js, edit command not support scripts as EDITOR

### ISSUE THREAD

**Issue by dol-leodagan** [jhuckaby/Cronicle#78]
## Summary

```bin/storage-cli.js edit``` use "time" to guess if modifications have been done...

This doesn't work if the modifications were instantaneous (with a script)

## Steps to reproduce the problem

Using jq.

Store this in a script "edit_entry.sh" and make it executable
```
#!/bin/sh
FILE_TO_EDIT="$1"

TEMP_FILE_TO_EDIT="$(mktemp -p "$(dirname "$FILE_TO_EDIT")")"

jq --raw-output "$CRONICLE_EDIT_FILTER" "$FILE_TO_EDIT" > "$TEMP_FILE_TO_EDIT" \
    && mv -f "$TEMP_FILE_TO_EDIT" "$FILE_TO_EDIT"
```

In a shell in the current working directory of Cronicle
```
export EDITOR="/path/to/edit_entry.sh"
export CRONICLE_EDIT_FILTER=" .email = \"someone@somehost.com\" "
node bin/storage-cli.js edit users/admin
> [1531746901.21][TRANSACTION][get] users/admin ({"elapsed_ms":2.542})
> Spawning editor to edit record: users/admin
> File has not been changed, record was not touched: users/admin
```

The script act as the EDITOR binary and filter the input file according to the exported CRONICLE_EDIT_FILTER variable then insert the result in the temporary file given by the "edit" command

The modification time is too close from temporary file creation time to trigger a difference in the storage-cli.js script.

The modification works if a sleep is added before editing the file.

## Your Setup

Docker Container

### Operating system and version?

Alpine

### Node.js version?

node v10.5.0

### Cronicle software version?

Cronicle 0.8.14

### Are you using a multi-server setup, or just a single server?

Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

filesystem

### Can you reproduce the crash consistently?

Not a crash, can be reproduced everytime

## Log Excerpts

```
+ FILE_TO_EDIT=/tmp/cli-temp-34.json
+ echo Pre-Modification
+ stat /tmp/cli-temp-34.json
   File: /tmp/cli-temp-34.json
   Size: 339        Blocks: 8          IO Block: 4096   regular file
 Device: a4h/164d   Inode: 272859      Links: 1
 Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
 Access: 2018-07-16 13:05:38.000000000
 Modify: 2018-07-16 13:05:38.000000000
 Change: 2018-07-16 13:05:38.000000000

 + cat /tmp/cli-temp-34.json
 {
    "username": "admin",
    "password": "",
    "full_name": "Administrator",
    "email": "admin@cronicle.com",
    "active": 1,
    "modified": 1531746338,
    "created": 1531746338,
    "salt": "",
    "privileges": {
            "admin": 1
    }
 }
 + jq --raw-output  .email = "someone@example.com" /tmp/cli-temp-34.json
 + mv -f /tmp/tmp.HNFEGn /tmp/cli-temp-34.json
 + echo Post-Modification
 + stat /tmp/cli-temp-34.json
   File: /tmp/cli-temp-34.json
   Size: 352        Blocks: 8          IO Block: 4096   regular file
 Device: a4h/164d   Inode: 272860      Links: 1
 Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
 Access: 2018-07-16 13:05:38.000000000
 Modify: 2018-07-16 13:05:38.000000000
 Change: 2018-07-16 13:05:38.000000000

 + cat /tmp/cli-temp-34.json
 {
   "username": "admin",
   "password": "",
   "full_name": "Administrator",
   "email": "someone@example.com",
   "active": 1,
   "modified": 1531746338,
   "created": 1531746338,
   "salt": "",
   "privileges": {
    "admin": 1
   }
}
File has not been changed, record was not touched: users/admin
```

**Comment by jhuckaby** [comment]
Hmm, well, the CLI system definitely isn't designed for what you are trying to do.  There is a TODO item on the roadmap to add APIs for more administrative tasks like adding/editing servers, users, etc.  Perhaps that will help.

**Comment by dol-leodagan** [comment]
I tried to use the Storage CLI for editing objects because I didn't find any option in the _setup_ command or _admin_ command to set the email field of Administrator user when installing Cronicle and it's used for password retrieval which can be dangerous if sent to the default email... (cronicle.com is registered)

I only use this method of editing after creating a new storage for initial setups before starting the Cronicle Server, but I'd rather have a clean CLI options like a third optional field to _admin_ command for email address, or an _edit_ command that could be fed with a stdin pipe.

If you accept pull request on CLI tools I can try to make those improvements myself.

**Comment by jhuckaby** [comment]
Okay, understood.  I see what you are saying.  I merged your PR, but I will also add your requested features to storage-cli.js.  Doing so right now...

**Comment by jhuckaby** [comment]
This release should do what you want: [Version 0.8.15](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.15)

When using the `admin` command in the CLI, you can now specify an optional e-mail address after the user/pass, and it defaults to `admin@localhost` (no longer cronicle.com).

New CLI command: `put` (aliases `save` and `store`) which will write a storage record given its key, and it reads the JSON data from STDIN.

Includes your PR #77.

Hope this helps!

**Comment by dol-leodagan** [comment]
Thanks, it's a great update 👍 

It will allow easier integration with system scripts.

Good move removing the transaction log from stdout in the _get_ command, it's one less pipe filtering the output ! (by the way if you want to display debug output in CLI command you could use stderr that won't mess the output piping)

I can now simply use this syntax to edit any storage object :

```sh
node bin/storage-cli.js get {key} | jq -r ' {filter} ' | node bin/storage-cli.js put {key}
```

**Comment by jhuckaby** [comment]
Glad to hear it!  Yeah, that transaction log leaking out into the console from the CLI was an accident.  Thanks again for the PR and issue reports!
