### ISSUE TITLE
user with run only privilege can do more with shell plugins

### ISSUE THREAD

**Issue by oliviermollier** [jhuckaby/Cronicle#784]
## Summary

When you create a user that can only run job, I notice that he can still edit. When you save it say you are not allowed to save but you can still change the content of the script and click run

## Steps to reproduce the problem

create a user called runner.

connect with him. open an exisiting job, update the text ( do not save) but click run. Command is executed. it mean give user runjob, allow him to run everything he want

## Your Setup

I have master cronicle installed in standard on one server and 10 workers on different server

### Operating system and version?

CentOS Linux release 7.9.2009 (Core)

### Cronicle software version?
Version 0.9.53
 node --version
v16.20.2

i updated a part of the code. i don't know if you want to reintegrate in standard or not but in case some people face the same security problem i shared my correction

**Comment by oliviermollier** [comment]
![Capture d'écran 2024-07-15 093656](https://github.com/user-attachments/assets/b98c367b-0cb5-4343-b077-1d56a85a2b16)
with screenshot

**Comment by oliviermollier** [comment]
![Capture d'écran 2024-07-15 102621](https://github.com/user-attachments/assets/37ef1bda-f9ff-42df-a5ae-06871da5f1a5)
with detail

**Comment by jhuckaby** [comment]
This is "as designed" behavior.  The `run_events` privilege allows the user or API key to modify any job parameters when the API call is sent in.  This is how the system was designed.

If you want to lock this down, please upgrade your primary server to [Cronicle v0.9.54](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.54), as I added a new optional user privilege called `job_read_only`.

Edit your `/opt/cronicle/conf/config.json` file and locate this section, inside the `client` object:

```json
"privilege_list": [
	{ "id": "admin", "title": "Administrator" },
	{ "id": "create_events", "title": "Create Events" },
	{ "id": "edit_events", "title": "Edit Events" },
	{ "id": "delete_events", "title": "Delete Events" },
	{ "id": "run_events", "title": "Run Events" },
	{ "id": "abort_events", "title": "Abort Events" },
	{ "id": "state_update", "title": "Toggle Scheduler" }
],
```

Add a new privilege with the ID `job_read_only` and title "Job Read Only":

```json
"privilege_list": [
	{ "id": "admin", "title": "Administrator" },
	{ "id": "create_events", "title": "Create Events" },
	{ "id": "edit_events", "title": "Edit Events" },
	{ "id": "delete_events", "title": "Delete Events" },
	{ "id": "run_events", "title": "Run Events" },
	{ "id": "abort_events", "title": "Abort Events" },
	{ "id": "state_update", "title": "Toggle Scheduler" },
	{ "id": "job_read_only", "title": "Job Read Only" }
],
```

Then restart your server, and edit your underprivileged user or API key, and check the new "Job Read Only" privilege checkbox, then save the user or API key.  They should also have the "Run Events" privilege checked, of course.

That user will now only be able to run events straight from the schedule, without any customization.  Any other params sent in will be stripped (ignored).

**Comment by oliviermollier** [comment]
Hello, thx a lot for your reactivity anyway i upgraded to the version you publish and it seems it's doesn't work as you describe ( or maybe i didn't understand correctly)

I updated user as you described:

![Capture d'écran 2024-07-16 100150](https://github.com/user-attachments/assets/5dcdf2b1-2c43-471a-9132-5d6baffadc59)


The i connect with API and click on edit
![Capture d'écran 2024-07-16 100716](https://github.com/user-attachments/assets/9f7f0463-877c-40ba-8f77-984194c9c37f)

i can still change parameter to replace TEST_LAUNCH by something else.

Did i do something bad? or miss understood you?

**Comment by jhuckaby** [comment]
When you actually run the job, the parameter overrides (changes) will be ignored.

Effectively, the user with the "Job Read Only" privilege cannot customize the parameters on the `run_event` API call.  Any customizations passed in are ignored.

There are no changes to the UI.  The only changes are inside the `run_event` API call itself.

**Comment by oliviermollier** [comment]
yes i understood my change are possible but no take in account but : 

please see my test : 
i create a basic job just call "ls"
![Capture d'écran 2024-07-16 201032](https://github.com/user-attachments/assets/db7ba210-db09-423c-a5e2-dbbd4ae81603)

executed as admin it do ls
![Capture d'écran 2024-07-16 201211](https://github.com/user-attachments/assets/fda6d70e-03ab-4d7d-b0fb-757b2341f6c5)


i connect to api ( read only user) and change the command by "df". it's suppose to let me change to "df" but still call "ls", right?

![Capture d'écran 2024-07-16 201357](https://github.com/user-attachments/assets/fabc0d24-ac69-4545-9c68-f25296b3e358)

as the result it call df
![Capture d'écran 2024-07-16 201530](https://github.com/user-attachments/assets/bbb5c70e-fa6f-439d-8eea-3f3594d1813c)

did i miss something in your explanation?

**Comment by jhuckaby** [comment]
Oh lord, I'm SO SORRY, there was a typo in my implementation.  I was trying to go too fast, and I didn't test it properly.  Huge apologies.

I just pushed a brand new release.  Please upgrade your primary server to [Cronicle v0.9.55](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.55) and try your test again.  It should work now.

Sorry!

**Comment by oliviermollier** [comment]
Hello, no worry, and i confirm it's work perfect now !!

thx a lot
