### ISSUE TITLE
Detailed Upcoming Events

### ISSUE THREAD

**Issue by ghost** [jhuckaby/Cronicle#79]
First of all, 
congratulations about your job, it's really amazing!
It helps me a lot!

My question is, if is it possible or if it will be as future feuture
a way to get more details about "Upcoming Events", either
from UI or/and from Rest API.
In case of "Allow Queued Jobs" it will be really helpful if there
was a way to retrieve information, specially for the Parameters
of each one. And, why not, a way to delete specific one.

Another thing/idea, is a way to Comment each run, either from
UI, either from Rest API. That will be really helpful for reports,
monitoring etc.

Thanks in advance.

**Comment by jhuckaby** [comment]
Hello, and thank you for your kind words.  However, you have combined a bunch of different feature requests into one GitHub issue.  It would be much better if they were split up into individual issues.

> My question is, if is it possible or if it will be as future feuture
> a way to get more details about "Upcoming Events", either
> from UI or/and from Rest API.

Well, the "Upcoming Events" display is currently all calculated on the client-side, in the browser JavaScript, by "simulating" the scheduled events.  It does this by advancing a timer by one minute at a time, and evaluating all the scheduled event rules, seeing which ones are meant to run.  Then it just builds an array and displays it.  I have no plans to move this to the server as an API, but you can use the [get_schedule](https://github.com/jhuckaby/Cronicle#get_schedule) API to get all the scheduled events, then use this data to generate a list of upcoming events.

> In case of "Allow Queued Jobs" it will be really helpful if there
> was a way to retrieve information, specially for the Parameters of each one.

Well, you can use the [get_event](https://github.com/jhuckaby/Cronicle#get_event) API, which not only returns information about the event, but also detailed information about all current running jobs, and also the number of queued jobs.  I may extend this later to return all the parameters of the queued jobs (it currently does not).

> And, why not, a way to delete specific one.

There are currently no plans for this, as it is a very specific feature, and no one is using the queue system.   I can add it to the TODO list, but I don't know when I'll be able to get to it tho.

> Another thing/idea, is a way to Comment each run, either from
> UI, either from Rest API.

This feature is on the [Roadmap](https://github.com/jhuckaby/Cronicle/wiki/Roadmap).
