### ISSUE TITLE
Wating for master... when reboot

### ISSUE THREAD

**Issue by serveryang** [jhuckaby/Cronicle#805]
when rebot system, then got `Wating for master... `
![image](https://github.com/user-attachments/assets/7ed8a609-153f-4ee9-8072-f0ab29238b78)

read document, but not fixed. hostname never changed！
i run in single server, no need master / slave mode.

**Comment by jhuckaby** [comment]
Well, you didn't follow the new issue template, and provide any information such as your OS and log excerpts.  

But I can offer the following advice:

It takes 60 seconds (1 minute) for a master server to be selected after startup.  If you've waited over a minute, then check out our troubleshooting guide:

https://github.com/jhuckaby/Cronicle/wiki/Troubleshooting

The most common issue is that your server hostname changed on reboot.  Cronicle is VERY sensitive to server hostnames, and expects them to be static and never change.

https://github.com/jhuckaby/Cronicle/wiki/Troubleshooting#server-hostnames

If you are running in a Docker container, then you need to use the `-h HOSTNAME` option.

If that isn't the problem, then you need to go look at the logs to see why it isn't choosing a master server.  Look at `/opt/cronicle/logs/Cronicle.log`.

**Comment by serveryang** [comment]
yeah. I found the hostname is not same in storage hostname. so i set the `/etc/hostname` to storage hostname.
