### ISSUE TITLE
Job Source in event details header cuts off job name

### ISSUE THREAD

**Issue by ian-kinner** [jhuckaby/Cronicle#821]
## Summary

Long job names are cut off and the source of the running event can't be determined when the part that is shown could be one of many with the same first X characters. It says "Chain Reaction (some long job na)" - this could be "some long job name number 1" or "some long job name number 2"

 It would be great to have a mouseover show the entire name, or better yet make this a link to the source job.

## Steps to reproduce the problem

Have a job with a long name trigger another job. The second job lists the originating job in a fixed width and cuts off long names.

## Your Setup

2 servers, thousands of scheduled jobs running a lot

### Operating system and version?

Amazon Linux 2 & Ubuntu

### Node.js version?

16.20.2

### Cronicle software version?

0.9.40

**Comment by jhuckaby** [comment]
Fixed in [v0.9.61](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.61].

![Screenshot 2024-10-18 at 3 59 23 PM](https://github.com/user-attachments/assets/521fc4c2-8ffd-4033-80b7-f2dcb4c332d3)

**Comment by ian-kinner** [comment]
@jhuckaby I was trying to impress upon my coworkers how awesome of a dev you appear to be _before_ you turned around a feature request in a couple hours and put out a release. Muchos gracias 🙏

**Comment by jhuckaby** [comment]
My pleasure -- it was an easy fix 😊 -- thank you for reporting it!
