### ISSUE TITLE
Job Details tab missing - New installation

### ISSUE THREAD

**Issue by ctcarino** [jhuckaby/Cronicle#825]
![missing-tab](https://github.com/user-attachments/assets/c5a737d7-c1ad-4b51-a19a-b0121ee23401)

## Summary

"Job Details" tab is not showing up

## Steps to reproduce the problem
1. went to : https://cronicle.net/
2. ran this script: curl -s https://raw.githubusercontent.com/jhuckaby/Cronicle/master/bin/install.js | node

## Your Setup

hosted on AWS. uses nginx as reverse proxy with single chronicle master instance

### Operating system and version?
Linux 2023

### Node.js version?
18.18.0

### Cronicle software version?
0.9.61

### Are you using a multi-server setup, or just a single server?
Single
### Are you using the filesystem as back-end storage, or S3/Couchbase?
local filesystem
### Can you reproduce the crash consistently?
yes

**Comment by jhuckaby** [comment]
The Job Details tab starts out hidden by design, and appears when it is needed.  Meaning, you need to click on a link to a (running or completed) job, then it appears.

**Comment by ctcarino** [comment]
thanks. yes i manage to see it now.
