### ISSUE TITLE
The job takes up a lot of memory

### ISSUE THREAD

**Issue by GustWind-byte** [jhuckaby/Cronicle#832]
<img width="668" alt="image" src="https://github.com/user-attachments/assets/3d061567-bf3b-4b24-bbfc-525270975810">
Occupies more than 37g
Won't this be automatically deleted?

**Comment by jhuckaby** [comment]
Read the docs please: https://github.com/jhuckaby/Cronicle/blob/master/docs/Configuration.md#job_data_expire_days
