### ISSUE TITLE
How to migrate the configuration on cronicle, if I don't configure master-slave mode, just under stand-alone operation

### ISSUE THREAD

**Issue by luojieio** [jhuckaby/Cronicle#89]
How to migrate the configuration on cronicle, if I don't configure master-slave mode, just under stand-alone operation

**Comment by jhuckaby** [comment]
If you are referring to the Cronicle configuration file, then it is just this one plain JSON text file located here:

```
/opt/cronicle/conf/config.json
```

Simply copy that file to all your Cronicle servers using standard tools such as `scp` or `ftp`.  There is no built-in way to distribute that file, so you will have to do it yourself.

If you are talking about the actual server data like Plugins, Users, Groups, and your Scheduled jobs, then you should read the [Data Import and Export](https://github.com/jhuckaby/Cronicle#data-import-and-export) section of the documentation.

Hope this helps!

**Comment by luojieio** [comment]
thanks
Data Import and Export Can solve my problem
But I want to mention a bug. When modifying the regular expression of the host group on the web page, if the writing is wrong, the whole Cronicle server daemon will not start, so I used the data import and export method to manually modify the data. The regular expression in the configuration, and then re-import back, this solves the problem that the daemon can not be started

**Comment by jhuckaby** [comment]
Thanks, this is a known bug, fixed in [Version 0.8.18](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.18).
