### ISSUE TITLE
[ Suggestion: improve chained jobs management ]

### ISSUE THREAD

**Issue by jerome83136** [jhuckaby/Cronicle#91]
Hi,

Today I have played with this very good piece of software and I'm quiet pleased.
Really nice work !

I was wondering if there are some plans to "improve" the chained jobs management ?

I think some kind of "dependencies" diagram could be great !
This diagram should display the jobs and their attached jobs (chains, success/error triggered jobs, etc...)

I would be great if the diagram could indicate at which step the chain execution is, depending on the current time.

Maybe a last idea: this diagram could allow "jobs chaining", simply by drawing connecting lines between jobs.
For this, jobs should have "connectors":
- success (to attach jobs which should be run on success)
- failure (to attach jobs which should be run on jobs failure)

Hope I gave you some usefull ideas :)

Best regards

**Comment by jhuckaby** [comment]
Hello, and thank you for the feature request!  I had no idea anyone was using job chaining to the degree where something like this would be useful.

I will add this to the roadmap, but I feel like this is more of a v2.0 feature, as it will take some serious work to build some kind of auto-generating diagram, based on the chain relationships.

Perhaps an interim feature could be a bit more indication on the Schedule page which events are chained.  Like a chain (:chains:) icon or something, or some kind of indication if a job is chained to another one.

Thanks again!  Leaving this open and tagging it as an enhancement.

**Comment by iambocai** [comment]
DAG（Directed Acyclic Graphs） is useful in some cases, imagine that when there are many tasks on our platform and the relationship is very complicated, if an intermediate task is not scheduled as expected, it is very painful to rely on configuration to manually check it. It may take a lot of effort, but If you have a DAG, it will be much better.

![image](https://user-images.githubusercontent.com/2259715/46191924-dfc46400-c32b-11e8-88e3-1debc4951ac6.png)
(from airflow)

B.R

**Comment by java-stranger** [comment]
Hi,

I know this is an old feature request, but I would like to re-open it... 

I understand the flow diagram might be too complex to add. But what about making another view in the Schedule tab (scheduled events table)? Now there's "Group by category", "Group by target" and "Group by plugin", maybe it would be possible to add "View by chain order"? In which case the table changes to tree-table, and chained jobs are displayed as direct children of the triggering job (with maybe different colors when it's triggered on success or on failure).

My problem is for example here I have several jobs, which form two chains (+one standalone job):
![image](https://user-images.githubusercontent.com/2429382/109780526-640b2780-7c07-11eb-8966-6a7b46933ad1.png)

Without a tree-view it's a total mess - no way to see which job will be triggered after which. I can of course use job title to specify the order (like "1. Tick Update", "2. Bar update" etc.), but then if I make a mistake and the job definition doesn't match the title, it's confusing.

Thanks in advance!

**Comment by mikeTWC1984** [comment]
FYI, it's actually not that hard to implement graph view for scheduled events. You can use some existing graph library, e.g. visjs. Once cronicle page is loaded, you will have access to app object that will contain info about events and chains ( nodes/edges)

Here is a sample you can try. Add visjs ref to index.html head:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis-network.min.js" integrity="sha512-GE9mKnPrTn2DY5AZuIC9yE6K4FF8T+9lsO7jwHn+RW9rEjnHzF/in0oGwlPzRwjhQ+oJiawmtfvleX+l6h5/cA==" crossorigin="anonymous"></script>
```

Than place target div whereever you want the graph to render:
```html
	<div  id="schedule_graph"> </div>
	<script>setTimeout(render_schedule_graph, 1000)</script>
```

And here is the function that would render graph from app object (to start you can put it on index.html too):
```html
	<script>
		var render_schedule_graph = function () {
			var sNodes = []
			var sEdges = []
			var catMap = Object.fromEntries(app.categories.map(i => [i.id, i]))
	
			app.schedule.forEach((job, index) => {
				let jobGroup = job.enabled ? job.category : 'disabled';
				let jobCat = catMap[job.category] || {};
				let jobIcon = String.fromCharCode(parseInt(job.graph_icon || 'f111', 16));
				let jobColor = job.enabled ? (jobCat.gcolor || "#3498DB" ) : "lightgray" // #3f7ed5
				sNodes.push({ 
					id: job.id,
					label: `${jobCat.title}: ${job.title}`,
					font: `12px lato ${job.enabled ? '#777' : 'lightgray' }`,
					group: jobGroup,
					shape: 'icon',
					icon: {face: "'FontAwesome'", code: jobIcon, color: jobColor }
	
				 })
				if (job.chain) sEdges.push({ from: job.id, to: job.chain, arrows: "to", color: "green", length: 160 })
				if (job.chain_error) sEdges.push({ from: job.id, to: job.chain_error, arrows: "to", color: "red", length: 160 })
			});
	
			var sGraph = { nodes: new vis.DataSet(sNodes), edges: new vis.DataSet(sEdges) }
	
			var options = {
				nodes: { shape: 'box' },
				groups: { disabled: { color: 'lightgray', font: { color: 'gray' } } },
			}
	
			app.network = new vis.Network(document.getElementById("schedule_graph"), sGraph, options)
	
			// allow delete event by pressing del key
			$(document).keyup(function (e) {
				if (e.keyCode == 46) { // delete button pressed
					var eventId = app.network.getSelectedNodes()[0]
					if(!eventId) return;
					var idx = $P().events.findIndex(i => i.id === eventId)
					if (eventId) $P().delete_event(idx)
				}
			})
	
			// open event edit page on double click
			app.network.on("doubleClick", function (params) {
				if (params.nodes.length === 1) {
					var node = params.nodes[0]
					window.open('#Schedule?sub=edit_event&id=' + node, '_self');
				}
			});
	
			// select nodes on graph on event filtering
			// if(app.schedule.length !== this.events.length) app.network.selectNodes(this.events.map(e=>e.id));
	
		}
	
		
	</script>
```
The nodes should be clickable and you also should be able to remove node with pressing "del" key

I embedded this into scheduled events tab on my  [custom fork](https://github.com/cronicle-edge/cronicle-edge) if you want some better example. But you can wrap the above snippet as standalone html page and put it in htdocs (so it will be avaliable under localhost:3012/mygraphreport.html), the only thing you'd need to fetch schedule info with ajax or fetch (instead of using app object)
