### ISSUE TITLE
suggestion -categories

### ISSUE THREAD

**Issue by yisraelU** [jhuckaby/Cronicle#94]
I would like to suggest having the ability to limit user permissions to specific categories.
If one is using cronicle to give certain endusers access, it would be nice to be able to limit them to what they need

**Comment by jhuckaby** [comment]
Thank you, however this is a duplicate.  Has already been suggested and is an open issue here: [Issue #33 - More granular user permissions](https://github.com/jhuckaby/Cronicle/issues/33).   It is also listed on the [Roadmap for v2.0](https://github.com/jhuckaby/Cronicle/wiki/Roadmap#version-20).

I will close this one and get to work on the other.  Thanks!

**Comment by jhuckaby** [comment]
Fixed in [Version 0.8.22](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.22).
