### ISSUE TITLE
Feature suggestion: Make password field hidden by default

### ISSUE THREAD

**Issue by zaidoonhad** [jhuckaby/Cronicle#97]
## Summary

Is it possible to make the password field at the login screen hidden by default?

**Comment by jhuckaby** [comment]
Hmm, making that field visible by default was a very deliberate design decision.  I absolutely hate password fields that mask the input.  However, I would be willing to compromise and implement one of the following:

(1) If you click the provided "Hide" link to hide the password, your preference would be saved (in browser localStorage), and it would remember from that point onward.

(2) I would be willing to make it a configurable option in the Cronicle `conf/config.json` file, so you can make the password field default to hidden for all users of your Cronicle installation.

Let me know which of these, if any, you prefer.

**Comment by zaidoonhad** [comment]
I would prefer it to be a configurable option  in the Cronicle
conf/config.json file. Thank you.

**Comment by jhuckaby** [comment]
Done.  [Version 0.8.21](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.21) released.

I actually implemented both features, but the global default is hidden like you asked.  But you can now configure it to be visible by default server-wide, and it also saves each user's UI preference, if they toggle the state via the hide/show button thingy.

Thanks!
