### ISSUE TITLE
Enhancement request to add Category as filter criteria for a specific user

### ISSUE THREAD

**Issue by Saurabh29** [jhuckaby/Cronicle#98]
## Summary
This is an enhancement request to support:
1. While creating a user it should be possible to select the Category user can see
2. Once user logins in, the user should be able to see only jobs in the assigned category.

This will help use Cronicle in case multi-user environment.

## Steps to reproduce the problem
This is a enhancement request.

## Your Setup
0.8.21

### Operating system and version?
Redhat

### Node.js version?
10.X

### Cronicle software version?
0.8.21

### Are you using a multi-server setup, or just a single server?
Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
File system

### Can you reproduce the crash consistently?
NA

## Log Excerpts
NA

**Comment by jhuckaby** [comment]
Duplicate issue: https://github.com/jhuckaby/Cronicle/issues/33

This in the roadmap: https://github.com/jhuckaby/Cronicle/wiki/Roadmap

**Comment by jhuckaby** [comment]
Fixed in [Version 0.8.22](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.22).
